"use client";
/* eslint-disable @next/next/no-img-element -- administrators can configure approved external image hosts */

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { BookOpen, Check, ChevronRight, CircleAlert, FileQuestion, Image as ImageIcon, Pencil, Plus, Save, ShieldCheck, Trash2, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { rulesQuestionReadiness } from "@/lib/rulesLearning";
import styles from "./AdminRuleCardEditor.module.css";

type Card={id:string;stable_key:string;difficulty:"beginner"|"intermediate"|"advanced";recommended_age_min:number;recommended_age_max:number;editorial_status:string};
type Version={id:string;card_id:string;version:number;locale:string;title:string;situation:string;simple_explanation:string;action_text:string;common_mistake:string;coach_tip:string;official_reference:string;reference_version:string;illustration_prompt:string;image_url:string|null;image_alt:string;image_credit:string|null;image_status:"pending"|"approved"|"rejected";human_review_required:boolean;approved_at:string|null;rules_cards:Card};
type Option={id:string;label:string;is_correct:boolean;explanation:string;position:number};
type Question={id:string;kind:"practice"|"official";variant:number;prompt:string;explanation:string;illustration_prompt:string;image_url:string|null;image_alt:string;allows_multiple:boolean;editorial_status:"draft"|"needs_review"|"approved";rules_question_options:Option[]};
type QuestionDraft=Omit<Question,"rules_question_options">&{options:Option[]};

export default function AdminRuleCardEditor({cardVersionId}:{cardVersionId:string}){
  const [version,setVersion]=useState<Version|null>(null);const [draft,setDraft]=useState<Version|null>(null);const [questions,setQuestions]=useState<Question[]>([]);const [questionDraft,setQuestionDraft]=useState<QuestionDraft|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  const token=useCallback(async()=>{const {data}=await supabase.auth.getSession();return data.session?.access_token??"";},[]);
  const load=useCallback(async()=>{const auth=await token();const response=await fetch(`/api/admin/rules/cards/${cardVersionId}`,{headers:{Authorization:`Bearer ${auth}`},cache:"no-store"});const json=await response.json().catch(()=>({}));if(!response.ok){setError(String(json.error??"Chargement impossible."));setLoading(false);return;}setVersion(json.version);setDraft(json.version);setQuestions(json.questions??[]);setLoading(false);},[cardVersionId,token]);
  useEffect(()=>{void load();},[load]);
  const readiness=useMemo(()=>rulesQuestionReadiness(questions),[questions]);
  function update(patch:Partial<Version>){setDraft(current=>current?{...current,...patch}:current);}
  async function save(){if(!draft)return;setSaving(true);setError("");setNotice("");try{const auth=await token();const response=await fetch(`/api/admin/rules/cards/${cardVersionId}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${auth}`},body:JSON.stringify({...draft,difficulty:draft.rules_cards.difficulty,recommended_age_min:draft.rules_cards.recommended_age_min,recommended_age_max:draft.rules_cards.recommended_age_max})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(json.error??"Enregistrement impossible."));setNotice("La fiche a été enregistrée et replacée en validation éditoriale.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Enregistrement impossible.");}finally{setSaving(false);}}
  async function approve(){setSaving(true);setError("");setNotice("");try{const auth=await token();const response=await fetch(`/api/admin/rules/cards/${cardVersionId}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${auth}`},body:JSON.stringify({action:"approve"})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(json.error??"Validation impossible."));setNotice("La fiche est approuvée et verrouillée dans cette version.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Validation impossible.");}finally{setSaving(false);}}
  function newQuestion(kind:Question["kind"]){const variants=questions.filter(question=>question.kind===kind).map(question=>question.variant);setQuestionDraft({id:"",kind,variant:Math.max(0,...variants)+1,prompt:"",explanation:"",illustration_prompt:"",image_url:null,image_alt:"",allows_multiple:false,editorial_status:"draft",options:[1,2,3].map(position=>({id:"",position,label:"",is_correct:position===1,explanation:""}))});}
  function editQuestion(question:Question){setQuestionDraft({...question,options:[...question.rules_question_options].sort((a,b)=>a.position-b.position)});}
  function updateQuestion(patch:Partial<QuestionDraft>){setQuestionDraft(current=>current?{...current,...patch}:current);}
  function updateOption(index:number,patch:Partial<Option>){setQuestionDraft(current=>current?{...current,options:current.options.map((option,optionIndex)=>optionIndex===index?{...option,...patch}:option)}:current);}
  function chooseCorrect(index:number,checked:boolean){setQuestionDraft(current=>current?{...current,options:current.options.map((option,optionIndex)=>({...option,is_correct:current.allows_multiple?(optionIndex===index?checked:option.is_correct):optionIndex===index}))}:current);}
  async function saveQuestion(){if(!questionDraft)return;setSaving(true);setError("");setNotice("");try{const auth=await token();const response=await fetch(`/api/admin/rules/cards/${cardVersionId}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${auth}`},body:JSON.stringify({action:"save_question",question:questionDraft})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(json.error??"Enregistrement impossible."));setQuestionDraft(null);setNotice("La question et ses réponses ont été enregistrées.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Enregistrement impossible.");}finally{setSaving(false);}}
  async function deleteQuestion(questionId:string){if(!window.confirm("Supprimer définitivement cette question et ses réponses ?"))return;setSaving(true);setError("");try{const auth=await token();const response=await fetch(`/api/admin/rules/cards/${cardVersionId}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${auth}`},body:JSON.stringify({action:"delete_question",questionId})});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(json.error??"Suppression impossible."));setQuestionDraft(null);setNotice("La question a été supprimée.");await load();}catch(cause){setError(cause instanceof Error?cause.message:"Suppression impossible.");}finally{setSaving(false);}}
  if(loading)return <div className={styles.loading} aria-busy="true"><i/><i/><i/></div>;
  if(!draft||!version)return <div className={styles.empty}><CircleAlert/><h1>Fiche introuvable</h1><p>{error}</p><Link href="/admin/rules">Retour au module</Link></div>;
  const locked=Boolean(version.approved_at);
  return <div className={styles.page}>
    <nav className={styles.breadcrumb}><Link href="/admin">Administration</Link><ChevronRight size={14}/><Link href="/admin/rules">Règles de golf</Link><ChevronRight size={14}/><span>{draft.title}</span></nav>
    <header className={styles.topline}><div><p className={styles.eyebrow}>Fiche {draft.rules_cards.stable_key} · version {draft.version}</p><h1>{draft.title}</h1><p>Rédigez un contenu clair pour les juniors et préparez sa validation éditoriale.</p></div><span className={`${styles.status} ${locked?styles.approved:""}`}>{locked?<><ShieldCheck size={15}/>Version approuvée</>:<><CircleAlert size={15}/>Validation requise</>}</span></header>
    {error?<div className={styles.error}><CircleAlert size={17}/>{error}</div>:null}{notice?<div className={styles.success}><Check size={17}/>{notice}</div>:null}
    <section className={styles.panel}><div className={styles.panelHead}><div><span><BookOpen size={19}/></span><div><h2>Contenu pédagogique</h2><p>Tous les champs sont obligatoires avant validation.</p></div></div><button onClick={()=>void save()} disabled={saving||locked}><Save size={15}/>{saving?"Enregistrement…":"Enregistrer"}</button></div>
      <div className={styles.grid}>
        <Field label="Titre court" value={draft.title} disabled={locked} onChange={title=>update({title})}/>
        <label><span>Difficulté</span><select disabled={locked} value={draft.rules_cards.difficulty} onChange={event=>update({rules_cards:{...draft.rules_cards,difficulty:event.target.value as Card["difficulty"]}})}><option value="beginner">Débutant</option><option value="intermediate">Intermédiaire</option><option value="advanced">Avancé</option></select></label>
        <label><span>Âge minimum</span><input type="number" min={4} max={25} disabled={locked} value={draft.rules_cards.recommended_age_min} onChange={event=>update({rules_cards:{...draft.rules_cards,recommended_age_min:Number(event.target.value)}})}/></label>
        <label><span>Âge maximum</span><input type="number" min={4} max={25} disabled={locked} value={draft.rules_cards.recommended_age_max} onChange={event=>update({rules_cards:{...draft.rules_cards,recommended_age_max:Number(event.target.value)}})}/></label>
        <TextArea label="Situation concrète" value={draft.situation} disabled={locked} onChange={situation=>update({situation})}/>
        <TextArea label="Explication simple" value={draft.simple_explanation} disabled={locked} onChange={simple_explanation=>update({simple_explanation})}/>
        <TextArea label="Ce que je dois faire" value={draft.action_text} disabled={locked} onChange={action_text=>update({action_text})}/>
        <TextArea label="Erreur fréquente" value={draft.common_mistake} disabled={locked} onChange={common_mistake=>update({common_mistake})}/>
        <TextArea label="Conseil pédagogique Coach" value={draft.coach_tip} disabled={locked} onChange={coach_tip=>update({coach_tip})}/>
      </div>
    </section>
    <section className={styles.panel}><div className={styles.panelHead}><div><span><ShieldCheck size={19}/></span><div><h2>Référentiel et illustration</h2><p>Traçabilité de la règle et configuration du visuel original.</p></div></div></div><div className={styles.grid}>
      <Field label="Référence officielle" value={draft.official_reference} disabled={locked} onChange={official_reference=>update({official_reference})}/><Field label="Version du référentiel" value={draft.reference_version} disabled={locked} onChange={reference_version=>update({reference_version})}/>
      <TextArea label="Consigne d’illustration" value={draft.illustration_prompt} disabled={locked} onChange={illustration_prompt=>update({illustration_prompt})}/><TextArea label="Texte alternatif accessible" value={draft.image_alt} disabled={locked} onChange={image_alt=>update({image_alt})}/>
      <Field label="URL de l’image" value={draft.image_url??""} disabled={locked} onChange={image_url=>update({image_url})}/><Field label="Crédit éventuel" value={draft.image_credit??""} disabled={locked} onChange={image_credit=>update({image_credit})}/>
      <label><span>Validation de l’image</span><select disabled={locked} value={draft.image_status} onChange={event=>update({image_status:event.target.value as Version["image_status"]})}><option value="pending">À vérifier</option><option value="approved">Approuvée</option><option value="rejected">Refusée</option></select></label>
      <div className={styles.imagePreview}>{draft.image_url?<img src={draft.image_url} alt={draft.image_alt}/>:<><ImageIcon size={22}/><span>Aucune illustration</span></>}</div>
    </div></section>
    <section className={styles.panel}>
      <div className={styles.panelHead}><div><span><FileQuestion size={19}/></span><div><h2>Questions</h2><p>Une question d’entraînement et deux variantes officielles approuvées sont requises.</p></div></div><span className={`${styles.readiness} ${readiness.valid?styles.approved:""}`}>{readiness.practice}/1 entraînement · {readiness.official}/2 officielles</span></div>
      {!locked?<div className={styles.questionActions}><button onClick={()=>newQuestion("practice")}><Plus size={15}/>Question d’entraînement</button><button onClick={()=>newQuestion("official")}><Plus size={15}/>Variante officielle</button></div>:null}
      {questions.length?<div className={styles.questions}>{questions.map(q=><article key={q.id}><span>{q.kind==="practice"?`Entraînement ${q.variant}`:`Officielle ${q.variant}`}</span><b>{q.prompt}</b><small>{q.rules_question_options.length} réponses · {statusLabel(q.editorial_status)}</small>{!locked?<button className={styles.iconButton} onClick={()=>editQuestion(q)} aria-label={`Modifier ${q.prompt}`}><Pencil size={15}/></button>:null}</article>)}</div>:<div className={styles.questionEmpty}><FileQuestion size={20}/><b>Aucune question rédigée</b><span>Ajoutez l’entraînement et les deux variantes officielles de cette fiche.</span></div>}
      {questionDraft&&!locked?<div className={styles.questionEditor}>
        <div className={styles.editorHead}><div><b>{questionDraft.id?"Modifier la question":"Nouvelle question"}</b><span>{questionDraft.kind==="practice"?"Entraînement non classé":"Variante protégée du quiz officiel"}</span></div><button onClick={()=>setQuestionDraft(null)} aria-label="Fermer l’éditeur"><X size={17}/></button></div>
        <div className={styles.questionGrid}>
          <label><span>Type</span><select value={questionDraft.kind} onChange={event=>updateQuestion({kind:event.target.value as Question["kind"]})}><option value="practice">Entraînement</option><option value="official">Officielle</option></select></label>
          <label><span>Variante</span><input type="number" min={1} value={questionDraft.variant} onChange={event=>updateQuestion({variant:Number(event.target.value)})}/></label>
          <label><span>Statut éditorial</span><select value={questionDraft.editorial_status} onChange={event=>updateQuestion({editorial_status:event.target.value as Question["editorial_status"]})}><option value="draft">Brouillon</option><option value="needs_review">À valider</option><option value="approved">Approuvée</option></select></label>
          <label className={styles.checkbox}><input type="checkbox" checked={questionDraft.allows_multiple} onChange={event=>{const allows_multiple=event.target.checked;updateQuestion({allows_multiple,options:questionDraft.options.map((option,index)=>({...option,is_correct:index===0}))});}}/><span>Plusieurs bonnes réponses</span></label>
          <TextArea label="Énoncé" value={questionDraft.prompt} disabled={false} onChange={prompt=>updateQuestion({prompt})}/>
          <TextArea label="Explication de la bonne réponse" value={questionDraft.explanation} disabled={false} onChange={explanation=>updateQuestion({explanation})}/>
          <TextArea label="Consigne d’illustration" value={questionDraft.illustration_prompt} disabled={false} onChange={illustration_prompt=>updateQuestion({illustration_prompt})}/>
          <TextArea label="Texte alternatif" value={questionDraft.image_alt} disabled={false} onChange={image_alt=>updateQuestion({image_alt})}/>
          <Field label="URL de l’illustration (facultative)" value={questionDraft.image_url??""} disabled={false} onChange={image_url=>updateQuestion({image_url})}/>
        </div>
        <fieldset className={styles.options}><legend>Propositions de réponse</legend>{questionDraft.options.map((option,index)=><div className={styles.optionRow} key={option.position}><label className={styles.correctChoice}><input type={questionDraft.allows_multiple?"checkbox":"radio"} name="correct-option" checked={option.is_correct} onChange={event=>chooseCorrect(index,event.target.checked)}/><span>Correcte</span></label><label><span>Réponse {index+1}</span><input value={option.label} onChange={event=>updateOption(index,{label:event.target.value})}/></label><label><span>Explication affichée</span><input value={option.explanation} onChange={event=>updateOption(index,{explanation:event.target.value})}/></label>{questionDraft.options.length>3?<button onClick={()=>updateQuestion({options:questionDraft.options.filter((_,optionIndex)=>optionIndex!==index).map((item,optionIndex)=>({...item,position:optionIndex+1}))})} aria-label={`Supprimer la réponse ${index+1}`}><Trash2 size={15}/></button>:null}</div>)}</fieldset>
        <div className={styles.editorFooter}><button className={styles.secondaryButton} disabled={questionDraft.options.length>=4} onClick={()=>updateQuestion({options:[...questionDraft.options,{id:"",position:questionDraft.options.length+1,label:"",is_correct:false,explanation:""}]})}><Plus size={15}/>Ajouter une réponse</button><div>{questionDraft.id?<button className={styles.dangerButton} disabled={saving} onClick={()=>void deleteQuestion(questionDraft.id)}><Trash2 size={15}/>Supprimer</button>:null}<button className={styles.primaryButton} disabled={saving} onClick={()=>void saveQuestion()}><Save size={15}/>{saving?"Enregistrement…":"Enregistrer la question"}</button></div></div>
      </div>:null}
      {!locked?<div className={styles.approvalBar}><div><ShieldCheck size={18}/><span><b>Validation humaine</b><small>Cette action verrouille définitivement la version actuelle.</small></span></div><button onClick={()=>void approve()} disabled={saving||!readiness.valid}><ShieldCheck size={15}/>Approuver la fiche</button></div>:null}
    </section>
  </div>;
}

function Field({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean}){return <label><span>{label}</span><input value={value} disabled={disabled} onChange={event=>onChange(event.target.value)}/></label>;}
function TextArea({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean}){return <label className={styles.textArea}><span>{label}</span><textarea rows={4} value={value} disabled={disabled} onChange={event=>onChange(event.target.value)}/></label>;}
function statusLabel(status:Question["editorial_status"]){return status==="approved"?"approuvée":status==="needs_review"?"à valider":"brouillon";}
