"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import Link from "next/link";
import Image from "next/image";
import { useParams } from "next/navigation";
import type { EChartsOption } from "echarts";
import { ArrowLeft, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, Dumbbell, FileText, Flame, MapPin, Mountain, Pencil, Smile, Target, Users } from "lucide-react";
import ActiviteeEChart from "@/components/ui/ActiviteeEChart";
import ActivityDateTile from "@/components/ui/ActivityDateTile";
import PlayerBreadcrumb from "@/components/player/PlayerBreadcrumb";
import { useI18n } from "@/components/i18n/AppI18nProvider";
import { resolveEffectivePlayerContext } from "@/lib/effectivePlayer";
import type { EventEvaluationCriterion } from "@/lib/evaluationCriteria";
import { pickLocaleText } from "@/lib/i18n/pickLocaleText";
import { MANAGEMENT_CHART_COLORS } from "@/lib/managementCharts";
import { isEffectivePlayerPerformanceEnabled } from "@/lib/performanceMode";
import { supabase } from "@/lib/supabaseClient";
import corporateStyles from "@/app/manager/camps/Camps.module.css";
import { DifficultyIcon, MotivationIcon, SatisfactionIcon } from "@/components/evaluations/StandardEvaluationIcons";
import styles from "./PlayerTrainingDetail.module.css";

type SessionType = "club" | "private" | "individual";
type SessionRow = { id:string; user_id:string; start_at:string; location_text:string|null; session_type:SessionType; club_id:string|null; coach_name:string|null; motivation:number|null; difficulty:number|null; satisfaction:number|null; notes:string|null; total_minutes:number|null; club_event_id:string|null };
type StructureItem = { category:string; minutes:number; note:string|null; position?:number|null };
type CoachFeedback = { coach_id:string; engagement:number|null; attitude:number|null; performance:number|null; player_note:string|null };
type CoachProfile = { id:string; first_name:string|null; last_name:string|null; avatar_url:string|null };
type TrainingDocument = { id:string; file_name:string; created_at:string; public_url:string; uploaded_by_name?:string|null };
type CustomResponse = { event_criterion_id:string; value_json:string|number|boolean|null };
type LinkedEvent = { title?:string|null; duration_minutes?:number|null; status?:string|null };

const CATEGORY_KEYS: Record<string,string> = { warmup_mobility:"cat.warmup_mobility",long_game:"cat.long_game",short_game_all:"cat.short_game_all",putting:"cat.putting",wedging:"cat.wedging",pitching:"cat.pitching",chipping:"cat.chipping",bunker:"cat.bunker",course:"cat.course",mental:"cat.mental",fitness:"cat.fitness",other:"cat.other" };
const totalMinutes = (rows:StructureItem[]) => rows.reduce((sum,row)=>sum+Math.max(0,Number(row.minutes)||0),0);
const fullName = (profile?:CoachProfile) => `${profile?.first_name??""} ${profile?.last_name??""}`.trim()||"Coach";
const mapResponses = (rows:CustomResponse[]) => Object.fromEntries(rows.map(row=>[row.event_criterion_id,row.value_json]));
function responseLabel(criterion:EventEvaluationCriterion,value:unknown){if(value===null||value===undefined||value==="")return "—";if(criterion.snapshot_response_format==="short_text")return String(value);const choice=criterion.snapshot_choices.find(item=>String(item.value)===String(value));return choice?`${choice.icon?`${choice.icon} `:""}${choice.label}`:String(value)}
function Rating({icon,label,value}:{icon:ReactNode;label:string;value:number|null}){const score=typeof value==="number"?value:0;return <div className={styles.rating}><div className={styles.ratingLabel}>{icon}{label}</div><strong>{value??"—"}/6</strong><div className={styles.ratingTrack}><span style={{width:`${Math.max(0,Math.min(100,score/6*100))}%`}}/></div></div>}

export default function PlayerTrainingDetailPage(){
  const {t,locale}=useI18n();const params=useParams<{sessionId:string}>();const sessionId=String(params?.sessionId??"").trim();
  const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [performanceEnabled,setPerformanceEnabled]=useState(false);
  const [session,setSession]=useState<SessionRow|null>(null);const [items,setItems]=useState<StructureItem[]>([]);const [plannedItems,setPlannedItems]=useState<StructureItem[]>([]);
  const [clubName,setClubName]=useState("");const [groupName,setGroupName]=useState("");const [linkedEvent,setLinkedEvent]=useState<LinkedEvent|null>(null);
  const [coachFeedback,setCoachFeedback]=useState<CoachFeedback[]>([]);const [coachProfiles,setCoachProfiles]=useState<Record<string,CoachProfile>>({});const [documents,setDocuments]=useState<TrainingDocument[]>([]);
  const [playerCriteria,setPlayerCriteria]=useState<EventEvaluationCriterion[]>([]);const [coachCriteria,setCoachCriteria]=useState<EventEvaluationCriterion[]>([]);const [playerResponses,setPlayerResponses]=useState<Record<string,unknown>>({});const [coachResponses,setCoachResponses]=useState<Record<string,unknown>>({});

  useEffect(()=>{let cancelled=false;(async()=>{try{setLoading(true);setError(null);if(!sessionId)throw new Error(t("trainingDetail.error.missingId"));const {effectiveUserId:userId}=await resolveEffectivePlayerContext();const [perf,sessionResult,itemResult]=await Promise.all([isEffectivePlayerPerformanceEnabled(userId),supabase.from("training_sessions").select("id,user_id,start_at,location_text,session_type,club_id,coach_name,motivation,difficulty,satisfaction,notes,total_minutes,club_event_id").eq("id",sessionId).maybeSingle(),supabase.from("training_session_items").select("category,minutes,note,created_at").eq("session_id",sessionId).order("created_at",{ascending:true})]);if(sessionResult.error)throw new Error(sessionResult.error.message);if(itemResult.error)throw new Error(itemResult.error.message);const loaded=sessionResult.data as SessionRow|null;if(!loaded)throw new Error(t("trainingDetail.error.notFound"));if(loaded.user_id!==userId)throw new Error(t("trainingDetail.error.forbidden"));if(cancelled)return;setPerformanceEnabled(perf);setSession(loaded);setItems((itemResult.data??[]) as StructureItem[]);
    if(loaded.club_id){const clubResult=await supabase.from("clubs").select("name").eq("id",loaded.club_id).maybeSingle();if(!cancelled)setClubName(String(clubResult.data?.name??t("common.club")))}
    if(loaded.club_event_id){const {data:auth}=await supabase.auth.getSession();const headers=auth.session?.access_token?{Authorization:`Bearer ${auth.session.access_token}`}:undefined;const eventQuery=new URLSearchParams({event_id:loaded.club_event_id,child_id:userId});const docsQuery=new URLSearchParams({player_id:userId,club_event_id:loaded.club_event_id});const [eventResponse,docsResponse]=await Promise.all([fetch(`/api/player/training-event?${eventQuery}`,{headers,cache:"no-store"}),fetch(`/api/player/documents?${docsQuery}`,{headers,cache:"no-store"})]);const eventJson=await eventResponse.json();const docsJson=await docsResponse.json();if(!eventResponse.ok)throw new Error(String(eventJson.error??t("common.errorLoading")));if(!docsResponse.ok)throw new Error(String(docsJson.error??t("common.errorLoading")));if(cancelled)return;setLinkedEvent(eventJson.event??null);setPlannedItems(eventJson.plannedStructureItems??[]);setGroupName(String(eventJson.groupName??""));if(eventJson.clubName)setClubName(String(eventJson.clubName));setCoachFeedback(eventJson.coachFeedback??[]);setDocuments(docsJson.documents??[]);setCoachProfiles(Object.fromEntries((eventJson.coachProfiles??[]).map((profile:CoachProfile)=>[profile.id,profile])));setPlayerCriteria(eventJson.customEvaluationCriteria??[]);setCoachCriteria(eventJson.customCoachEvaluationCriteria??[]);setPlayerResponses(mapResponses(eventJson.customEvaluationResponses??[]));setCoachResponses(mapResponses(eventJson.customCoachEvaluationResponses??[]))}}
    catch(caught){if(!cancelled)setError(caught instanceof Error?caught.message:t("common.errorLoading"))}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[sessionId,t]);

  const actualTotal=totalMinutes(items);const plannedTotal=totalMinutes(plannedItems)||Number(linkedEvent?.duration_minutes??0);const duration=actualTotal||Number(session?.total_minutes??0)||plannedTotal;
  const categories=useMemo(()=>Array.from(new Set([...plannedItems,...items].map(item=>item.category))),[plannedItems,items]);const categoryLabel=(category:string)=>CATEGORY_KEYS[category]?t(CATEGORY_KEYS[category]):category;
  const completion=plannedTotal>0?Math.round(actualTotal/plannedTotal*100):null;const hasPlayerEvaluation=[session?.motivation,session?.difficulty,session?.satisfaction].some(value=>typeof value==="number")||Object.values(playerResponses).some(value=>value!==null&&value!==undefined&&value!=="");
  const structureOption:EChartsOption={animationDuration:450,color:[MANAGEMENT_CHART_COLORS[1],MANAGEMENT_CHART_COLORS[0]],tooltip:{trigger:"axis",axisPointer:{type:"shadow"},valueFormatter:value=>`${value} min`},grid:{left:8,right:8,top:24,bottom:8,containLabel:true},xAxis:{type:"value",axisLabel:{fontSize:9,color:"#7b877e",formatter:"{value} min"},splitLine:{lineStyle:{color:"#edf1eb"}}},yAxis:{type:"category",data:categories.map(categoryLabel),axisLabel:{fontSize:9,color:"#657168",width:88,overflow:"truncate"},axisTick:{show:false},axisLine:{show:false}},series:[{name:pickLocaleText(locale,"Planifié","Planned"),type:"bar",barMaxWidth:11,itemStyle:{borderRadius:5},data:categories.map(category=>plannedItems.filter(item=>item.category===category).reduce((sum,item)=>sum+item.minutes,0))},{name:pickLocaleText(locale,"Réalisé","Completed"),type:"bar",barMaxWidth:11,itemStyle:{borderRadius:5},data:categories.map(category=>items.filter(item=>item.category===category).reduce((sum,item)=>sum+item.minutes,0))}]};
  const coachAverage=(key:"engagement"|"attitude"|"performance")=>{const values=coachFeedback.map(row=>row[key]).filter((value):value is number=>typeof value==="number");return values.length?Number((values.reduce((sum,value)=>sum+value,0)/values.length).toFixed(1)):null};
  const evaluationValues=[session?.motivation,session?.difficulty,session?.satisfaction,coachAverage("engagement"),coachAverage("attitude"),coachAverage("performance")];
  const evaluationOption:EChartsOption={animationDuration:450,tooltip:{trigger:"axis",axisPointer:{type:"shadow"},valueFormatter:value=>`${value}/6`},grid:{left:8,right:12,top:18,bottom:8,containLabel:true},xAxis:{type:"value",min:0,max:6,interval:1,axisLabel:{fontSize:9,color:"#7b877e"},splitLine:{lineStyle:{color:"#edf1eb"}}},yAxis:{type:"category",data:[t("trainingNew.motivationBefore"),t("trainingNew.difficultyDuring"),t("trainingNew.satisfactionAfter"),t("trainingDetail.engagement"),t("trainingDetail.attitude"),t("trainingDetail.performance")],axisLabel:{fontSize:9,color:"#657168",width:90,overflow:"truncate"},axisTick:{show:false},axisLine:{show:false}},series:[{type:"bar",barMaxWidth:13,data:evaluationValues.map((value,index)=>({value:value??0,itemStyle:{color:index<3?MANAGEMENT_CHART_COLORS[1]:MANAGEMENT_CHART_COLORS[0],borderRadius:6}}))}]};

  if(loading)return <div className="player-dashboard-bg"><div className="app-shell marketplace-page"><div className={styles.loading} aria-label={t("common.loading")}/></div></div>;
  const start=session?new Date(session.start_at):null;const end=start?new Date(start.getTime()+duration*60000):null;const trainingTitle=linkedEvent?.title||(groupName?`${pickLocaleText(locale,"Entraînement","Training")} • ${groupName}`:t("trainingDetail.title"));const dateLocale=locale==="en"?"en-US":"fr-CH";const timeRange=start&&end?`${new Intl.DateTimeFormat(dateLocale,{hour:"2-digit",minute:"2-digit"}).format(start)} – ${new Intl.DateTimeFormat(dateLocale,{hour:"2-digit",minute:"2-digit"}).format(end)}`:"—";
  return <div className="player-dashboard-bg"><div className="app-shell marketplace-page"><div className={styles.page}>
    <PlayerBreadcrumb items={[{label:"Player",href:"/player"},{label:pickLocaleText(locale,"Activités","Activities"),href:"/player/golf/trainings"},{label:pickLocaleText(locale,"Détail","Detail")}]}/>
    <header className={corporateStyles.topline}><div><h1>{pickLocaleText(locale,"Détail de l’activité","Activity details")}</h1><p className={corporateStyles.lead}>{pickLocaleText(locale,"Retrouve le contenu réalisé et les évaluations de cette activité.","Review the completed content and evaluations for this activity.")}</p></div><div className={corporateStyles.actions}><Link className={corporateStyles.secondary} href="/player/golf/trainings"><ArrowLeft size={15}/>{pickLocaleText(locale,"Retour aux activités","Back to activities")}</Link>{session&&<Link className={corporateStyles.primary} href={`/player/golf/trainings/${sessionId}/edit`}><Pencil size={14}/>{hasPlayerEvaluation?t("common.edit"):pickLocaleText(locale,"Évaluer","Evaluate")}</Link>}</div></header>
    {error&&<div className={styles.error}>{error}</div>}{!session?<div className={styles.panel}><div className={styles.empty}>{t("common.noData")}</div></div>:<>
      <section className={styles.hero}><ActivityDateTile startsAt={session.start_at} locale={dateLocale} className={styles.dateTile} showYear/><div className={styles.heroContent}><span className={styles.eyebrow}><Dumbbell size={12}/>{session.club_event_id?pickLocaleText(locale,"Activité du club","Club activity"):pickLocaleText(locale,"Activité personnelle","Personal activity")}</span><h2>{trainingTitle}</h2>{clubName&&<p>{pickLocaleText(locale,"Organisé par","Organized by")} {clubName}</p>}<div className={styles.meta}><span><Clock3 size={14}/>{timeRange}</span>{session.location_text&&<span><MapPin size={14}/>{session.location_text}</span>}{groupName&&<span><Users size={14}/>{groupName}</span>}</div></div><span className={styles.status}><CheckCircle2 size={14}/>{hasPlayerEvaluation?pickLocaleText(locale,"Évaluée","Evaluated"):pickLocaleText(locale,"À évaluer","To evaluate")}</span></section>
      <section className={styles.kpis}><Kpi icon={<Clock3 size={16}/>} title={pickLocaleText(locale,"Durée réalisée","Completed duration")} value={duration?`${duration} min`:"—"} detail={timeRange}/><Kpi icon={<Dumbbell size={16}/>} title={pickLocaleText(locale,"Secteurs travaillés","Areas trained")} value={String(categories.length)} detail={pickLocaleText(locale,"Domaines de jeu","Game areas")}/><Kpi icon={<Target size={16}/>} title={pickLocaleText(locale,"Plan réalisé","Plan completed")} value={completion===null?"—":`${completion}%`} detail={plannedTotal?`${actualTotal} / ${plannedTotal} min`:pickLocaleText(locale,"Pas de plan coach","No coach plan")}/><Kpi icon={<ClipboardCheck size={16}/>} title={pickLocaleText(locale,"Évaluation","Evaluation")} value={hasPlayerEvaluation?pickLocaleText(locale,"Faite","Done"):pickLocaleText(locale,"À faire","Pending")} detail={playerCriteria.length?`${playerCriteria.length} ${pickLocaleText(locale,"critère(s) club","club criteria")}`:pickLocaleText(locale,"Critères ActiviTee","ActiviTee criteria")}/></section>
      {performanceEnabled&&<section className={styles.grid}><ChartPanel title={pickLocaleText(locale,"Volume par secteur","Volume by area")} subtitle={pickLocaleText(locale,"Comparaison du programme coach et du travail réalisé.","Coach plan compared with completed work.")} option={categories.length?structureOption:null} aria={pickLocaleText(locale,"Volume planifié et réalisé","Planned and completed volume")} empty={pickLocaleText(locale,"Aucune structure renseignée.","No structure entered.")} labels={[pickLocaleText(locale,"Planifié","Planned"),pickLocaleText(locale,"Réalisé","Completed")]}/><ChartPanel title={pickLocaleText(locale,"Synthèse des évaluations","Evaluation summary")} subtitle={pickLocaleText(locale,"Auto-évaluation junior et regard du coach, sur 6.","Junior self-assessment and coach view, out of 6.")} option={evaluationValues.some(value=>typeof value==="number")?evaluationOption:null} aria={pickLocaleText(locale,"Synthèse des évaluations","Evaluation summary")} empty={pickLocaleText(locale,"Les évaluations apparaîtront ici une fois complétées.","Evaluations will appear here once completed.")} labels={["Junior","Coach"]}/></section>}
      {performanceEnabled&&<section className={`${styles.panel} ${styles.wide}`}><PanelHeader title={pickLocaleText(locale,"Structure de l’entraînement","Training structure")} subtitle={pickLocaleText(locale,"Le programme prévu et ce qui a réellement été effectué.","The planned programme and what was actually completed.")}/><div className={styles.structureGrid}><StructureColumn title={pickLocaleText(locale,"Planifié par le coach","Planned by coach")} items={plannedItems} label={categoryLabel} empty={pickLocaleText(locale,"Aucun contenu planifié.","No planned content.")}/><StructureColumn title={pickLocaleText(locale,"Réalisé par le joueur","Completed by player")} items={items} label={categoryLabel} empty={pickLocaleText(locale,"Aucun contenu renseigné.","No completed content entered.")}/></div></section>}
      <section className={styles.grid}><article className={styles.panel}><PanelHeader title={pickLocaleText(locale,"Mon auto-évaluation","My self-assessment")} subtitle={pickLocaleText(locale,"Les 3 critères ActiviTee junior et les priorités du club.","The 3 junior ActiviTee criteria and club priorities.")}/><div className={styles.ratings}><Rating icon={<MotivationIcon size={15}/>} label={t("trainingNew.motivationBefore")} value={session.motivation}/><Rating icon={<DifficultyIcon size={15}/>} label={t("trainingNew.difficultyDuring")} value={session.difficulty}/><Rating icon={<SatisfactionIcon size={15}/>} label={t("trainingNew.satisfactionAfter")} value={session.satisfaction}/></div><CriteriaList criteria={playerCriteria} responses={playerResponses}/>{session.notes&&<p className={styles.note}>{session.notes}</p>}</article><article className={styles.panel}><PanelHeader title={t("trainingDetail.coachEvaluation")} subtitle={pickLocaleText(locale,"Les 3 critères ActiviTee coach et les priorités du club.","The 3 coach ActiviTee criteria and club priorities.")}/>{coachFeedback.length?<div className={styles.coach}>{coachFeedback.map((feedback,index)=>{const profile=coachProfiles[feedback.coach_id];return <div key={`${feedback.coach_id}-${index}`}><div className={styles.coachIdentity}><div className={styles.avatar}>{profile?.avatar_url?<Image src={profile.avatar_url} alt="" width={34} height={34} unoptimized/>:`${profile?.first_name?.[0]??"C"}${profile?.last_name?.[0]??""}`}</div><div><b>{fullName(profile)}</b><small>{t("common.coach")}</small></div></div><div className={styles.ratings}><Rating icon={<Flame size={14}/>} label={t("trainingDetail.engagement")} value={feedback.engagement}/><Rating icon={<Mountain size={14}/>} label={t("trainingDetail.attitude")} value={feedback.attitude}/><Rating icon={<Smile size={14}/>} label={t("trainingDetail.performance")} value={feedback.performance}/></div>{feedback.player_note&&<p className={styles.note}>{feedback.player_note}</p>}</div>})}<CriteriaList criteria={coachCriteria} responses={coachResponses}/></div>:<div className={styles.empty}>{t("trainingDetail.noCoachEvaluation")}</div>}</article></section>
      {session.club_event_id&&<section className={`${styles.panel} ${styles.wide}`}><PanelHeader title={pickLocaleText(locale,"Documents liés","Related documents")} subtitle={pickLocaleText(locale,"Supports partagés par l’équipe d’encadrement.","Resources shared by the coaching team.")}/>{documents.length?<div className={styles.documents}>{documents.map(document=><a className={styles.document} href={document.public_url} target="_blank" rel="noreferrer" key={document.id}><span className={styles.documentIcon}><FileText size={16}/></span><span><b>{document.file_name}</b><small>{document.uploaded_by_name?`${document.uploaded_by_name} • `:""}{new Intl.DateTimeFormat(dateLocale).format(new Date(document.created_at))}</small></span><ChevronRight size={15}/></a>)}</div>:<div className={styles.empty}>{pickLocaleText(locale,"Aucun document lié à cette activité.","No document linked to this activity.")}</div>}</section>}
    </>}</div></div></div>}

function Kpi({icon,title,value,detail}:{icon:ReactNode;title:string;value:string;detail:string}){return <div className={styles.kpi}><div className={styles.kpiIcon}>{icon}</div><span>{title}</span><strong>{value}</strong><small>{detail}</small></div>}
function PanelHeader({title,subtitle}:{title:string;subtitle:string}){return <div className={styles.panelHeader}><div><h2>{title}</h2><p>{subtitle}</p></div></div>}
function ChartPanel({title,subtitle,option,aria,empty,labels}:{title:string;subtitle:string;option:EChartsOption|null;aria:string;empty:string;labels:[string,string]}){return <article className={styles.panel}><PanelHeader title={title} subtitle={subtitle}/>{option?<><div className={styles.chart}><ActiviteeEChart option={option} ariaLabel={aria} height={270}/></div><div className={styles.legend}><span><i style={{background:MANAGEMENT_CHART_COLORS[1]}}/> {labels[0]}</span><span><i style={{background:MANAGEMENT_CHART_COLORS[0]}}/> {labels[1]}</span></div></>:<div className={styles.empty}>{empty}</div>}</article>}
function StructureColumn({title,items,label,empty}:{title:string;items:StructureItem[];label:(category:string)=>string;empty:string}){return <div className={styles.structureColumn}><h3>{title}</h3>{items.length?items.map((item,index)=><div className={styles.structureItem} key={`${item.category}-${index}`}><b>{label(item.category)}</b><strong>{item.minutes} min</strong>{item.note&&<small>{item.note}</small>}</div>):<div className={styles.empty}>{empty}</div>}</div>}
function CriteriaList({criteria,responses}:{criteria:EventEvaluationCriterion[];responses:Record<string,unknown>}){if(!criteria.length)return null;return <div className={styles.criteria}>{criteria.map(criterion=><div className={styles.criterion} key={criterion.id}><b>{criterion.snapshot_name}</b><strong>{responseLabel(criterion,responses[criterion.id])}</strong>{criterion.snapshot_description&&<small>{criterion.snapshot_description}</small>}</div>)}</div>}
