"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, RefreshCw, Save } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import styles from "@/components/admin/AdminHomeStats.module.css";
import actionStyles from "@/components/admin/organizations/OrganizationSettingsAdmin.module.css";
import navigationStyles from "@/app/design-system/design-system.module.css";
import ManagerCoachStatistics from "@/components/manager/ManagerCoachStatistics";
import permissionStyles from "@/components/manager/CoachPermissions.module.css";

type Value = string | boolean | string[];
type Season = { id: string; name: string; starts_on: string; ends_on: string; is_current: boolean };
type Field = { id: string; label: string; field_type: string; options_json?: string[]; scope: "permanent" | "season"; applies_to_roles?: string[]; is_active: boolean; description?: string | null };
type Coach = { id: string; user_id: string; role: string; auth_email?: string | null; is_active: boolean | null; can_manage_assigned_groups?: boolean; can_manage_assigned_group_planning?: boolean; can_transfer_players_between_club_groups?: boolean; custom_field_values?: Record<string, Value>; profiles: { first_name: string | null; last_name: string | null; username: string | null; staff_function: string | null; phone: string | null; address: string | null; postal_code: string | null; city: string | null } | null };
type SeasonRecord = { club_member_id: string; registration_status: "active" | "inactive"; custom_field_values?: Record<string, Value> };
async function headers() { const { data } = await supabase.auth.getSession(); return data.session?.access_token ? { Authorization: `Bearer ${data.session.access_token}` } : {}; }

export default function CoachEditPage({ memberId }: { memberId: string }) {
  const query = useSearchParams(); const clubId = query.get("club") ?? ""; const backUrl = `/manager/user-management/coaches${clubId ? `?club=${clubId}` : ""}`;
  const [tab, setTab] = useState<"profile" | "statistics">(query.get("tab") === "statistics" ? "statistics" : "profile");
  const [coach, setCoach] = useState<Coach | null>(null); const [seasons, setSeasons] = useState<Season[]>([]); const [seasonId, setSeasonId] = useState(query.get("season") ?? ""); const [fields, setFields] = useState<Field[]>([]); const [seasonValues, setSeasonValues] = useState<Record<string, Value>>({}); const [seasonStatus, setSeasonStatus] = useState<"active" | "inactive">("active"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ first_name: "", last_name: "", username: "", email: "", password: "", staff_function: "", phone: "", address: "", postal_code: "", city: "", is_active: true, can_manage_assigned_groups: false, can_manage_assigned_group_planning: false, can_transfer_players_between_club_groups: false, custom: {} as Record<string, Value> });
  const permanentFields = useMemo(() => fields.filter((field) => field.scope === "permanent" && field.is_active && (!field.applies_to_roles?.length || field.applies_to_roles.includes("coach"))), [fields]); const seasonalFields = useMemo(() => fields.filter((field) => field.scope === "season" && field.is_active && (!field.applies_to_roles?.length || field.applies_to_roles.includes("coach"))), [fields]);
  async function load() { if (!clubId) return; setLoading(true); try { const auth = await headers(); const [members, seasonsRes] = await Promise.all([fetch(`/api/manager/clubs/${clubId}/members`, { headers: auth }), fetch(`/api/manager/clubs/${clubId}/seasons`, { headers: auth })]); const mj = await members.json(); const sj = await seasonsRes.json(); if (!members.ok || !seasonsRes.ok) throw new Error(mj.error ?? sj.error); const next = (mj.members ?? []).find((item: Coach) => item.id === memberId && item.role === "coach"); if (!next) throw new Error("Coach introuvable."); const nextSeasons = sj.seasons ?? []; const selected = nextSeasons.some((item: Season) => item.id === seasonId) ? seasonId : nextSeasons.find((item: Season) => item.is_current)?.id ?? nextSeasons[0]?.id ?? ""; const p = next.profiles; setCoach(next); setFields(mj.playerFields ?? []); setSeasons(nextSeasons); setSeasonId(selected); setForm({ first_name: p?.first_name ?? "", last_name: p?.last_name ?? "", username: p?.username ?? "", email: next.auth_email?.endsWith("@noemail.local") ? "" : next.auth_email ?? "", password: "", staff_function: p?.staff_function ?? "", phone: p?.phone ?? "", address: p?.address ?? "", postal_code: p?.postal_code ?? "", city: p?.city ?? "", is_active: next.is_active !== false, can_manage_assigned_groups: Boolean(next.can_manage_assigned_groups), can_manage_assigned_group_planning: Boolean(next.can_manage_assigned_group_planning), can_transfer_players_between_club_groups: Boolean(next.can_transfer_players_between_club_groups), custom: next.custom_field_values ?? {} }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }
  async function loadSeason(id: string) { if (!id) return; try { const r = await fetch(`/api/manager/clubs/${clubId}/seasons/${id}/coach-records`, { headers: await headers() }); const j = await r.json(); if (!r.ok) throw new Error(j.error); const record = (j.records ?? []).find((item: SeasonRecord) => item.club_member_id === memberId); setSeasonStatus(record?.registration_status ?? "active"); setSeasonValues(record?.custom_field_values ?? {}); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement de la saison impossible."); } }
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { void loadSeason(seasonId); }, [seasonId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function saveProfile(e: React.FormEvent) { e.preventDefault(); if (!coach || !form.first_name.trim() || !form.last_name.trim()) return; setSaving(true); setError(""); try { const r = await fetch(`/api/manager/clubs/${clubId}/members`, { method: "PATCH", headers: { "Content-Type": "application/json", ...(await headers()) }, body: JSON.stringify({ memberId, role: "coach", first_name: form.first_name, last_name: form.last_name, username: form.username, auth_email: form.email, auth_password: form.password, staff_function: form.staff_function, phone: form.phone, address: form.address, postal_code: form.postal_code, city: form.city, is_active: form.is_active, can_manage_assigned_groups: form.can_manage_assigned_groups, can_manage_assigned_group_planning: form.can_manage_assigned_group_planning, can_transfer_players_between_club_groups: form.can_transfer_players_between_club_groups, custom_field_values: form.custom }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error); setMessage("Profil et permissions enregistrés."); setForm((current) => ({ ...current, password: "" })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setSaving(false); } }
  async function saveSeason(e: React.FormEvent) { e.preventDefault(); if (!seasonId) return; setSaving(true); setError(""); try { const r = await fetch(`/api/manager/clubs/${clubId}/seasons/${seasonId}/coach-records`, { method: "PATCH", headers: { "Content-Type": "application/json", ...(await headers()) }, body: JSON.stringify({ member_ids: [memberId], registration_status: seasonStatus, custom_field_values: seasonValues }) }); const j = await r.json(); if (!r.ok) throw new Error(j.error); setMessage("Paramètres enregistrés."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setSaving(false); } }
  if (loading) return <div className={styles.page}><ListLoadingBlock label="Chargement de la fiche coach…" /></div>;
  const name = [coach?.profiles?.first_name, coach?.profiles?.last_name].filter(Boolean).join(" ") || "Coach";
  const selectedSeason = seasons.find((season) => season.id === seasonId);
  return <div className={styles.page}>
    <nav aria-label="Fil d’Ariane" style={{ minHeight: 22, color: "#35483b", fontSize: 11, fontWeight: 700 }}><Link href={backUrl}>Coachs</Link><span aria-hidden="true" style={{ margin: "0 8px" }}>/</span><span>Fiche coach</span></nav>
    <div className={styles.topline}><div><h1>{name}</h1><p className={styles.lead}>Profil, paramètres saisonniers et activité du coach.</p></div><div className={actionStyles.topActions}><label className="groups-season-nav-select"><select aria-label="Saison" value={seasonId} onChange={(e) => setSeasonId(e.target.value)}>{seasons.map((season) => <option key={season.id} value={season.id}>{season.name}{season.is_current ? " · En cours" : ""}</option>)}</select></label><Link className={actionStyles.backButton} href={backUrl}><ArrowLeft size={16}/>Retour à la liste</Link></div></div>
    {error ? <div className={actionStyles.errorAlert}>{error}</div> : null}{message ? <div className={actionStyles.successAlert}>{message}</div> : null}
    <section className={styles.overview}><div className={navigationStyles.tabs} role="tablist" aria-label="Sections de la fiche coach"><button type="button" role="tab" aria-selected={tab === "profile"} onClick={() => setTab("profile")}>Profil</button><button type="button" role="tab" aria-selected={tab === "statistics"} onClick={() => setTab("statistics")}>Statistiques</button></div></section>
    {tab === "profile" ? <>
      <form onSubmit={saveProfile}><section className={styles.overview}><div className={styles.sectionHeading}><div><h2>Profil du coach</h2></div></div><div className="user-mgmt-form-grid"><Text label="Prénom" value={form.first_name} onChange={(v) => setForm({ ...form, first_name: v })}/><Text label="Nom" value={form.last_name} onChange={(v) => setForm({ ...form, last_name: v })}/><Text label="Nom d’utilisateur" value={form.username} onChange={(v) => setForm({ ...form, username: v })}/><Text label="Fonction" value={form.staff_function} onChange={(v) => setForm({ ...form, staff_function: v })}/><Text label="Adresse e-mail" type="email" value={form.email} onChange={(v) => setForm({ ...form, email: v })}/><Text label="Nouveau mot de passe" type="password" value={form.password} onChange={(v) => setForm({ ...form, password: v })}/><Text label="Téléphone" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })}/>{permanentFields.map((field) => <Custom key={field.id} field={field} value={form.custom[field.id]} onChange={(v) => setForm({ ...form, custom: { ...form.custom, [field.id]: v } })}/>)}</div><Link className={actionStyles.secondaryButton} href="/manager/user-management/custom-fields">Ajouter des champs</Link><Actions saving={saving} label="Enregistrer le profil"/></section></form>
      <form onSubmit={saveProfile}>
        <section className={`${styles.overview} ${permissionStyles.card}`}>
          <div className={styles.sectionHeading}><div><h2>Permissions Coach</h2><p>Ces droits s’appliquent uniquement à ce club et sont désactivés par défaut.</p></div></div>
          <div className={permissionStyles.presets} aria-label="Profils de permissions">
            <button type="button" onClick={() => setForm({ ...form, can_manage_assigned_groups: false, can_manage_assigned_group_planning: false, can_transfer_players_between_club_groups: false })}>Coach encadrant</button>
            <button type="button" onClick={() => setForm({ ...form, can_manage_assigned_groups: false, can_manage_assigned_group_planning: true, can_transfer_players_between_club_groups: false })}>Coach planificateur</button>
            <button type="button" onClick={() => setForm({ ...form, can_manage_assigned_groups: true, can_manage_assigned_group_planning: true, can_transfer_players_between_club_groups: false })}>Responsable de groupe</button>
            <button type="button" onClick={() => setForm({ ...form, can_transfer_players_between_club_groups: true })}>Head Coach</button>
          </div>
          <div className={permissionStyles.switches}>
            <PermissionSwitch label="Autoriser la gestion de ses groupes" description="Composition, catégories et informations opérationnelles de ses groupes." checked={form.can_manage_assigned_groups} onChange={(checked) => setForm({ ...form, can_manage_assigned_groups: checked })} />
            <PermissionSwitch label="Autoriser la planification des activités" description="Création et modification des activités de ses groupes, sans gérer les autres coachs." checked={form.can_manage_assigned_group_planning} onChange={(checked) => setForm({ ...form, can_manage_assigned_group_planning: checked })} />
            <PermissionSwitch label="Head Coach — autoriser la mobilité des juniors" description="Déplacement de juniors entre les groupes de ce club, sans accès aux paramètres Manager." checked={form.can_transfer_players_between_club_groups} onChange={(checked) => setForm({ ...form, can_transfer_players_between_club_groups: checked })} />
          </div>
          <Actions saving={saving} label="Enregistrer les permissions"/>
        </section>
      </form>
      <form onSubmit={saveSeason}><section className={styles.quickPanel}><div className={styles.sectionHeading}><div><h2>Paramètres de saison</h2></div></div><div className="user-mgmt-form-grid"><label className="user-mgmt-field"><span className="user-mgmt-field-label">Statut</span><select value={seasonStatus} onChange={(e) => setSeasonStatus(e.target.value as "active" | "inactive")}><option value="active">Actif</option><option value="inactive">Inactif</option></select></label>{seasonalFields.map((field) => <Custom key={field.id} field={field} value={seasonValues[field.id]} onChange={(v) => setSeasonValues({ ...seasonValues, [field.id]: v })}/>)}</div><Link className={actionStyles.secondaryButton} href="/manager/user-management/custom-fields">Ajouter des champs</Link><Actions saving={saving} label="Enregistrer les paramètres"/></section></form>
    </> : coach ? <ManagerCoachStatistics clubId={clubId} coachId={coach.user_id} seasonId={seasonId} seasonFrom={selectedSeason?.starts_on} seasonTo={selectedSeason?.ends_on}/> : null}
  </div>;
}
function Text({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (v: string) => void; type?: string }) { return <label className="user-mgmt-field"><span className="user-mgmt-field-label">{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function PermissionSwitch({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className={permissionStyles.switchRow}><span><b>{label}</b><small>{description}</small></span><input type="checkbox" role="switch" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
function Custom({ field, value, onChange }: { field: Field; value?: Value; onChange: (v: Value) => void }) { const options = field.options_json ?? []; const control = field.field_type === "select" ? <select value={String(value ?? "")} onChange={(e) => onChange(e.target.value)}><option value="">Choisir</option>{options.map((option) => <option key={option}>{option}</option>)}</select> : field.field_type === "boolean" ? <select value={value === true ? "yes" : value === false ? "no" : ""} onChange={(e) => onChange(e.target.value === "yes")}><option value="">Non défini</option><option value="yes">Oui</option><option value="no">Non</option></select> : field.field_type === "long_text" ? <textarea value={String(value ?? "")} onChange={(e) => onChange(e.target.value)} /> : <input type={field.field_type === "number" ? "number" : field.field_type === "date" ? "date" : "text"} value={String(value ?? "")} onChange={(e) => onChange(e.target.value)} />; return <label className="user-mgmt-field"><span className="user-mgmt-field-label">{field.label}</span>{control}{field.description ? <small>{field.description}</small> : null}</label>; }
function Actions({ saving, label }: { saving: boolean; label: string }) { return <div className={actionStyles.topActions} style={{ justifyContent: "flex-end", marginTop: 16 }}><button className={actionStyles.primaryButton} type="submit" disabled={saving}>{saving ? <RefreshCw size={16} className={styles.spin} /> : <Save size={16} />}{saving ? "Enregistrement…" : label}</button></div>; }
