"use client";

import Link from "next/link";
import { useManagerPerformanceLabels } from "./useManagerPerformanceLabels";
import type { ManagerAttentionValue } from "@/lib/managerPerformancePresentation";
import ManagerClubSelect from "./ManagerClubSelect";
import { useManagerResource } from "./useManagerResource";
import { useMemo, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import styles from "@/components/manager/Performance.module.css";
import coachStyles from "@/components/manager/CoachPerformance.module.css";
import tableStyles from "@/components/manager/PerformanceTables.module.css";
import PerformanceAppliedPeriod from "@/components/manager/PerformanceAppliedPeriod";
import ManagerStatisticsTabs from "@/components/manager/ManagerStatisticsTabs";
import ManagerMemberAvatar from "@/components/manager/ManagerMemberAvatar";
import { usePerformanceContext } from "@/components/manager/usePerformanceContext";

type Tab = "overview" | "load" | "coverage" | "evaluations" | "attention";
type CoachRow = { id: string; memberId: string; name: string; avatarUrl: string | null; function: string | null; active: boolean; groups: Array<{ id: string; name: string; role: string; juniors: number }>; groupCount: number; headGroupCount: number; role: string; activities: number; coachHours: number; previousCoachHours: number; uniquePlayers: number; medianGroupSize: number | null; activeWeeks: number; camps: number; evaluationsExpected: number; evaluationsCompleted: number; evaluationsInProgress: number; evaluationsOverdue: number; visibleFeedbackRate: number | null; lastActivity: string | null };
type Data = { range: { from: string; to: string }; filters: { groups: Array<{ id: string; name: string }> }; overview: { activeCoaches: number; activities: number; activityHours: number; coachHours: number; medianPlayers: number | null; coverageRate: number | null; evaluationCompletionRate: number | null; pendingAttendance: number }; distribution: { medianCoachHours: number | null; monthly: Array<{ month: string; activities: number; activityHours: number; coachHours: number }> }; coverage: { groupsWithoutHead: Array<{ id: string; name: string }>; singleCoachGroups: Array<{ id: string; name: string }>; futureWithoutCoach: Array<{ id: string; title: string; startsAt: string }> }; evaluations: { expected: number; completed: number; overdue: number; completionRate: number | null }; rows: CoachRow[]; attention: Array<ManagerAttentionValue & { reason: string; label: string; href: string }> };
const presets = { season: 0, "30d": 30, "3m": 3, "6m": 6, "12m": 12 } as const;

export default function ManagerCoachPerformancePage() {
  const { t, metric, date: formatDate, month, format, coachAttention } = useManagerPerformanceLabels();
  const tabs: ReadonlyArray<{ value: Tab; label: string }> = [
  { value: "overview", label: t("manager.performance.overview") },
  { value: "load", label: t("manager.performance.load") },
  { value: "coverage", label: t("manager.performance.coverage") },
  { value: "evaluations", label: t("manager.performance.evaluations") },
  { value: "attention", label: t("manager.performance.attention") },
];
  const context = usePerformanceContext(); const [tab, setTab] = useState<Tab>("overview");
  const [preset, setPreset] = useState<keyof typeof presets | "custom">("season"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [groupSelection, setGroupSelection] = useState({ scope: "", id: "all" });
  const filterScope = `${context.clubId}:${context.seasonId}`;
  const group = groupSelection.scope === filterScope ? groupSelection.id : "all";
  const setGroup = (id: string) => setGroupSelection({ scope: filterScope, id }); const [role, setRole] = useState("all"); const [status, setStatus] = useState("active");
  const season = context.seasons.find((item) => item.id === context.seasonId);
  const range = useMemo(() => { const today = new Date(); const todayKey = today.toISOString().slice(0, 10); if (preset === "season") return { from: season?.starts_on ?? "", to: season?.ends_on && season.ends_on < todayKey ? season.ends_on : todayKey }; if (preset === "custom") return { from, to }; const start = new Date(today); if (preset === "30d") start.setUTCDate(start.getUTCDate() - 29); else start.setUTCMonth(start.getUTCMonth() - presets[preset]); return { from: start.toISOString().slice(0, 10), to: todayKey }; }, [from, preset, season, to]);
  const validRange = Boolean(range.from && range.to && range.from <= range.to);
  const query = new URLSearchParams({ season: context.seasonId, from: range.from, to: range.to, group, role, status });
  const resource = useManagerResource<Data>(context.clubId && context.seasonId && validRange ? `/api/manager/clubs/${context.clubId}/performance/coaches?${query}` : null, t("manager.loadError"));
  const { data, loading, error } = resource;
  const refreshing = loading && Boolean(data);
  return <div className={`${styles.page} ${tableStyles.scope}`}>
    <nav aria-label={t("common.breadcrumb")} className={styles.breadcrumb}>{t("manager.performance.coachBreadcrumb")}</nav>
    <div className={styles.topline}><div><h1>{t("manager.performance.coachTitle")}</h1><p className={styles.lead}>{t("manager.performance.coachLead")}</p></div><div className={styles.toolbarActions}><ManagerClubSelect clubs={context.clubs} clubId={context.clubId} onChange={context.setClubId} /><label className="groups-season-nav-select"><select aria-label={t("manager.season")} disabled={!context.seasons.length} value={context.seasonId} onChange={(event) => context.setSeasonId(event.target.value)}>{!context.seasonId ? <option value="">{t(context.seasons.length ? "manager.chooseSeason" : "manager.noSeason")}</option> : null}{context.seasons.map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_current ? ` · ${t("manager.current")}` : ""}</option>)}</select></label><button type="button" className={styles.refresh} disabled={loading || !context.seasonId || !validRange} onClick={resource.reload}><RefreshCw size={14}/>{refreshing ? t("manager.refreshing") : t("manager.refresh")}</button></div></div>
    {context.error || error ? <div className={styles.error} role="alert"><AlertTriangle size={15}/> {context.error || error}</div> : null}
    {!context.loading && context.seasonId && !validRange ? <p role="status">{t("manager.invalidPeriod")}</p> : null}
    <section className={campStyles.panel}><div className={styles.filters}><label>{t("manager.performance.period")}<select value={preset} onChange={(event) => setPreset(event.target.value as typeof preset)}><option value="season">{t("manager.performance.season")}</option><option value="30d">{t("manager.performance.days30")}</option><option value="3m">{t("manager.performance.months3")}</option><option value="6m">{t("manager.performance.months6")}</option><option value="12m">{t("manager.performance.months12")}</option><option value="custom">{t("manager.performance.custom")}</option></select></label>{preset === "custom" ? <><label>{t("manager.performance.from")}<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)}/></label><label>{t("manager.performance.to")}<input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)}/></label></> : null}<label>{t("manager.performance.group")}<select value={group} onChange={(event) => setGroup(event.target.value)}><option value="all">{t("manager.performance.all")}</option>{data?.filters.groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t("manager.performance.role")}<select value={role} onChange={(event) => setRole(event.target.value)}><option value="all">{t("manager.performance.all")}</option><option value="head">{t("manager.performance.head")}</option><option value="assistant">{t("manager.performance.assistant")}</option></select></label><label>{t("manager.performance.status")}<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="active">{t("manager.performance.active")}</option><option value="inactive">{t("manager.performance.inactive")}</option><option value="all">{t("manager.performance.all")}</option></select></label></div><PerformanceAppliedPeriod from={range.from} to={range.to}/></section>
    <ManagerStatisticsTabs<Tab> items={tabs} value={tab} onChange={setTab} ariaLabel={t("manager.performance.coachSections")} />
    {(loading || context.loading) && !data ? <section className={campStyles.panel}><ListLoadingBlock label={t("manager.performance.loadingCoaches")}/></section> : data ? <>
      {tab === "overview" ? <><div className={styles.kpis}><Kpi label={t("manager.performance.activeCoaches")} value={String(data.overview.activeCoaches)} detail={t("manager.performance.activeHelp")}/><Kpi label={t("manager.performance.completedActivities")} value={String(data.overview.activities)} detail={t("manager.performance.uniqueActivities")}/><Kpi label={t("manager.performance.activityHours")} value={metric(data.overview.activityHours," h")} detail={t("manager.performance.noDoubleCount")}/><Kpi label={t("manager.performance.coachHours")} value={metric(data.overview.coachHours," h")} detail={t("manager.performance.coachHoursHelp")}/><Kpi label={t("manager.performance.medianJuniors")} value={metric(data.overview.medianPlayers)} detail={t("manager.performance.distinctJuniors")}/><Kpi label={t("manager.performance.coverage")} value={metric(data.overview.coverageRate," %")} detail={t("manager.performance.explicitCoach")}/><Kpi label={t("manager.performance.evaluations")} value={metric(data.overview.evaluationCompletionRate," %")} detail={t("manager.performance.attributableEvaluations")}/><Kpi label={t("manager.performance.pendingAttendance")} value={String(data.overview.pendingAttendance)} detail={t("manager.performance.pendingStatuses")}/></div><CoachTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId}/></> : null}
      {tab === "load" ? <section className={campStyles.panel}><Header title={t("manager.performance.loadDistribution")} text={format("loadHelp", { hours: data.distribution.medianCoachHours == null ? metric(null) : format("coachHoursValue", { hours: metric(data.distribution.medianCoachHours) }) })}/><div className={styles.chart} role="img" aria-label={t("manager.performance.monthlyHours")}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.distribution.monthly}><CartesianGrid stroke="#e7ece6" vertical={false}/><XAxis tickFormatter={month} dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}} unit=" h"/><Tooltip labelFormatter={(label) => month(String(label))} formatter={(value) => metric(Number(value), " h")}/><Legend/><Bar dataKey="activityHours" name={t("manager.performance.activityHours")} fill="#9eafa0" radius={[4,4,0,0]}/><Bar dataKey="coachHours" name={t("manager.performance.coachHours")} fill="#526e54" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><CoachTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId}/></section> : null}
      {tab === "coverage" ? <section className={campStyles.panel}><Header title={t("manager.performance.coverage")} text={t("manager.performance.coverageHelp")}/><div className={styles.grid2}><DataList title={t("manager.performance.noHeadGroups")} rows={data.coverage.groupsWithoutHead.map((item) => ({label:item.name,href:`/manager/groups/${item.id}`}))}/><DataList title={t("manager.performance.singleCoachGroups")} rows={data.coverage.singleCoachGroups.map((item) => ({label:item.name,href:`/manager/groups/${item.id}`}))}/><DataList title={t("manager.performance.futureWithoutCoach")} rows={data.coverage.futureWithoutCoach.map((item) => ({label:item.title,meta:formatDate(item.startsAt),href:"/manager/calendar"}))}/></div></section> : null}
      {tab === "evaluations" ? <section className={campStyles.panel}><Header title={t("manager.performance.evaluations")} text={t("manager.performance.coachEvaluationsHelp")}/><div className={styles.kpis}><Kpi label={t("manager.performance.expected")} value={String(data.evaluations.expected)} detail={t("manager.performance.attributablePairs")}/><Kpi label={t("manager.performance.completed")} value={String(data.evaluations.completed)} detail={t("manager.performance.recordedEvaluation")}/><Kpi label={t("manager.performance.overdue")} value={String(data.evaluations.overdue)} detail={t("manager.performance.overdueHelp")}/><Kpi label={t("manager.performance.completion")} value={metric(data.evaluations.completionRate," %")} detail={t("manager.performance.completedExpected")}/></div><CoachTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId}/></section> : null}
      {tab === "attention" ? <section className={campStyles.panel}><Header title={t("manager.performance.attention")} text={t("manager.performance.coachAttentionHelp")}/><div className={styles.attention}>{data.attention.length ? data.attention.map((item,index) => <Link href={item.href} key={`${item.type}-${item.label}-${index}`}><b>{item.label}</b><span>{t(`manager.performance.coachAttention.${item.type}`)}</span><span>{coachAttention(item)}</span></Link>) : <div className={styles.empty}>{t("manager.performance.noAttention")}</div>}</div></section> : null}
    </> : null}
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{detail}</small></article>; }
function Header({ title, text }: { title: string; text: string }) { return <div className={styles.sectionHeader}><div><h2>{title}</h2><p>{text}</p></div></div>; }
function DataList({ title, rows }: { title: string; rows: Array<{label:string;meta?:string;href:string}> }) { const { t } = useManagerPerformanceLabels(); return <div><h3 className={coachStyles.listTitle}>{title}</h3><div className={coachStyles.compactList}>{rows.length ? rows.map((row,index) => <Link href={row.href} key={`${row.label}-${index}`}><b>{row.label}</b>{row.meta ? <span>{row.meta}</span> : null}</Link>) : <div className={styles.empty}>{t("manager.performance.noItems")}</div>}</div></div>; }
function CoachTable({ rows, clubId, seasonId }: { rows: CoachRow[]; clubId: string; seasonId: string }) { const { t, metric, date: formatDate, count } = useManagerPerformanceLabels(); return <section className={campStyles.panel}><Header title={t("manager.performance.coachDetail")} text={count("coachCount", rows.length)}/><div className={campStyles.tableWrap}><table className={`${campStyles.table} ${tableStyles.memberTable}`}><thead><tr><th aria-label={t("manager.performance.avatar")}/><th>{t("manager.performance.coach")}</th><th>{t("manager.performance.groupsRole")}</th><th>{t("manager.performance.activities")}</th><th>{t("manager.performance.coachHours")}</th><th>{t("manager.performance.juniors")}</th><th>{t("manager.performance.typicalSize")}</th><th>{t("manager.performance.evaluations")}</th><th>{t("manager.performance.overdue")}</th><th>{t("manager.performance.lastActivity")}</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><ManagerMemberAvatar name={row.name} avatarUrl={row.avatarUrl}/></td><td data-label={t("manager.performance.coach")}><span className={tableStyles.cellValue}><Link className={styles.tableLink} href={`/manager/user-management/coaches/${row.memberId}?club=${clubId}&season=${seasonId}&tab=statistics`}>{row.name}</Link>{row.function ? <small> · {row.function}</small> : null}</span></td><td data-label={t("manager.performance.groupsRole")}><span className={tableStyles.cellValue}>{row.groupCount}<small> · {row.headGroupCount ? count("headGroups", row.headGroupCount) : t(row.groupCount ? "manager.performance.assistant" : "manager.performance.noGroup")}</small></span></td><td data-label={t("manager.performance.activities")}><span className={tableStyles.cellValue}>{row.activities}</span></td><td data-label={t("manager.performance.coachHours")}><span className={tableStyles.cellValue}>{metric(row.coachHours," h")}</span></td><td data-label={t("manager.performance.juniors")}><span className={tableStyles.cellValue}>{row.uniquePlayers}</span></td><td data-label={t("manager.performance.typicalSize")}><span className={tableStyles.cellValue}>{metric(row.medianGroupSize)}</span></td><td data-label={t("manager.performance.evaluations")}><span className={tableStyles.cellValue}>{row.evaluationsCompleted} / {row.evaluationsExpected}</span></td><td data-label={t("manager.performance.overdue")}><span className={tableStyles.cellValue}>{row.evaluationsOverdue}</span></td><td data-label={t("manager.performance.lastActivity")}><span className={tableStyles.cellValue}>{formatDate(row.lastActivity)}</span></td></tr>) : <tr><td colSpan={10}><div className={styles.empty}>{t("manager.performance.noCoaches")}</div></td></tr>}</tbody></table></div></section>; }
