"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- concise loading-state branch */

import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import styles from "@/components/manager/Performance.module.css";
import coachStyles from "@/components/manager/CoachPerformance.module.css";
import { performanceHeaders } from "@/components/manager/usePerformanceContext";

type Coach = { id: string; memberId: string; name: string; groups: Array<{ id: string; name: string; role: string; juniors: number }>; activities: number; coachHours: number; previousCoachHours: number; uniquePlayers: number; medianGroupSize: number | null; activeWeeks: number; camps: number; evaluationsExpected: number; evaluationsCompleted: number; evaluationsInProgress: number; evaluationsOverdue: number; visibleFeedbackRate: number | null; lastActivity: string | null; activityTypes: string[]; evaluationTodo: Array<{ eventId: string; playerId: string; groupId: string | null; eventTitle: string; reason: string }> };
type Data = { range: { from: string; to: string }; coach: Coach; distribution: { monthly: Array<{ month: string; activityHours: number; coachHours: number }> } };
const display = (value: number | null, suffix = "") => value == null ? "Données insuffisantes" : `${value.toLocaleString("fr-CH")}${suffix}`;

export default function ManagerCoachStatistics({ clubId, coachId, seasonId, seasonFrom, seasonTo }: { clubId: string; coachId: string; seasonId: string; seasonFrom?: string; seasonTo?: string }) {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  async function load(background = false) { if (!clubId || !coachId || !seasonId) return; background ? setRefreshing(true) : setLoading(true); setError(""); try { const today = new Date().toISOString().slice(0,10); const query = new URLSearchParams({ coachId, season: seasonId, status: "all", from: seasonFrom ?? "", to: seasonTo && seasonTo < today ? seasonTo : today }); const response = await fetch(`/api/manager/clubs/${clubId}/performance/coaches?${query}`, { headers: await performanceHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Chargement impossible."); setData(json); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { void load(); }, [clubId, coachId, seasonId, seasonFrom, seasonTo]); // eslint-disable-line react-hooks/exhaustive-deps
  if (loading && !data) return <section className={campStyles.panel}><ListLoadingBlock label="Chargement des statistiques du coach…"/></section>;
  if (error && !data) return <div className={styles.error} role="alert"><AlertTriangle size={15}/> {error}</div>;
  if (!data?.coach) return <section className={campStyles.panel}><div className={styles.empty}>Aucune donnée exploitable pour cette période.</div></section>;
  const coach = data.coach; const change = coach.previousCoachHours > 0 ? Math.round(((coach.coachHours - coach.previousCoachHours) / coach.previousCoachHours) * 1000) / 10 : null;
  return <div className={styles.page}>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>Statistiques</h2><p>Activités explicitement attribuées à ce coach pour la saison sélectionnée.</p></div><button type="button" className={styles.refresh} disabled={refreshing} onClick={() => void load(true)}><RefreshCw size={14}/>{refreshing ? "Actualisation…" : "Actualiser"}</button></div><div className={styles.kpis}><Kpi label="Groupes attribués" value={String(coach.groups.length)} detail="Responsable ou assistant"/><Kpi label="Activités encadrées" value={String(coach.activities)} detail="Affectations explicites"/><Kpi label="Heures d’encadrement" value={display(coach.coachHours," h")} detail={change == null ? "Comparaison indisponible" : `${change >= 0 ? "+" : ""}${change} % sur la période précédente`}/><Kpi label="Juniors accompagnés" value={String(coach.uniquePlayers)} detail="Juniors différents"/><Kpi label="Taille médiane" value={display(coach.medianGroupSize)} detail="Présents ou attendus par activité"/><Kpi label="Semaines actives" value={String(coach.activeWeeks)} detail="Au moins une activité attribuée"/><Kpi label="Camps" value={String(coach.camps)} detail="Participations enregistrées"/><Kpi label="Évaluations réalisées" value={`${coach.evaluationsCompleted} / ${coach.evaluationsExpected}`} detail={`${coach.evaluationsOverdue} en retard`}/></div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>Activité et charge</h2><p>La charge affichée ne constitue pas une note de performance.</p></div></div><div className={styles.chart} role="img" aria-label="Évolution de la charge mensuelle"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.distribution.monthly}><CartesianGrid stroke="#e7ece6" vertical={false}/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis unit=" h" tick={{fontSize:10}}/><Tooltip/><Bar dataKey="coachHours" name="Heures-coachs" fill="#526e54" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>Groupes et juniors accompagnés</h2><p>L’assiduité des juniors est un contexte, pas une mesure de la performance du coach.</p></div></div><div className={campStyles.tableWrap}><table className={`${campStyles.table} ${coachStyles.groupTable}`}><thead><tr><th>Groupe</th><th>Rôle</th><th>Juniors</th></tr></thead><tbody>{coach.groups.length ? coach.groups.map((group) => <tr key={group.id}><td data-label="Groupe"><Link className={styles.tableLink} href={`/manager/groups/${group.id}`}>{group.name}</Link></td><td data-label="Rôle">{group.role}</td><td data-label="Juniors">{group.juniors}</td></tr>) : <tr><td colSpan={3}><div className={styles.empty}>Aucun groupe attribué pour cette saison.</div></td></tr>}</tbody></table></div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>Évaluations à terminer</h2><p>Une évaluation est considérée en retard sept jours après l’activité.</p></div></div><div className={styles.attention}>{coach.evaluationTodo.length ? coach.evaluationTodo.map((item) => <Link href={item.groupId ? `/manager/groups/${item.groupId}/planning/${item.eventId}` : "/manager/calendar"} key={`${item.eventId}-${item.playerId}`}><b>{item.eventTitle}</b><span>{item.reason}</span><span>Voir l’activité</span></Link>) : <div className={styles.empty}>Aucune évaluation attribuable en retard.</div>}</div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>Qualité des données</h2><p>Éléments factuels, présentés sans jugement.</p></div></div><div className={styles.smallGrid}><Small label="Évaluations en cours" value={coach.evaluationsInProgress}/><Small label="Évaluations en retard" value={coach.evaluationsOverdue}/><Small label="Retours visibles" value={coach.visibleFeedbackRate == null ? "Données insuffisantes" : `${coach.visibleFeedbackRate} %`}/><Small label="Dernière activité" value={coach.lastActivity ? new Intl.DateTimeFormat("fr-CH").format(new Date(coach.lastActivity)) : "Aucune"}/></div></section>
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{detail}</small></article>; }
function Small({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><b>{value}</b></div>; }
