"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Eye, History, MailCheck, Pause, RefreshCw, Save, Send, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import actionStyles from "@/components/admin/organizations/OrganizationSettingsAdmin.module.css";
import styles from "@/components/manager/ManagerPlayerStatistics.module.css";
import reportStyles from "@/components/manager/ManagerPeriodicReport.module.css";
import { PeriodicReportView, type PublishedReport } from "@/components/parent/PeriodicReportView";

type Config = { is_enabled: boolean; frequency: string; send_day: number; timezone: string; locale: string; recipient_user_ids: string[]; sections: Record<string, boolean>; coach_priority: string; coach_objective: string; coach_encouragement: string; coach_comment: string; next_send_at: string | null; last_sent_at: string | null; last_status: string | null };
type Recipient = { userId: string; name: string; email: string; relation: string | null; isPrimary: boolean };
type ReportHistory = { id: string; period_from: string; period_to: string; delivery_mode: string; status: string; error_message: string | null; attempt_count: number; sent_at: string | null; created_at: string };
type ReportPreview = PublishedReport["published_content"] & { clubName: string; periodLabel: string };
const sectionLabels: Record<string, string> = { attendance: "Assiduité", training: "Entraînements", competitions: "Compétitions", handicap: "Handicap et niveau FTEM", evaluations: "Évaluations", coach_comment: "Commentaire du coach", upcoming: "Prochaines activités" };
async function authHeaders() { const session = await supabase.auth.getSession(); return session.data.session?.access_token ? { Authorization: `Bearer ${session.data.session.access_token}` } : {}; }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("fr-CH", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Jamais"; }

export default function ManagerPeriodicReport({ clubId, playerId, familyUrl }: { clubId: string; playerId: string; familyUrl: string }) {
  const [config, setConfig] = useState<Config | null>(null); const [recipients, setRecipients] = useState<Recipient[]>([]); const [history, setHistory] = useState<ReportHistory[]>([]); const [preview, setPreview] = useState<ReportPreview | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); setError(""); try { const response = await fetch(`/api/manager/clubs/${clubId}/players/${playerId}/periodic-report`, { headers: await authHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Chargement impossible."); setConfig(json.config); setRecipients(json.recipients ?? []); setHistory(json.history ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [clubId, playerId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save(next = config) { if (!next) return; setBusy("save"); setError(""); setMessage(""); try { const response = await fetch(`/api/manager/clubs/${clubId}/players/${playerId}/periodic-report`, { method: "PUT", headers: { "Content-Type": "application/json", ...(await authHeaders()) }, body: JSON.stringify(next) }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Enregistrement impossible."); setConfig(json.config); setMessage("Configuration enregistrée."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Enregistrement impossible."); } finally { setBusy(""); } }
  async function action(kind: "preview" | "test" | "send") { if (kind === "send" && !window.confirm(`Envoyer maintenant le rapport à ${config?.recipient_user_ids.length ?? 0} parent(s) sélectionné(s) ?`)) return; setBusy(kind); setError(""); setMessage(""); try { const response = await fetch(`/api/manager/clubs/${clubId}/players/${playerId}/periodic-report`, { method: "POST", headers: { "Content-Type": "application/json", ...(await authHeaders()) }, body: JSON.stringify({ action: kind }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? json.errors?.map((item: { email: string; error: string }) => `${item.email} : ${item.error}`).join(" · ") ?? "Action impossible."); if (kind === "preview") setPreview(json.preview); else { const failures = json.errors?.length ? ` ${json.errors.length} envoi(s) en erreur.` : ""; setMessage(kind === "test" ? `Rapport de test préparé pour ${json.sent.join(", ")}.${failures}` : `Rapport envoyé à ${json.sent.join(", ")}.${failures}`); await load(); } } catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(""); } }
  if (loading) return <section className={campStyles.panel}><ListLoadingBlock label="Chargement du rapport périodique…" /></section>;
  if (!config) return <div className={actionStyles.errorAlert}>{error || "Configuration indisponible."}</div>;
  const noRecipients = recipients.length === 0;
  return <div className={styles.stack}>
    {error ? <div className={actionStyles.errorAlert} role="alert">{error}</div> : null}{message ? <div className={actionStyles.successAlert} role="status">{message}</div> : null}
    <section className={campStyles.panel}><div className={campStyles.panelHeader}><div><h2>Rapport périodique</h2><p>Préparez un résumé parental court, factuel et consultable dans l’espace sécurisé.</p></div><label className={reportStyles.automaticToggle}><input type="checkbox" checked={config.is_enabled} disabled={noRecipients} onChange={(event) => setConfig({ ...config, is_enabled: event.target.checked })} /><span>Envoi automatique</span></label></div>
      {noRecipients ? <div className={styles.info}>Aucun parent ne possède d’adresse e-mail exploitable. <Link href={familyUrl}>Compléter les accès famille</Link>.</div> : null}
      <div className="user-mgmt-form-grid">
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">Fréquence</span><select value={config.frequency} onChange={(event) => setConfig({ ...config, frequency: event.target.value })}><option value="monthly">Mensuelle</option><option value="quarterly">Trimestrielle</option><option value="semiannual">Semestrielle</option></select></label>
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">Jour d’envoi</span><input type="number" min={1} max={28} value={config.send_day} onChange={(event) => setConfig({ ...config, send_day: Number(event.target.value) })} /></label>
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">Langue</span><select value={config.locale} onChange={(event) => setConfig({ ...config, locale: event.target.value })}><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="en">English</option></select></label>
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">Fuseau horaire</span><input value={config.timezone} readOnly /></label>
      </div>
      <h3>Parents destinataires</h3><div className="user-mgmt-chip-list">{recipients.map((recipient) => <label className="pill-soft" key={recipient.userId}><input type="checkbox" checked={config.recipient_user_ids.includes(recipient.userId)} onChange={(event) => setConfig({ ...config, recipient_user_ids: event.target.checked ? [...config.recipient_user_ids, recipient.userId] : config.recipient_user_ids.filter((id) => id !== recipient.userId) })} />{recipient.name} · {recipient.email}{recipient.isPrimary ? " · principal" : ""}</label>)}</div>
      <h3>Contenu inclus</h3><div className="user-mgmt-chip-list">{Object.entries(sectionLabels).map(([key, label]) => <label className="pill-soft" key={key}><input type="checkbox" checked={config.sections[key] !== false} onChange={(event) => setConfig({ ...config, sections: { ...config.sections, [key]: event.target.checked } })} />{label}</label>)}</div>
      <h3>Prochaine période</h3><div className="user-mgmt-form-grid"><label className="user-mgmt-field"><span className="user-mgmt-field-label">Priorité</span><input value={config.coach_priority ?? ""} onChange={(event) => setConfig({ ...config, coach_priority: event.target.value })} /></label><label className="user-mgmt-field"><span className="user-mgmt-field-label">Objectif</span><input value={config.coach_objective ?? ""} onChange={(event) => setConfig({ ...config, coach_objective: event.target.value })} /></label><label className="user-mgmt-field"><span className="user-mgmt-field-label">Encouragement</span><input value={config.coach_encouragement ?? ""} onChange={(event) => setConfig({ ...config, coach_encouragement: event.target.value })} /></label><label className="user-mgmt-field" style={{ gridColumn: "1 / -1" }}><span className="user-mgmt-field-label">Commentaire personnalisé visible par les parents</span><textarea rows={4} value={config.coach_comment ?? ""} onChange={(event) => setConfig({ ...config, coach_comment: event.target.value })} /></label></div>
      <div className={actionStyles.topActions} style={{ justifyContent: "flex-end", marginTop: 18 }}><button type="button" className={actionStyles.secondaryButton} disabled={Boolean(busy)} onClick={() => void action("preview")}><Eye size={15} />Prévisualiser</button><button type="button" className={actionStyles.secondaryButton} disabled={Boolean(busy)} onClick={() => void action("test")}><MailCheck size={15} />Envoyer un test au manager</button><button type="button" className={actionStyles.secondaryButton} disabled={Boolean(busy) || !config.is_enabled} onClick={() => { const next = { ...config, is_enabled: false }; setConfig(next); void save(next); }}><Pause size={15} />Suspendre</button><button type="button" className={actionStyles.primaryButton} disabled={Boolean(busy) || !config.recipient_user_ids.length} onClick={() => void action("send")}><Send size={15} />Envoyer maintenant</button><button type="button" className={actionStyles.primaryButton} disabled={Boolean(busy)} onClick={() => void save()}>{busy === "save" ? <RefreshCw size={15} /> : <Save size={15} />}Enregistrer la configuration</button></div>
      <div className={styles.period}>Prochain envoi : {formatDate(config.next_send_at)} · Dernier envoi : {formatDate(config.last_sent_at)} · Statut : {config.last_status ?? "aucun"}</div>
    </section>
    {preview ? <section className={campStyles.panel} aria-label="Aperçu du prochain rapport"><div className={campStyles.panelHeader}><div><h2>Aperçu du prochain rapport</h2><p>{preview.periodLabel}</p></div><button type="button" className={campStyles.iconButton} aria-label="Fermer l’aperçu" title="Fermer" onClick={() => setPreview(null)}><X size={15} /></button></div><PeriodicReportView compactHeading report={{ id: "preview", club_name: preview.clubName, period_label: preview.periodLabel, personalized_comment: preview.sections?.coachComment ?? null, published_content: preview }} /></section> : null}
    <section className={campStyles.panel}><div className={campStyles.panelHeader}><div><h2>Historique</h2><p>Livraisons parentales réussies, ignorées ou en erreur.</p></div><History size={18} /></div>{history.length ? <div className={campStyles.tableWrap}><table className={campStyles.table}><thead><tr><th>Période</th><th>Mode</th><th>Statut</th><th>Tentatives</th><th>Date</th></tr></thead><tbody>{history.map((row) => <tr key={row.id}><td>{row.period_from} – {row.period_to}</td><td>{row.delivery_mode === "automatic" ? "Automatique" : "Manuel"}</td><td><span className={campStyles.badge}>{row.status}</span>{row.error_message ? <small>{row.error_message}</small> : null}</td><td>{row.attempt_count}</td><td>{formatDate(row.sent_at ?? row.created_at)}</td></tr>)}</tbody></table></div> : <div className={campStyles.empty}>Aucun rapport n’a encore été envoyé.</div>}</section>
  </div>;
}
