"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, RefreshCw, Save } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import styles from "@/components/admin/AdminHomeStats.module.css";
import actionStyles from "@/components/admin/organizations/OrganizationSettingsAdmin.module.css";

type Manager = { id: string; role: string; auth_email?: string | null; is_active: boolean | null; profiles: { first_name: string | null; last_name: string | null; username: string | null; staff_function: string | null; phone: string | null; address: string | null; postal_code: string | null; city: string | null } | null };

async function authHeaders() { const { data } = await supabase.auth.getSession(); return data.session?.access_token ? { Authorization: `Bearer ${data.session.access_token}` } : {}; }

export default function ManagerEditPage({ memberId }: { memberId: string }) {
  const query = useSearchParams(); const clubId = query.get("club") ?? ""; const backUrl = `/manager/user-management/managers${clubId ? `?club=${clubId}` : ""}`;
  const [manager, setManager] = useState<Manager | null>(null); const [form, setForm] = useState({ first_name: "", last_name: "", username: "", email: "", password: "", staff_function: "", phone: "", address: "", postal_code: "", city: "", is_active: true }); const [errors, setErrors] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load() { if (!clubId) { setError("Club manquant."); setLoading(false); return; } setLoading(true); try { const response = await fetch(`/api/manager/clubs/${clubId}/members`, { headers: await authHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Impossible de charger le manager."); const next = (json.members ?? []).find((item: Manager) => item.id === memberId && item.role === "manager") as Manager | undefined; if (!next) throw new Error("Manager introuvable."); const profile = next.profiles; setManager(next); setForm({ first_name: profile?.first_name ?? "", last_name: profile?.last_name ?? "", username: profile?.username ?? "", email: next.auth_email?.endsWith("@noemail.local") ? "" : next.auth_email ?? "", password: "", staff_function: profile?.staff_function ?? "", phone: profile?.phone ?? "", address: profile?.address ?? "", postal_code: profile?.postal_code ?? "", city: profile?.city ?? "", is_active: next.is_active !== false }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger le manager."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  function validate() { const next: Record<string, string> = {}; if (!form.first_name.trim()) next.first_name = "Le prénom est obligatoire."; if (!form.last_name.trim()) next.last_name = "Le nom est obligatoire."; if (!form.username.trim()) next.username = "Le nom d’utilisateur est obligatoire."; if (!form.staff_function.trim()) next.staff_function = "La fonction est obligatoire."; if (!/^\S+@\S+\.\S+$/.test(form.email.trim())) next.email = "Saisissez une adresse e-mail valide."; if (form.password && form.password.length < 8) next.password = "Le mot de passe doit contenir au moins 8 caractères."; setErrors(next); return Object.keys(next).length === 0; }
  async function save(event: React.FormEvent) { event.preventDefault(); if (!manager || !validate()) return; setSaving(true); setError(""); setMessage(""); try { const response = await fetch(`/api/manager/clubs/${clubId}/members`, { method: "PATCH", headers: { "Content-Type": "application/json", ...(await authHeaders()) }, body: JSON.stringify({ memberId: manager.id, role: "manager", first_name: form.first_name.trim(), last_name: form.last_name.trim(), username: form.username.trim().toLowerCase(), auth_email: form.email.trim().toLowerCase(), auth_password: form.password, staff_function: form.staff_function.trim(), phone: form.phone.trim(), address: form.address.trim(), postal_code: form.postal_code.trim(), city: form.city.trim(), is_active: form.is_active }) }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Impossible d’enregistrer le manager."); setForm((current) => ({ ...current, password: "" })); setMessage("Les informations du manager ont été enregistrées."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible d’enregistrer le manager."); } finally { setSaving(false); } }
  const name = [manager?.profiles?.first_name, manager?.profiles?.last_name].filter(Boolean).join(" ") || "Manager";
  if (loading) return <div className={styles.page}><section className={styles.overview}><ListLoadingBlock label="Chargement de la fiche manager…" /></section></div>;
  return <div className={styles.page}><nav aria-label="Fil d’Ariane" style={{ minHeight: 22, color: "#35483b", fontSize: 11, fontWeight: 700 }}><Link href={backUrl}>Managers</Link> / Fiche manager</nav><div className={styles.topline}><div><h1>{name}</h1><p className={styles.lead}>Coordonnées et accès du manager.</p></div><div className={actionStyles.topActions}><Link className={actionStyles.backButton} href={backUrl}><ArrowLeft size={16} />Retour à la liste</Link></div></div>{error ? <div className={actionStyles.errorAlert} role="alert">{error}</div> : null}{message ? <div className={actionStyles.successAlert} role="status">{message}</div> : null}<form onSubmit={save} noValidate><section className={styles.overview}><div className={styles.sectionHeading}><div><h2>Profil du manager</h2><p>Les champs marqués d’un astérisque sont requis.</p></div></div><div className="user-mgmt-form-grid"><Field label="Prénom" required value={form.first_name} error={errors.first_name} onChange={(value) => setForm({ ...form, first_name: value })} /><Field label="Nom" required value={form.last_name} error={errors.last_name} onChange={(value) => setForm({ ...form, last_name: value })} /><Field label="Nom d’utilisateur" required value={form.username} error={errors.username} onChange={(value) => setForm({ ...form, username: value })} /><Field label="Fonction" required value={form.staff_function} error={errors.staff_function} onChange={(value) => setForm({ ...form, staff_function: value })} /><Field label="Adresse e-mail" required type="email" value={form.email} error={errors.email} onChange={(value) => setForm({ ...form, email: value })} /><Field label="Nouveau mot de passe" type="password" value={form.password} error={errors.password} onChange={(value) => setForm({ ...form, password: value })} /><Field label="Téléphone" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><Field label="Adresse" full value={form.address} onChange={(value) => setForm({ ...form, address: value })} /><Field label="Code postal" value={form.postal_code} onChange={(value) => setForm({ ...form, postal_code: value })} /><Field label="Ville" value={form.city} onChange={(value) => setForm({ ...form, city: value })} /><label className="user-mgmt-field"><span className="user-mgmt-field-label">Compte actif</span><select value={form.is_active ? "yes" : "no"} onChange={(event) => setForm({ ...form, is_active: event.target.value === "yes" })}><option value="yes">Oui</option><option value="no">Non</option></select></label></div><div className={actionStyles.topActions} style={{ justifyContent: "flex-end", marginTop: "auto" }}><button type="submit" className={actionStyles.primaryButton} disabled={saving}>{saving ? <RefreshCw size={16} className={styles.spin} /> : <Save size={16} />}{saving ? "Enregistrement…" : "Enregistrer le manager"}</button></div></section></form></div>;
}

function Field({ label, value, onChange, error, type = "text", required, full }: { label: string; value: string; onChange: (value: string) => void; error?: string; type?: string; required?: boolean; full?: boolean }) { return <label className="user-mgmt-field" style={full ? { gridColumn: "1 / -1" } : undefined}><span className="user-mgmt-field-label">{label}{required ? " *" : ""}</span><input required={required} aria-required={required || undefined} aria-invalid={Boolean(error)} type={type} value={value} onChange={(event) => onChange(event.target.value)} />{error ? <small className="form-error" role="alert">{error}</small> : null}</label>; }
