"use client";

import { useI18n } from "@/components/i18n/AppI18nProvider";
import { managerJuniorFeedback, managerJuniorFormat, managerJuniorDate, managerReportStatus } from "@/lib/managerJuniorPresentation";

import Link from "next/link";
import { managerCount, managerLocaleTag } from "@/lib/managerLocale";
import { useEffect, useRef, useState } from "react";
import { Eye, History, MailCheck, Pause, RefreshCw, Save, Send, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import actionStyles from "@/components/admin/organizations/OrganizationSettingsAdmin.module.css";
import styles from "@/components/manager/ManagerPlayerStatistics.module.css";
import reportStyles from "@/components/manager/ManagerPeriodicReport.module.css";
import { PeriodicReportView, type PublishedReport } from "@/components/parent/PeriodicReportView";

type Config = { is_enabled: boolean; frequency: string; send_day: number; timezone: string; locale: string; recipient_user_ids: string[]; sections: Record<string, boolean>; coach_priority: string; coach_objective: string; coach_encouragement: string; coach_comment: string; next_send_at: string | null; last_sent_at: string | null; last_status: string | null };
type Recipient = { userId: string; name: string; email: string; relation: string | null; isPrimary: boolean };
type ReportHistory = { id: string; period_from: string; period_to: string; delivery_mode: string; status: string; error_message: string | null; attempt_count: number; sent_at: string | null; created_at: string };
type ReportPreview = PublishedReport["published_content"] & { clubName: string; periodLabel: string };

async function authHeaders() { const session = await supabase.auth.getSession(); return session.data.session?.access_token ? { Authorization: `Bearer ${session.data.session.access_token}` } : {}; }


export default function ManagerPeriodicReport({ clubId, playerId, familyUrl }: { clubId: string; playerId: string; familyUrl: string }) {
  const { t, locale } = useI18n();
  const sectionLabels: Record<string, string> = { attendance: t("manager.performance.attendance"), training: t("manager.junior.report.training"), competitions: t("manager.performance.competitions"), handicap: t("manager.junior.report.handicap"), evaluations: t("manager.performance.evaluations"), coach_comment: t("manager.junior.report.coachComment"), upcoming: t("coach.home.upcoming") };
  const formatDate = (value: string | null, withTime = true) => managerJuniorDate(t, locale, value, withTime);
  const [config, setConfig] = useState<Config | null>(null); const [recipients, setRecipients] = useState<Recipient[]>([]); const [history, setHistory] = useState<ReportHistory[]>([]); const [preview, setPreview] = useState<ReportPreview | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [savedConfig, setSavedConfig] = useState<Config | null>(null);
  const [delivery, setDelivery] = useState<{ kind: "test" | "send"; sent: string[]; errors: Array<{ email: string; error: string }> } | null>(null);
  const working = useRef(false);
  const dirty = JSON.stringify(config) !== JSON.stringify(savedConfig);
  async function load() { setLoading(true); setError(""); try { const response = await fetch(`/api/manager/clubs/${clubId}/players/${playerId}/periodic-report`, { headers: await authHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? t("manager.loadError")); setConfig(json.config); setSavedConfig(json.config); setRecipients(json.recipients ?? []); setHistory(json.history ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : t("manager.loadError")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [clubId, playerId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function save(next = config) { if (!next || working.current) return; working.current = true; setBusy("save"); setDelivery(null); setError(""); setMessage(""); try { const response = await fetch(`/api/manager/clubs/${clubId}/players/${playerId}/periodic-report`, { method: "PUT", headers: { "Content-Type": "application/json", ...(await authHeaders()) }, body: JSON.stringify(next) }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? t("manager.saveError")); setConfig(json.config); setSavedConfig(json.config); setPreview(null); setMessage(t("manager.junior.report.saved")); } catch (cause) { setError(cause instanceof Error ? cause.message : t("manager.saveError")); } finally { working.current = false; setBusy(""); } }
  async function action(kind: "preview" | "test" | "send") {
    if (working.current || dirty || !config) return;
    if (kind === "send" && (!config.recipient_user_ids.length || !window.confirm(managerCount(t, locale, "manager.junior.report.confirm", config.recipient_user_ids.length)))) return;
    working.current = true;
    setBusy(kind); setError(""); setMessage(""); setDelivery(null);
    try {
      const response = await fetch(`/api/manager/clubs/${clubId}/players/${playerId}/periodic-report`, { method: "POST", headers: { "Content-Type": "application/json", ...(await authHeaders()) }, body: JSON.stringify({ action: kind }) });
      const json = await response.json();
      if (!response.ok) throw new Error(json.error ?? json.errors?.map((item: { email: string; error: string }) => `${item.email} : ${managerJuniorFeedback(t, item.error)}`).join(" · ") ?? t("manager.administration.actionError"));
      if (kind === "preview") setPreview(json.preview);
      else { setDelivery({ kind, sent: json.sent ?? [], errors: json.errors ?? [] }); await load(); }
    } catch (cause) { setError(cause instanceof Error ? cause.message : t("manager.administration.actionError")); }
    finally { working.current = false; setBusy(""); }
  }
  if (loading) return <section className={campStyles.panel}><ListLoadingBlock label={t("manager.junior.report.loading")} /></section>;
  if (!config) return <div className={actionStyles.errorAlert}>{managerJuniorFeedback(t, error) || t("manager.junior.report.unavailable")}</div>;
  const noRecipients = recipients.length === 0;
  return <div className={styles.stack}>
    {error ? <div className={actionStyles.errorAlert} role="alert">{managerJuniorFeedback(t, error)}</div> : null}{message ? <div className={actionStyles.successAlert} role="status">{managerJuniorFeedback(t, message)}</div> : null}
    {delivery ? <div className={delivery.errors.length ? actionStyles.errorAlert : actionStyles.successAlert} role="status">{delivery.sent.length ? <p>{managerJuniorFormat(t, delivery.kind === "test" ? "report.testSent" : "report.sent", { recipients: delivery.sent.join(", ") })}</p> : null}{delivery.errors.length ? <><p>{managerCount(t, locale, "manager.junior.report.failed", delivery.errors.length)}</p>{delivery.errors.map((item, index) => <div key={index}>{item.email} : {managerJuniorFeedback(t, item.error)}</div>)}</> : null}</div> : null}
    <section className={campStyles.panel}><fieldset disabled={Boolean(busy)} className={reportStyles.fields}><div className={campStyles.panelHeader}><div><h2>{t("manager.junior.emails.periodic_report.title")}</h2><p>{t("manager.junior.report.lead")}</p></div><label className={reportStyles.automaticToggle}><input type="checkbox" checked={config.is_enabled} disabled={noRecipients} onChange={(event) => setConfig({ ...config, is_enabled: event.target.checked })} /><span>{t("manager.junior.report.automatic")}</span></label></div>
      {noRecipients ? <div className={styles.info}>{t("manager.junior.report.noRecipients")} <Link href={familyUrl}>{t("manager.junior.report.completeFamily")}</Link>.</div> : null}
      <div className="user-mgmt-form-grid">
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("manager.junior.report.frequency")}</span><select value={config.frequency} onChange={(event) => setConfig({ ...config, frequency: event.target.value })}><option value="monthly">{t("manager.junior.report.monthly")}</option><option value="quarterly">{t("manager.junior.report.quarterly")}</option><option value="semiannual">{t("manager.junior.report.semiannual")}</option></select></label>
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("manager.junior.report.sendDay")}</span><input type="number" min={1} max={28} value={config.send_day} onChange={(event) => setConfig({ ...config, send_day: Number(event.target.value) })} /></label>
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("common.language")}</span><select value={config.locale} onChange={(event) => setConfig({ ...config, locale: event.target.value })}><option value="fr">Français</option><option value="de">Deutsch</option><option value="it">Italiano</option><option value="en">English</option></select></label>
        <label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("manager.junior.report.timezone")}</span><input value={config.timezone} readOnly /></label>
      </div>
      <h3>{t("manager.junior.report.recipients")}</h3><div className="user-mgmt-chip-list">{recipients.map((recipient) => <label className="pill-soft" key={recipient.userId}><input type="checkbox" checked={config.recipient_user_ids.includes(recipient.userId)} onChange={(event) => setConfig({ ...config, recipient_user_ids: event.target.checked ? [...config.recipient_user_ids, recipient.userId] : config.recipient_user_ids.filter((id) => id !== recipient.userId) })} />{recipient.name} · {recipient.email}{recipient.isPrimary ? t("manager.junior.report.primarySuffix") : ""}</label>)}</div>
      <h3>{t("manager.junior.report.sections")}</h3><div className="user-mgmt-chip-list">{Object.entries(sectionLabels).map(([key, label]) => <label className="pill-soft" key={key}><input type="checkbox" checked={config.sections[key] !== false} onChange={(event) => setConfig({ ...config, sections: { ...config.sections, [key]: event.target.checked } })} />{label}</label>)}</div>
      <h3>{t("manager.junior.report.nextPeriod")}</h3><div className="user-mgmt-form-grid"><label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("manager.junior.report.priority")}</span><input value={config.coach_priority ?? ""} onChange={(event) => setConfig({ ...config, coach_priority: event.target.value })} /></label><label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("manager.performance.objective")}</span><input value={config.coach_objective ?? ""} onChange={(event) => setConfig({ ...config, coach_objective: event.target.value })} /></label><label className="user-mgmt-field"><span className="user-mgmt-field-label">{t("manager.junior.report.encouragement")}</span><input value={config.coach_encouragement ?? ""} onChange={(event) => setConfig({ ...config, coach_encouragement: event.target.value })} /></label><label className="user-mgmt-field" style={{ gridColumn: "1 / -1" }}><span className="user-mgmt-field-label">{t("manager.junior.report.parentComment")}</span><textarea rows={4} value={config.coach_comment ?? ""} onChange={(event) => setConfig({ ...config, coach_comment: event.target.value })} /></label></div>
      {dirty ? <p className={styles.info} role="status">{t("manager.junior.report.saveFirst")}</p> : null}<div className={actionStyles.topActions} style={{ justifyContent: "flex-end", marginTop: 18 }}><button type="button" className={actionStyles.secondaryButton} disabled={Boolean(busy) || dirty} onClick={() => void action("preview")}><Eye size={15} />{t("manager.junior.report.preview")}</button><button type="button" className={actionStyles.secondaryButton} disabled={Boolean(busy) || dirty} onClick={() => void action("test")}><MailCheck size={15} />{t("manager.junior.report.test")}</button><button type="button" className={actionStyles.secondaryButton} disabled={Boolean(busy) || !config.is_enabled} onClick={() => { const next = { ...config, is_enabled: false }; setConfig(next); void save(next); }}><Pause size={15} />{t("manager.junior.report.pause")}</button><button type="button" className={actionStyles.primaryButton} disabled={Boolean(busy) || dirty || !config.recipient_user_ids.length} onClick={() => void action("send")}><Send size={15} />{t("manager.junior.report.send")}</button><button type="button" className={actionStyles.primaryButton} disabled={Boolean(busy)} onClick={() => void save()}>{busy === "save" ? <RefreshCw size={15} /> : <Save size={15} />}{t("manager.junior.report.save")}</button></div>
      <div className={styles.period}>{managerJuniorFormat(t, "report.schedule", { next: formatDate(config.next_send_at), last: formatDate(config.last_sent_at), status: managerReportStatus(t, config.last_status) })}</div></fieldset>
    </section>
    {preview && !dirty ? <section className={campStyles.panel} aria-label={t("manager.junior.report.previewTitle")}><div className={campStyles.panelHeader}><div><h2>{t("manager.junior.report.previewTitle")}</h2><p>{preview.periodLabel}</p></div><button type="button" className={campStyles.iconButton} aria-label={t("manager.junior.report.closePreview")} title={t("manager.settings.close")} onClick={() => setPreview(null)}><X size={15} /></button></div><PeriodicReportView compactHeading locale={config.locale} report={{ id: "preview", club_name: preview.clubName, period_label: preview.periodLabel, personalized_comment: preview.sections?.coachComment ?? null, published_content: preview }} /></section> : null}
    <section className={campStyles.panel}><div className={campStyles.panelHeader}><div><h2>{t("manager.junior.report.history")}</h2><p>{t("manager.junior.report.historyHelp")}</p></div><History size={18} /></div>{history.length ? <div className={campStyles.tableWrap}><table className={`${campStyles.table} ${reportStyles.historyTable}`}><thead><tr><th>{t("manager.performance.period")}</th><th>{t("manager.junior.report.mode")}</th><th>{t("manager.performance.status")}</th><th>{t("manager.junior.report.attempts")}</th><th>{t("manager.fields.date")}</th></tr></thead><tbody>{history.map((row) => <tr key={row.id}><td data-label={t("manager.performance.period")}>{formatDate(row.period_from, false)} – {formatDate(row.period_to, false)}</td><td data-label={t("manager.junior.report.mode")}>{row.delivery_mode === "automatic" ? t("manager.junior.report.modeAutomatic") : t("manager.junior.report.modeManual")}</td><td data-label={t("manager.performance.status")}><span className={campStyles.badge}>{managerReportStatus(t, row.status)}</span>{row.error_message ? <small>{managerJuniorFeedback(t, row.error_message)}</small> : null}</td><td data-label={t("manager.junior.report.attempts")}>{row.attempt_count.toLocaleString(managerLocaleTag(locale))}</td><td data-label={t("manager.fields.date")}>{formatDate(row.sent_at ?? row.created_at)}</td></tr>)}</tbody></table></div> : <div className={campStyles.empty}>{t("manager.junior.report.empty")}</div>}</section>
  </div>;
}
