"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- concise loading-state branch */

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import styles from "@/components/manager/Performance.module.css";
import coachStyles from "@/components/manager/CoachPerformance.module.css";
import tableStyles from "@/components/manager/PerformanceTables.module.css";
import PerformanceAppliedPeriod from "@/components/manager/PerformanceAppliedPeriod";
import ManagerStatisticsTabs from "@/components/manager/ManagerStatisticsTabs";
import ManagerMemberAvatar from "@/components/manager/ManagerMemberAvatar";
import { performanceHeaders, usePerformanceContext } from "@/components/manager/usePerformanceContext";

type Tab = "overview" | "load" | "coverage" | "evaluations" | "attention";
const tabs: ReadonlyArray<{ value: Tab; label: string }> = [
  { value: "overview", label: "Vue d’ensemble" },
  { value: "load", label: "Charge" },
  { value: "coverage", label: "Couverture" },
  { value: "evaluations", label: "Évaluations" },
  { value: "attention", label: "Centre d’attention" },
];
type CoachRow = { id: string; memberId: string; name: string; avatarUrl: string | null; function: string | null; active: boolean; groups: Array<{ id: string; name: string; role: string; juniors: number }>; groupCount: number; role: string; activities: number; coachHours: number; previousCoachHours: number; uniquePlayers: number; medianGroupSize: number | null; activeWeeks: number; camps: number; evaluationsExpected: number; evaluationsCompleted: number; evaluationsInProgress: number; evaluationsOverdue: number; visibleFeedbackRate: number | null; lastActivity: string | null };
type Data = { range: { from: string; to: string }; filters: { groups: Array<{ id: string; name: string }> }; overview: { activeCoaches: number; activities: number; activityHours: number; coachHours: number; medianPlayers: number | null; coverageRate: number | null; evaluationCompletionRate: number | null; pendingAttendance: number }; distribution: { medianCoachHours: number | null; monthly: Array<{ month: string; activities: number; activityHours: number; coachHours: number }> }; coverage: { groupsWithoutHead: Array<{ id: string; name: string }>; singleCoachGroups: Array<{ id: string; name: string }>; futureWithoutCoach: Array<{ id: string; title: string; startsAt: string }> }; evaluations: { expected: number; completed: number; overdue: number; completionRate: number | null }; rows: CoachRow[]; attention: Array<{ type: string; reason: string; label: string; value: string; href: string }> };
const presets = { season: 0, "30d": 30, "3m": 3, "6m": 6, "12m": 12 } as const;
const metric = (number: number | null, suffix = "") => number == null ? "Données insuffisantes" : `${number.toLocaleString("fr-CH")}${suffix}`;
const formatDate = (input: string | null) => input ? new Intl.DateTimeFormat("fr-CH", { dateStyle: "short" }).format(new Date(input)) : "Aucune activité";

export default function ManagerCoachPerformancePage() {
  const context = usePerformanceContext(); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [tab, setTab] = useState<Tab>("overview");
  const [preset, setPreset] = useState<keyof typeof presets | "custom">("season"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [group, setGroup] = useState("all"); const [role, setRole] = useState("all"); const [status, setStatus] = useState("active");
  const season = context.seasons.find((item) => item.id === context.seasonId);
  const range = useMemo(() => { const today = new Date(); const todayKey = today.toISOString().slice(0, 10); if (preset === "season") return { from: season?.starts_on ?? "", to: season?.ends_on && season.ends_on < todayKey ? season.ends_on : todayKey }; if (preset === "custom") return { from, to }; const start = new Date(today); if (preset === "30d") start.setUTCDate(start.getUTCDate() - 29); else start.setUTCMonth(start.getUTCMonth() - presets[preset]); return { from: start.toISOString().slice(0, 10), to: todayKey }; }, [from, preset, season, to]);
  async function load(background = false) { if (!context.clubId || !context.seasonId || !range.from || !range.to || range.from > range.to) return; background ? setRefreshing(true) : setLoading(true); setError(""); try { const query = new URLSearchParams({ season: context.seasonId, from: range.from, to: range.to, group, role, status }); const response = await fetch(`/api/manager/clubs/${context.clubId}/performance/coaches?${query}`, { headers: await performanceHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Chargement impossible."); setData(json); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { void load(Boolean(data)); }, [context.clubId, context.seasonId, range.from, range.to, group, role, status]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className={`${styles.page} ${tableStyles.scope}`}>
    <nav className={styles.breadcrumb}>Manager / Performance / Statistiques coachs</nav>
    <div className={styles.topline}><div><h1>Statistiques coachs</h1><p className={styles.lead}>Visualisez la charge, la couverture des activités et le suivi des évaluations, sans classement des coachs.</p></div><div className={styles.toolbarActions}><label className="groups-season-nav-select"><select aria-label="Saison" value={context.seasonId} onChange={(event) => context.setSeasonId(event.target.value)}>{context.seasons.map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_current ? " · En cours" : ""}</option>)}</select></label><button type="button" className={styles.refresh} disabled={refreshing} onClick={() => void load(true)}><RefreshCw size={14}/>{refreshing ? "Actualisation…" : "Actualiser"}</button></div></div>
    {context.error || error ? <div className={styles.error} role="alert"><AlertTriangle size={15}/> {context.error || error}</div> : null}
    <section className={campStyles.panel}><div className={styles.filters}><label>Période<select value={preset} onChange={(event) => setPreset(event.target.value as typeof preset)}><option value="season">Saison actuelle</option><option value="30d">30 jours</option><option value="3m">3 mois</option><option value="6m">6 mois</option><option value="12m">12 mois</option><option value="custom">Personnalisée</option></select></label>{preset === "custom" ? <><label>Du<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)}/></label><label>Au<input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)}/></label></> : null}<label>Groupe<select value={group} onChange={(event) => setGroup(event.target.value)}><option value="all">Tous</option>{data?.filters.groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Rôle<select value={role} onChange={(event) => setRole(event.target.value)}><option value="all">Tous</option><option value="head">Responsable</option><option value="assistant">Assistant</option></select></label><label>Statut<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="active">Actifs</option><option value="inactive">Inactifs</option><option value="all">Tous</option></select></label></div><PerformanceAppliedPeriod from={range.from} to={range.to}/></section>
    <ManagerStatisticsTabs<Tab> items={tabs} value={tab} onChange={setTab} ariaLabel="Sections statistiques coachs" />
    {(loading || context.loading) && !data ? <section className={campStyles.panel}><ListLoadingBlock label="Chargement des statistiques coachs…"/></section> : data ? <>
      {tab === "overview" ? <><div className={styles.kpis}><Kpi label="Coachs actifs" value={String(data.overview.activeCoaches)} detail="Statut club et saison actifs"/><Kpi label="Activités réalisées" value={String(data.overview.activities)} detail="Activités uniques de la période"/><Kpi label="Heures d’activité" value={metric(data.overview.activityHours," h")} detail="Sans double comptage des activités"/><Kpi label="Heures-coachs" value={metric(data.overview.coachHours," h")} detail="Durée attribuée à chaque coach affecté"/><Kpi label="Juniors médians" value={metric(data.overview.medianPlayers)} detail="Juniors différents par coach"/><Kpi label="Couverture" value={metric(data.overview.coverageRate," %")} detail="Activités avec un coach explicite"/><Kpi label="Évaluations" value={metric(data.overview.evaluationCompletionRate," %")} detail="Évaluations attribuables réalisées"/><Kpi label="Présences à renseigner" value={String(data.overview.pendingAttendance)} detail="Statuts encore en attente"/></div><CoachTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId}/></> : null}
      {tab === "load" ? <section className={campStyles.panel}><Header title="Répartition de la charge" text={`Médiane du club : ${metric(data.distribution.medianCoachHours," h-coachs")}. Ces volumes sont présentés sans jugement contractuel.`}/><div className={styles.chart} role="img" aria-label="Évolution mensuelle des heures d’activité et des heures-coachs"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.distribution.monthly}><CartesianGrid stroke="#e7ece6" vertical={false}/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}} unit=" h"/><Tooltip/><Legend/><Bar dataKey="activityHours" name="Heures d’activité" fill="#9eafa0" radius={[4,4,0,0]}/><Bar dataKey="coachHours" name="Heures-coachs" fill="#526e54" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><CoachTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId}/></section> : null}
      {tab === "coverage" ? <section className={campStyles.panel}><Header title="Couverture" text="Les affectations explicites sont distinguées des simples rattachements aux groupes."/><div className={styles.grid2}><DataList title="Groupes sans responsable" rows={data.coverage.groupsWithoutHead.map((item) => ({label:item.name,href:`/manager/groups/${item.id}`}))}/><DataList title="Groupes dépendant d’un seul coach" rows={data.coverage.singleCoachGroups.map((item) => ({label:item.name,href:`/manager/groups/${item.id}`}))}/><DataList title="Activités futures sans coach" rows={data.coverage.futureWithoutCoach.map((item) => ({label:item.title,meta:formatDate(item.startsAt),href:"/manager/calendar"}))}/></div></section> : null}
      {tab === "evaluations" ? <section className={campStyles.panel}><Header title="Évaluations" text="Une évaluation est attribuée à son auteur réel ou au responsable explicitement affecté lorsqu’il est identifiable."/><div className={styles.kpis}><Kpi label="Attendues" value={String(data.evaluations.expected)} detail="Paires activité-junior attribuables"/><Kpi label="Réalisées" value={String(data.evaluations.completed)} detail="Évaluation enregistrée"/><Kpi label="En retard" value={String(data.evaluations.overdue)} detail="Plus de 7 jours après l’activité"/><Kpi label="Complétion" value={metric(data.evaluations.completionRate," %")} detail="Réalisées ÷ attendues"/></div><CoachTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId}/></section> : null}
      {tab === "attention" ? <section className={campStyles.panel}><Header title="Centre d’attention" text="Les écarts sont contextualisés et ne constituent pas une note de performance."/><div className={styles.attention}>{data.attention.length ? data.attention.map((item,index) => <Link href={item.href} key={`${item.type}-${item.label}-${index}`}><b>{item.label}</b><span>{item.reason}</span><span>{item.value}</span></Link>) : <div className={styles.empty}>Aucun élément nécessitant une attention particulière.</div>}</div></section> : null}
    </> : null}
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{detail}</small></article>; }
function Header({ title, text }: { title: string; text: string }) { return <div className={styles.sectionHeader}><div><h2>{title}</h2><p>{text}</p></div></div>; }
function DataList({ title, rows }: { title: string; rows: Array<{label:string;meta?:string;href:string}> }) { return <div><h3 className={coachStyles.listTitle}>{title}</h3><div className={coachStyles.compactList}>{rows.length ? rows.map((row,index) => <Link href={row.href} key={`${row.label}-${index}`}><b>{row.label}</b>{row.meta ? <span>{row.meta}</span> : null}</Link>) : <div className={styles.empty}>Aucun élément.</div>}</div></div>; }
function CoachTable({ rows, clubId, seasonId }: { rows: CoachRow[]; clubId: string; seasonId: string }) { return <section className={campStyles.panel}><Header title="Détail par coach" text={`${rows.length} coach${rows.length > 1 ? "s" : ""} dans le périmètre filtré.`}/><div className={campStyles.tableWrap}><table className={`${campStyles.table} ${tableStyles.memberTable}`}><thead><tr><th aria-label="Avatar"/><th>Coach</th><th>Groupes / rôle</th><th>Activités</th><th>Heures-coachs</th><th>Juniors</th><th>Taille habituelle</th><th>Évaluations</th><th>En retard</th><th>Dernière activité</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><ManagerMemberAvatar name={row.name} avatarUrl={row.avatarUrl}/></td><td><Link className={styles.tableLink} href={`/manager/user-management/coaches/${row.memberId}?club=${clubId}&season=${seasonId}&tab=statistics`}>{row.name}</Link>{row.function ? <small> · {row.function}</small> : null}</td><td>{row.groupCount}<small> · {row.role}</small></td><td>{row.activities}</td><td>{metric(row.coachHours," h")}</td><td>{row.uniquePlayers}</td><td>{metric(row.medianGroupSize)}</td><td>{row.evaluationsCompleted} / {row.evaluationsExpected}</td><td>{row.evaluationsOverdue}</td><td>{formatDate(row.lastActivity)}</td></tr>) : <tr><td colSpan={10}><div className={styles.empty}>Aucun coach ne correspond aux filtres.</div></td></tr>}</tbody></table></div></section>; }
