"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw, Search } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import styles from "@/components/admin/AdminHomeStats.module.css";
import actionStyles from "@/components/admin/organizations/OrganizationSettingsAdmin.module.css";

type Club = { id: string; name: string };
type Season = { id: string; name: string; starts_on: string; ends_on: string; is_current: boolean };
type Manager = { id: string; role: string; is_active: boolean | null; auth_email?: string | null; profiles: { first_name: string | null; last_name: string | null; staff_function: string | null; phone: string | null; avatar_url: string | null } | null };

async function authHeaders() { const { data } = await supabase.auth.getSession(); return data.session?.access_token ? { Authorization: `Bearer ${data.session.access_token}` } : {}; }

export default function ManagersManagementPage() {
  const [clubs, setClubs] = useState<Club[]>([]); const [clubId, setClubId] = useState(""); const [seasons, setSeasons] = useState<Season[]>([]); const [seasonId, setSeasonId] = useState(""); const [managers, setManageres] = useState<Manager[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function loadClub(id: string) { if (!id) return; setLoading(true); setError(""); try { const headers = await authHeaders(); const [response, seasonsResponse] = await Promise.all([fetch(`/api/manager/clubs/${id}/members`, { headers, cache: "no-store" }), fetch(`/api/manager/clubs/${id}/seasons`, { headers, cache: "no-store" })]); const json = await response.json(); const seasonsJson = await seasonsResponse.json(); if (!response.ok) throw new Error(json.error ?? "Impossible de charger les managers."); if (!seasonsResponse.ok) throw new Error(seasonsJson.error ?? "Impossible de charger les saisons."); setManageres(((json.members ?? []) as Manager[]).filter((member) => member.role === "manager" && member.is_active !== false)); const nextSeasons = (seasonsJson.seasons ?? []) as Season[]; setSeasons(nextSeasons); setSeasonId((current) => nextSeasons.some((season) => season.id === current) ? current : nextSeasons.find((season) => season.is_current)?.id ?? nextSeasons[0]?.id ?? ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger les managers."); } finally { setLoading(false); } }
  useEffect(() => { void (async () => { try { const response = await fetch("/api/manager/my-clubs", { headers: await authHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Impossible de charger les clubs."); const next = (json.clubs ?? []) as Club[]; const initial = next[0]?.id ?? ""; setClubs(next); setClubId(initial); if (initial) await loadClub(initial); else setLoading(false); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger les clubs."); setLoading(false); } })(); }, []);
  const rows = useMemo(() => managers.filter((manager) => `${manager.profiles?.first_name ?? ""} ${manager.profiles?.last_name ?? ""} ${manager.profiles?.staff_function ?? ""} ${manager.auth_email ?? ""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((left, right) => `${left.profiles?.last_name ?? ""} ${left.profiles?.first_name ?? ""}`.localeCompare(`${right.profiles?.last_name ?? ""} ${right.profiles?.first_name ?? ""}`, "fr-CH")), [managers, query]);
  const incompleteCount = managers.filter((manager) => !manager.profiles?.staff_function || !manager.auth_email).length;
  return <div className={styles.page}>
    <nav aria-label="Fil d’Ariane" style={{ minHeight: 22, color: "#35483b", fontSize: 11, fontWeight: 700 }}>Gestion des utilisateurs / Managers</nav>
    <div className={styles.topline}><div><h1>Managers</h1><p className={styles.lead}>Les accès et coordonnées de l’encadrement du club.</p></div><div className={actionStyles.topActions}><label className="groups-season-nav-select"><select aria-label="Saison" value={seasonId} onChange={(event) => setSeasonId(event.target.value)} disabled={seasons.length === 0}>{seasons.length === 0 ? <option value="">Aucune saison configurée</option> : null}{seasons.map((season) => <option key={season.id} value={season.id}>{season.name}{season.is_current ? " · En cours" : ""}</option>)}</select></label><Link className={actionStyles.primaryButton} href="/manager/user-management/managers/new"><Plus size={16} />Ajouter un manager</Link></div></div>
    {error ? <div role="alert" className={actionStyles.errorAlert}>{error}</div> : null}
    {loading ? <section className={styles.overview}><ListLoadingBlock label="Chargement des managers…" /></section> : <><section className={styles.overview}><div className={styles.statsGrid}><article className={styles.statCard}><span>Managers actifs</span><b>{managers.length}</b><small>dans le club</small></article><article className={styles.statCard}><span>Fonction renseignée</span><b>{managers.filter((manager) => Boolean(manager.profiles?.staff_function)).length}</b><small>profils complets</small></article><article className={styles.statCard}><span>Dossiers incomplets</span><b>{incompleteCount}</b><small>fonction ou e-mail à compléter</small></article></div></section><section className={styles.quickPanel}><div className={styles.sectionHeading}><h2>Managers</h2><button className={styles.refreshButton} type="button" onClick={() => void loadClub(clubId)}><RefreshCw size={14} />Actualiser</button></div><div className="user-mgmt-toolbar"><label className="user-mgmt-field" style={{ minWidth: 240 }}><span className="user-mgmt-field-label">Recherche</span><span style={{ position: "relative" }}><Search size={15} style={{ position: "absolute", left: 10, top: 11, color: "#778178" }} /><input value={query} onChange={(event) => setQuery(event.target.value)} style={{ paddingLeft: 33 }} placeholder="Nom, fonction ou e-mail" /></span></label></div><div className="user-mgmt-table-wrap"><table className="user-mgmt-table user-mgmt-table--compact user-mgmt-table--staff user-mgmt-table--member-list"><thead><tr><th aria-label="Avatar" /><th>Manager</th><th>Fonction</th><th>Adresse e-mail</th><th>Statut</th><th aria-label="Actions" /></tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={6}><div className="marketplace-empty">Aucun manager ne correspond à la recherche.</div></td></tr> : rows.map((manager) => { const name = [manager.profiles?.last_name, manager.profiles?.first_name].filter(Boolean).join(" ") || "Sans nom"; const incomplete = !manager.profiles?.staff_function || !manager.auth_email; return <tr key={manager.id}><td><span className="user-mgmt-member-avatar" aria-hidden="true">{manager.profiles?.avatar_url ? <img src={manager.profiles.avatar_url} alt="" /> : [manager.profiles?.first_name, manager.profiles?.last_name].map((value) => value?.trim().charAt(0).toUpperCase()).join("") || "—"}</span></td><td><b>{name}</b>{incomplete ? <small style={{ display: "block", color: "#ad3d35" }}>Dossier incomplet</small> : null}</td><td>{manager.profiles?.staff_function || "—"}</td><td>{manager.auth_email || "—"}</td><td><span className="pill-soft">Actif</span></td><td><Link className="btn" aria-label={`Éditer ${name}`} href={`/manager/user-management/managers/${manager.id}?club=${clubId}`}>Éditer</Link></td></tr>; })}</tbody></table></div></section></>}
  </div>;
}
