"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- concise loading-state branch */

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import styles from "@/components/manager/Performance.module.css";
import tableStyles from "@/components/manager/PerformanceTables.module.css";
import PerformanceAppliedPeriod from "@/components/manager/PerformanceAppliedPeriod";
import ManagerStatisticsTabs from "@/components/manager/ManagerStatisticsTabs";
import ManagerMemberAvatar from "@/components/manager/ManagerMemberAvatar";
import { performanceHeaders, usePerformanceContext } from "@/components/manager/usePerformanceContext";

type Tab = "overview" | "attendance" | "training" | "competition" | "evaluations" | "attention";
type JuniorRow = { id: string; memberId: string; name: string; avatarUrl: string | null; active: boolean; groupName: string | null; ageCategory: string | null; ftemCode: string | null; attendance: { rate: number | null; present: number; denominator: number; pending: number }; attendanceTrend: { status: string; change: number | null }; trainingMinutes: number; regularityRate: number | null; objectiveRate: number | null; handicapChange: number | null; competitions: number; evaluationsExpected: number; evaluationsCompleted: number; progression: boolean; reasons: string[] };
type Attention = { playerId: string; playerName: string; reason: string; value: string; severity: "positive" | "warning" | "neutral" };
type Data = {
  generatedAt: string; range: { from: string; to: string }; filters: { groups: Array<{ id: string; name: string }>; ftem: Array<{ code: string; label: string }>; activityTypes: string[] };
  overview: { activeJuniors: number; attendanceRate: number | null; medianActivities: number | null; medianTrainingMinutes: number | null; progressing: number; evaluationCoverage: number | null; competitionParticipation: number | null; dataCompleteness: number | null };
  attendance: { monthly: Array<{ month: string; rate: number | null; present: number; absent: number; excused: number; pending: number }>; present: number; absent: number; excused: number; pending: number; assiduous: number; progressing: number; declining: number };
  training: { totalMinutes: number; medianMinutes: number | null; medianObjectiveRate: number | null; medianRegularityRate: number | null; objectiveDistribution: Record<string, number> };
  competition: { participating: number; medianCompetitions: number | null; rounds: number; missingResults: number };
  evaluations: { expected: number; completed: number; missing: number; coverage: number | null };
  byGroup: Array<{ id: string; label: string; count: number; attendanceRate: number | null; medianTrainingMinutes: number | null }>;
  rows: JuniorRow[]; attention: Attention[];
};

const duration = (value: number | null) => value == null ? "Données insuffisantes" : `${Math.floor(value / 60)} h ${String(Math.round(value % 60)).padStart(2, "0")}`;
const number = (value: number | null, suffix = "") => value == null ? "Données insuffisantes" : `${value.toLocaleString("fr-CH")}${suffix}`;
const presets = { season: 0, "30d": 30, "3m": 3, "6m": 6, "12m": 12 } as const;
const tabs: ReadonlyArray<{ value: Tab; label: string }> = [
  { value: "overview", label: "Vue d’ensemble" },
  { value: "attendance", label: "Assiduité" },
  { value: "training", label: "Entraînement" },
  { value: "competition", label: "Compétitions" },
  { value: "evaluations", label: "Évaluations" },
  { value: "attention", label: "Centre d’attention" },
];

export default function ManagerJuniorPerformancePage() {
  const context = usePerformanceContext(); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [tab, setTab] = useState<Tab>("overview");
  const [preset, setPreset] = useState<keyof typeof presets | "custom">("season"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [group, setGroup] = useState("all"); const [ftem, setFtem] = useState("all"); const [age, setAge] = useState("all"); const [activityType, setActivityType] = useState("all"); const [status, setStatus] = useState("active"); const [comparison, setComparison] = useState("previous");
  const season = context.seasons.find((item) => item.id === context.seasonId);
  const range = useMemo(() => { const today = new Date(); if (preset === "season") return { from: season?.starts_on ?? "", to: season?.ends_on && season.ends_on < today.toISOString().slice(0, 10) ? season.ends_on : today.toISOString().slice(0, 10) }; if (preset === "custom") return { from, to }; const start = new Date(today); if (preset === "30d") start.setUTCDate(start.getUTCDate() - 29); else start.setUTCMonth(start.getUTCMonth() - presets[preset]); return { from: start.toISOString().slice(0, 10), to: today.toISOString().slice(0, 10) }; }, [from, preset, season, to]);
  async function load(background = false) { if (!context.clubId || !context.seasonId || !range.from || !range.to || range.from > range.to) return; background ? setRefreshing(true) : setLoading(true); setError(""); try { const query = new URLSearchParams({ season: context.seasonId, from: range.from, to: range.to, group, ftem, age, activityType, status, comparison }); const response = await fetch(`/api/manager/clubs/${context.clubId}/performance/juniors?${query}`, { headers: await performanceHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? "Chargement impossible."); setData(json); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { void load(Boolean(data)); }, [context.clubId, context.seasonId, range.from, range.to, group, ftem, age, activityType, status, comparison]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className={`${styles.page} ${tableStyles.scope}`}>
    <nav className={styles.breadcrumb}>Manager / Performance / Statistiques juniors</nav>
    <div className={styles.topline}><div><h1>Statistiques juniors</h1><p className={styles.lead}>Suivez l’assiduité, l’entraînement, la progression et la qualité des données du club.</p></div><div className={styles.toolbarActions}><label className="groups-season-nav-select"><select aria-label="Saison" value={context.seasonId} onChange={(event) => context.setSeasonId(event.target.value)}>{context.seasons.map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_current ? " · En cours" : ""}</option>)}</select></label><button type="button" className={styles.refresh} disabled={refreshing} onClick={() => void load(true)}><RefreshCw size={14} />{refreshing ? "Actualisation…" : "Actualiser"}</button></div></div>
    {context.error || error ? <div className={styles.error} role="alert"><AlertTriangle size={15} /> {context.error || error}</div> : null}
    <section className={campStyles.panel}><div className={styles.filters}><label>Période<select value={preset} onChange={(event) => setPreset(event.target.value as typeof preset)}><option value="season">Saison actuelle</option><option value="30d">30 jours</option><option value="3m">3 mois</option><option value="6m">6 mois</option><option value="12m">12 mois</option><option value="custom">Personnalisée</option></select></label>{preset === "custom" ? <><label>Du<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></label><label>Au<input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></label></> : null}<label>Groupe<select value={group} onChange={(event) => setGroup(event.target.value)}><option value="all">Tous</option>{data?.filters.groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Niveau FTEM<select value={ftem} onChange={(event) => setFtem(event.target.value)}><option value="all">Tous</option>{data?.filters.ftem.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.label}</option>)}</select></label><label>Catégorie d’âge<select value={age} onChange={(event) => setAge(event.target.value)}><option value="all">Toutes</option>{["U12","U14","U16","U18","18+"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Type d’activité<select value={activityType} onChange={(event) => setActivityType(event.target.value)}><option value="all">Tous</option>{data?.filters.activityTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label>Statut<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="active">Actifs</option><option value="inactive">Inactifs</option><option value="all">Tous</option></select></label><label>Comparaison<select value={comparison} onChange={(event) => setComparison(event.target.value)}><option value="previous">Période précédente</option><option value="none">Aucune</option></select></label></div><PerformanceAppliedPeriod from={range.from} to={range.to}/></section>
    <ManagerStatisticsTabs<Tab> items={tabs} value={tab} onChange={setTab} ariaLabel="Sections statistiques juniors" />
    {(loading || context.loading) && !data ? <section className={campStyles.panel}><ListLoadingBlock label="Chargement des statistiques juniors…" /></section> : data ? <>
      {tab === "overview" ? <><div className={styles.kpis}><Kpi label="Juniors actifs" value={String(data.overview.activeJuniors)} detail="Statut club et saison actifs" /><Kpi label="Assiduité du club" value={number(data.overview.attendanceRate," %")} detail="Présences ÷ présences et absences" /><Kpi label="Activités médianes" value={number(data.overview.medianActivities)} detail="Par junior sur la période" /><Kpi label="Volume médian" value={duration(data.overview.medianTrainingMinutes)} detail="Entraînement enregistré par junior" /><Kpi label="Juniors en progression" value={String(data.overview.progressing)} detail="Au moins un signal fiable et expliqué" /><Kpi label="Évaluations réalisées" value={number(data.overview.evaluationCoverage," %")} detail="Couverture des activités attendues" /><Kpi label="Participation compétition" value={number(data.overview.competitionParticipation," %")} detail="Juniors avec au moins une compétition" /><Kpi label="Complétude des données" value={number(data.overview.dataCompleteness," %")} detail="Juniors avec au moins une donnée exploitable" /></div><JuniorTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId} /></> : null}
      {tab === "attendance" ? <section className={campStyles.panel}><Header title="Assiduité" text="Les absences excusées et statuts en attente sont exclus du taux principal." /><div className={styles.smallGrid}><Small label="Présents" value={data.attendance.present} /><Small label="Absents" value={data.attendance.absent} /><Small label="Excusés" value={data.attendance.excused} /><Small label="À traiter" value={data.attendance.pending} /><Small label="Juniors assidus" value={data.attendance.assiduous} /></div><div className={styles.chart} role="img" aria-label="Évolution mensuelle de l’assiduité"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.attendance.monthly}><CartesianGrid stroke="#e7ece6" vertical={false}/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis domain={[0,100]} unit=" %" tick={{fontSize:10}}/><Tooltip/><Line dataKey="rate" name="Assiduité" stroke="#607b5b" strokeWidth={2.5}/></LineChart></ResponsiveContainer></div><GroupTable rows={data.byGroup} /></section> : null}
      {tab === "training" ? <section className={campStyles.panel}><Header title="Entraînement" text="Le volume est présenté sans jugement ; le repère dépend du niveau FTEM et des mois de saison." /><div className={styles.kpis}><Kpi label="Volume total" value={duration(data.training.totalMinutes)} detail="Tous les juniors filtrés"/><Kpi label="Volume médian" value={duration(data.training.medianMinutes)} detail="Moins sensible aux extrêmes"/><Kpi label="Réalisation médiane" value={number(data.training.medianObjectiveRate," %")} detail="Du repère FTEM proratisé"/><Kpi label="Régularité médiane" value={number(data.training.medianRegularityRate," %")} detail="Semaines avec activité enregistrée"/></div><Distribution values={data.training.objectiveDistribution}/></section> : null}
      {tab === "competition" ? <section className={campStyles.panel}><Header title="Compétitions" text="Participation et résultats enregistrés sont distingués."/><div className={styles.kpis}><Kpi label="Juniors participants" value={String(data.competition.participating)} detail="Au moins une compétition"/><Kpi label="Compétitions médianes" value={number(data.competition.medianCompetitions)} detail="Par junior"/><Kpi label="Tours joués" value={String(data.competition.rounds)} detail="Compétition et entraînement"/><Kpi label="Résultats manquants" value={String(data.competition.missingResults)} detail="Participation connue, résultat absent"/></div><JuniorTable rows={data.rows.filter((row) => row.competitions > 0)} clubId={context.clubId} seasonId={context.seasonId}/></section> : null}
      {tab === "evaluations" ? <section className={campStyles.panel}><Header title="Évaluations" text="La couverture mesure les activités attendues ayant reçu une évaluation coach."/><div className={styles.kpis}><Kpi label="Attendues" value={String(data.evaluations.expected)} detail="Activités nécessitant une évaluation"/><Kpi label="Réalisées" value={String(data.evaluations.completed)} detail="Une évaluation enregistrée"/><Kpi label="Manquantes" value={String(data.evaluations.missing)} detail="Action encore nécessaire"/><Kpi label="Couverture" value={number(data.evaluations.coverage," %")} detail="Réalisées ÷ attendues"/></div></section> : null}
      {tab === "attention" ? <AttentionList rows={data.attention} juniors={data.rows} clubId={context.clubId} seasonId={context.seasonId}/> : null}
    </> : null}
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{detail}</small></article>; }
function Small({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><b>{value}</b></div>; }
function Header({ title, text }: { title: string; text: string }) { return <div className={styles.sectionHeader}><div><h2>{title}</h2><p>{text}</p></div></div>; }
function Distribution({ values }: { values: Record<string, number> }) { const rows = [{key:'below60',label:'Moins de 60 %'},{key:'from60to89',label:'60 à 89 %'},{key:'from90to120',label:'90 à 120 %'},{key:'above120',label:'Plus de 120 %'},{key:'undefined',label:'Objectif non défini'}]; const max = Math.max(1,...Object.values(values)); return <div className={styles.distribution}>{rows.map((row) => <div key={row.key}><span>{row.label}</span><span className={styles.track}><i style={{width:`${((values[row.key] ?? 0)/max)*100}%`}}/></span><b>{values[row.key] ?? 0}</b></div>)}</div>; }
function GroupTable({ rows }: { rows: Data['byGroup'] }) { return <div className={campStyles.tableWrap}><table className={campStyles.table}><thead><tr><th>Groupe</th><th>Juniors</th><th>Assiduité</th><th>Volume médian</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.label}</b></td><td>{row.count}</td><td>{number(row.attendanceRate," %")}</td><td>{duration(row.medianTrainingMinutes)}</td></tr>)}</tbody></table></div>; }
function JuniorTable({ rows, clubId, seasonId }: { rows: JuniorRow[]; clubId: string; seasonId: string }) { return <section className={campStyles.panel}><Header title="Détail par junior" text={`${rows.length} junior${rows.length > 1 ? 's' : ''} dans le périmètre filtré.`}/><div className={campStyles.tableWrap}><table className={`${campStyles.table} ${tableStyles.memberTable}`}><thead><tr><th aria-label="Avatar"/><th>Junior</th><th>Groupe / FTEM</th><th>Assiduité</th><th>Entraînement</th><th>Objectif</th><th>Compétitions</th><th>Progression</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><ManagerMemberAvatar name={row.name} avatarUrl={row.avatarUrl}/></td><td><Link className={styles.tableLink} href={`/manager/user-management/players/${row.memberId}?club=${clubId}&season=${seasonId}&tab=statistics`}>{row.name}</Link></td><td>{row.groupName ?? 'Sans groupe'}<small> · {row.ftemCode ?? 'FTEM indisponible'}</small></td><td>{number(row.attendance.rate," %")}<small> · {row.attendance.denominator} activité(s)</small></td><td>{duration(row.trainingMinutes)}</td><td>{number(row.objectiveRate," %")}</td><td>{row.competitions}</td><td>{row.reasons.length ? row.reasons.join(' · ') : 'Données insuffisantes'}</td></tr>) : <tr><td colSpan={8}><div className={styles.empty}>Aucun junior ne correspond aux filtres.</div></td></tr>}</tbody></table></div></section>; }
function AttentionList({ rows, juniors, clubId, seasonId }: { rows: Attention[]; juniors: JuniorRow[]; clubId: string; seasonId: string }) { return <section className={campStyles.panel}><Header title="Centre d’attention" text="Situations opérationnelles et progressions à valoriser, sans classement des juniors."/><div className={styles.attention}>{rows.length ? rows.map((row,index) => <Link key={`${row.playerId}-${row.reason}-${index}`} className={row.severity === 'positive' ? styles.positive : row.severity === 'warning' ? styles.warning : ''} href={`/manager/user-management/players/${juniors.find((junior) => junior.id === row.playerId)?.memberId ?? row.playerId}?club=${clubId}&season=${seasonId}&tab=statistics`}><b>{row.playerName}</b><span>{row.reason}</span><span>{row.value}</span></Link>) : <div className={styles.empty}>Aucun élément nécessitant une attention particulière.</div>}</div></section>; }
