"use client";

import Link from "next/link";
import { useManagerPerformanceLabels } from "./useManagerPerformanceLabels";
import type { ManagerAttentionValue, ManagerProgressSignal } from "@/lib/managerPerformancePresentation";
import { managerActivityLabel } from "@/lib/managerLocale";
import ManagerClubSelect from "./ManagerClubSelect";
import { useManagerResource } from "./useManagerResource";
import { useMemo, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import styles from "@/components/manager/Performance.module.css";
import tableStyles from "@/components/manager/PerformanceTables.module.css";
import PerformanceAppliedPeriod from "@/components/manager/PerformanceAppliedPeriod";
import ManagerStatisticsTabs from "@/components/manager/ManagerStatisticsTabs";
import ManagerMemberAvatar from "@/components/manager/ManagerMemberAvatar";
import { usePerformanceContext } from "@/components/manager/usePerformanceContext";

type Tab = "overview" | "attendance" | "training" | "competition" | "evaluations" | "attention";
type JuniorRow = { id: string; memberId: string; name: string; avatarUrl: string | null; active: boolean; groupName: string | null; ageCategory: string | null; ftemCode: string | null; attendance: { rate: number | null; present: number; denominator: number; pending: number }; attendanceTrend: { status: string; change: number | null }; trainingMinutes: number; regularityRate: number | null; objectiveRate: number | null; handicapChange: number | null; competitions: number; evaluationsExpected: number; evaluationsCompleted: number; progression: boolean; reasons: string[]; progressionSignals: ManagerProgressSignal[] };
type Attention = ManagerAttentionValue & { playerId: string; playerName: string; reason: string; value: string; severity: "positive" | "warning" | "neutral" };
type Data = {
  generatedAt: string; range: { from: string; to: string }; filters: { groups: Array<{ id: string; name: string }>; ftem: Array<{ code: string; label: string }>; activityTypes: string[] };
  overview: { activeJuniors: number; attendanceRate: number | null; medianActivities: number | null; medianTrainingMinutes: number | null; progressing: number; evaluationCoverage: number | null; competitionParticipation: number | null; dataCompleteness: number | null };
  attendance: { monthly: Array<{ month: string; rate: number | null; present: number; absent: number; excused: number; pending: number }>; present: number; absent: number; excused: number; pending: number; assiduous: number; progressing: number; declining: number };
  training: { totalMinutes: number; medianMinutes: number | null; medianObjectiveRate: number | null; medianRegularityRate: number | null; objectiveDistribution: Record<string, number> };
  competition: { participating: number; medianCompetitions: number | null; rounds: number; missingResults: number };
  evaluations: { expected: number; completed: number; missing: number; coverage: number | null };
  byGroup: Array<{ id: string; label: string; count: number; attendanceRate: number | null; medianTrainingMinutes: number | null }>;
  rows: JuniorRow[]; attention: Attention[];
};

const presets = { season: 0, "30d": 30, "3m": 3, "6m": 6, "12m": 12 } as const;

export default function ManagerJuniorPerformancePage() {
  const { t, metric: number, duration, month } = useManagerPerformanceLabels();
  const tabs: ReadonlyArray<{ value: Tab; label: string }> = [
  { value: "overview", label: t("manager.performance.overview") },
  { value: "attendance", label: t("manager.performance.attendance") },
  { value: "training", label: t("manager.performance.training") },
  { value: "competition", label: t("manager.performance.competitions") },
  { value: "evaluations", label: t("manager.performance.evaluations") },
  { value: "attention", label: t("manager.performance.attention") },
];
  const context = usePerformanceContext(); const [tab, setTab] = useState<Tab>("overview");
  const [preset, setPreset] = useState<keyof typeof presets | "custom">("season"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [groupSelection, setGroupSelection] = useState({ scope: "", id: "all" });
  const filterScope = `${context.clubId}:${context.seasonId}`;
  const group = groupSelection.scope === filterScope ? groupSelection.id : "all";
  const setGroup = (id: string) => setGroupSelection({ scope: filterScope, id }); const [ftem, setFtem] = useState("all"); const [age, setAge] = useState("all"); const [activityType, setActivityType] = useState("all"); const [status, setStatus] = useState("active"); const [comparison, setComparison] = useState("previous");
  const season = context.seasons.find((item) => item.id === context.seasonId);
  const range = useMemo(() => { const today = new Date(); if (preset === "season") return { from: season?.starts_on ?? "", to: season?.ends_on && season.ends_on < today.toISOString().slice(0, 10) ? season.ends_on : today.toISOString().slice(0, 10) }; if (preset === "custom") return { from, to }; const start = new Date(today); if (preset === "30d") start.setUTCDate(start.getUTCDate() - 29); else start.setUTCMonth(start.getUTCMonth() - presets[preset]); return { from: start.toISOString().slice(0, 10), to: today.toISOString().slice(0, 10) }; }, [from, preset, season, to]);
  const validRange = Boolean(range.from && range.to && range.from <= range.to);
  const query = new URLSearchParams({ season: context.seasonId, from: range.from, to: range.to, group, ftem, age, activityType, status, comparison });
  const resource = useManagerResource<Data>(context.clubId && context.seasonId && validRange ? `/api/manager/clubs/${context.clubId}/performance/juniors?${query}` : null, t("manager.loadError"));
  const { data, loading, error } = resource;
  const refreshing = loading && Boolean(data);
  return <div className={`${styles.page} ${tableStyles.scope}`}>
    <nav aria-label={t("common.breadcrumb")} className={styles.breadcrumb}>{t("manager.performance.juniorBreadcrumb")}</nav>
    <div className={styles.topline}><div><h1>{t("manager.performance.juniorTitle")}</h1><p className={styles.lead}>{t("manager.performance.juniorLead")}</p></div><div className={styles.toolbarActions}><ManagerClubSelect clubs={context.clubs} clubId={context.clubId} onChange={context.setClubId} /><label className="groups-season-nav-select"><select aria-label={t("manager.season")} disabled={!context.seasons.length} value={context.seasonId} onChange={(event) => context.setSeasonId(event.target.value)}>{!context.seasonId ? <option value="">{t(context.seasons.length ? "manager.chooseSeason" : "manager.noSeason")}</option> : null}{context.seasons.map((item) => <option key={item.id} value={item.id}>{item.name}{item.is_current ? ` · ${t("manager.current")}` : ""}</option>)}</select></label><button type="button" className={styles.refresh} disabled={loading || !context.seasonId || !validRange} onClick={resource.reload}><RefreshCw size={14} />{refreshing ? t("manager.refreshing") : t("manager.refresh")}</button></div></div>
    {context.error || error ? <div className={styles.error} role="alert"><AlertTriangle size={15} /> {context.error || error}</div> : null}
    {!context.loading && context.seasonId && !validRange ? <p role="status">{t("manager.invalidPeriod")}</p> : null}
    <section className={campStyles.panel}><div className={styles.filters}><label>{t("manager.performance.period")}<select value={preset} onChange={(event) => setPreset(event.target.value as typeof preset)}><option value="season">{t("manager.performance.season")}</option><option value="30d">{t("manager.performance.days30")}</option><option value="3m">{t("manager.performance.months3")}</option><option value="6m">{t("manager.performance.months6")}</option><option value="12m">{t("manager.performance.months12")}</option><option value="custom">{t("manager.performance.custom")}</option></select></label>{preset === "custom" ? <><label>{t("manager.performance.from")}<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></label><label>{t("manager.performance.to")}<input type="date" value={to} min={from} onChange={(event) => setTo(event.target.value)} /></label></> : null}<label>{t("manager.performance.group")}<select value={group} onChange={(event) => setGroup(event.target.value)}><option value="all">{t("manager.performance.all")}</option>{data?.filters.groups.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{t("manager.performance.ftemLevel")}<select value={ftem} onChange={(event) => setFtem(event.target.value)}><option value="all">{t("manager.performance.all")}</option>{data?.filters.ftem.map((item) => <option key={item.code} value={item.code}>{item.code} · {item.label}</option>)}</select></label><label>{t("manager.performance.ageCategory")}<select value={age} onChange={(event) => setAge(event.target.value)}><option value="all">{t("manager.performance.allCategories")}</option>{["U12","U14","U16","U18","18+"].map((item) => <option key={item}>{item}</option>)}</select></label><label>{t("manager.performance.activityType")}<select value={activityType} onChange={(event) => setActivityType(event.target.value)}><option value="all">{t("manager.performance.all")}</option>{data?.filters.activityTypes.map((item) => <option key={item} value={item}>{managerActivityLabel(t, item)}</option>)}</select></label><label>{t("manager.performance.status")}<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="active">{t("manager.performance.active")}</option><option value="inactive">{t("manager.performance.inactive")}</option><option value="all">{t("manager.performance.all")}</option></select></label><label>{t("manager.performance.comparison")}<select value={comparison} onChange={(event) => setComparison(event.target.value)}><option value="previous">{t("manager.performance.previous")}</option><option value="none">{t("manager.performance.none")}</option></select></label></div><PerformanceAppliedPeriod from={range.from} to={range.to}/></section>
    <ManagerStatisticsTabs<Tab> items={tabs} value={tab} onChange={setTab} ariaLabel={t("manager.performance.juniorSections")} />
    {(loading || context.loading) && !data ? <section className={campStyles.panel}><ListLoadingBlock label={t("manager.performance.loadingJuniors")} /></section> : data ? <>
      {tab === "overview" ? <><div className={styles.kpis}><Kpi label={t("manager.performance.activeJuniors")} value={String(data.overview.activeJuniors)} detail={t("manager.performance.activeHelp")} /><Kpi label={t("manager.performance.clubAttendance")} value={number(data.overview.attendanceRate," %")} detail={t("manager.performance.attendanceRateHelp")} /><Kpi label={t("manager.performance.medianActivities")} value={number(data.overview.medianActivities)} detail={t("manager.performance.perJuniorPeriod")} /><Kpi label={t("manager.performance.medianVolume")} value={duration(data.overview.medianTrainingMinutes)} detail={t("manager.performance.recordedTraining")} /><Kpi label={t("manager.performance.progressingJuniors")} value={String(data.overview.progressing)} detail={t("manager.performance.reliableSignal")} /><Kpi label={t("manager.performance.completedEvaluations")} value={number(data.overview.evaluationCoverage," %")} detail={t("manager.performance.expectedCoverage")} /><Kpi label={t("manager.performance.competitionParticipation")} value={number(data.overview.competitionParticipation," %")} detail={t("manager.performance.juniorsWithCompetition")} /><Kpi label={t("manager.performance.dataCompleteness")} value={number(data.overview.dataCompleteness," %")} detail={t("manager.performance.usableData")} /></div><JuniorTable rows={data.rows} clubId={context.clubId} seasonId={context.seasonId} /></> : null}
      {tab === "attendance" ? <section className={campStyles.panel}><Header title={t("manager.performance.attendance")} text={t("manager.performance.attendanceHelp")} /><div className={styles.smallGrid}><Small label={t("manager.performance.present")} value={data.attendance.present} /><Small label={t("manager.performance.absent")} value={data.attendance.absent} /><Small label={t("manager.performance.excused")} value={data.attendance.excused} /><Small label={t("manager.performance.pending")} value={data.attendance.pending} /><Small label={t("manager.performance.assiduous")} value={data.attendance.assiduous} /></div><div className={styles.chart} role="img" aria-label={t("manager.performance.monthlyAttendance")}><ResponsiveContainer width="100%" height="100%"><LineChart data={data.attendance.monthly}><CartesianGrid stroke="#e7ece6" vertical={false}/><XAxis tickFormatter={month} dataKey="month" tick={{fontSize:10}}/><YAxis domain={[0,100]} unit=" %" tick={{fontSize:10}}/><Tooltip labelFormatter={(label) => month(String(label))} formatter={(value) => number(Number(value), " %")}/><Line dataKey="rate" name={t("manager.performance.attendance")} stroke="#607b5b" strokeWidth={2.5}/></LineChart></ResponsiveContainer></div><GroupTable rows={data.byGroup} /></section> : null}
      {tab === "training" ? <section className={campStyles.panel}><Header title={t("manager.performance.training")} text={t("manager.performance.trainingHelp")} /><div className={styles.kpis}><Kpi label={t("manager.performance.totalVolume")} value={duration(data.training.totalMinutes)} detail={t("manager.performance.filteredJuniors")}/><Kpi label={t("manager.performance.medianVolume")} value={duration(data.training.medianMinutes)} detail={t("manager.performance.medianHelp")}/><Kpi label={t("manager.performance.medianAchievement")} value={number(data.training.medianObjectiveRate," %")} detail={t("manager.performance.proratedFtem")}/><Kpi label={t("manager.performance.medianRegularity")} value={number(data.training.medianRegularityRate," %")} detail={t("manager.performance.activeWeeks")}/></div><Distribution values={data.training.objectiveDistribution}/></section> : null}
      {tab === "competition" ? <section className={campStyles.panel}><Header title={t("manager.performance.competitions")} text={t("manager.performance.competitionHelp")}/><div className={styles.kpis}><Kpi label={t("manager.performance.participating")} value={String(data.competition.participating)} detail={t("manager.performance.oneCompetition")}/><Kpi label={t("manager.performance.medianCompetitions")} value={number(data.competition.medianCompetitions)} detail={t("manager.performance.perJunior")}/><Kpi label={t("manager.performance.rounds")} value={String(data.competition.rounds)} detail={t("manager.performance.roundsHelp")}/><Kpi label={t("manager.performance.missingResults")} value={String(data.competition.missingResults)} detail={t("manager.performance.missingResultsHelp")}/></div><JuniorTable rows={data.rows.filter((row) => row.competitions > 0)} clubId={context.clubId} seasonId={context.seasonId}/></section> : null}
      {tab === "evaluations" ? <section className={campStyles.panel}><Header title={t("manager.performance.evaluations")} text={t("manager.performance.juniorEvaluationsHelp")}/><div className={styles.kpis}><Kpi label={t("manager.performance.expected")} value={String(data.evaluations.expected)} detail={t("manager.performance.expectedHelp")}/><Kpi label={t("manager.performance.completed")} value={String(data.evaluations.completed)} detail={t("manager.performance.oneEvaluation")}/><Kpi label={t("manager.performance.missing")} value={String(data.evaluations.missing)} detail={t("manager.performance.actionRequired")}/><Kpi label={t("manager.performance.coverage")} value={number(data.evaluations.coverage," %")} detail={t("manager.performance.completedExpected")}/></div></section> : null}
      {tab === "attention" ? <AttentionList rows={data.attention} juniors={data.rows} clubId={context.clubId} seasonId={context.seasonId}/> : null}
    </> : null}
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{detail}</small></article>; }
function Small({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><b>{value}</b></div>; }
function Header({ title, text }: { title: string; text: string }) { return <div className={styles.sectionHeader}><div><h2>{title}</h2><p>{text}</p></div></div>; }
function Distribution({ values }: { values: Record<string, number> }) { const { t } = useManagerPerformanceLabels(); const rows = [{key:'below60',label:t("manager.performance.below60")},{key:'from60to89',label:t("manager.performance.from60to89")},{key:'from90to120',label:t("manager.performance.from90to120")},{key:'above120',label:t("manager.performance.above120")},{key:'undefined',label:t("manager.performance.undefined")}]; const max = Math.max(1,...Object.values(values)); return <div className={styles.distribution}>{rows.map((row) => <div key={row.key}><span>{row.label}</span><span className={styles.track}><i style={{width:`${((values[row.key] ?? 0)/max)*100}%`}}/></span><b>{values[row.key] ?? 0}</b></div>)}</div>; }
function GroupTable({ rows }: { rows: Data['byGroup'] }) { const { t, metric: number, duration } = useManagerPerformanceLabels(); return <div className={campStyles.tableWrap}><table className={campStyles.table}><thead><tr><th>{t("manager.performance.group")}</th><th>{t("manager.performance.juniors")}</th><th>{t("manager.performance.attendance")}</th><th>{t("manager.performance.medianVolume")}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td data-label={t("manager.performance.group")}><span className={tableStyles.cellValue}><b>{row.label}</b></span></td><td data-label={t("manager.performance.juniors")}><span className={tableStyles.cellValue}>{row.count}</span></td><td data-label={t("manager.performance.attendance")}><span className={tableStyles.cellValue}>{number(row.attendanceRate," %")}</span></td><td data-label={t("manager.performance.medianVolume")}><span className={tableStyles.cellValue}>{duration(row.medianTrainingMinutes)}</span></td></tr>)}</tbody></table></div>; }
function JuniorTable({ rows, clubId, seasonId }: { rows: JuniorRow[]; clubId: string; seasonId: string }) { const { t, metric: number, duration, count, signals } = useManagerPerformanceLabels(); return <section className={campStyles.panel}><Header title={t("manager.performance.juniorDetail")} text={count("juniorCount", rows.length)}/><div className={campStyles.tableWrap}><table className={`${campStyles.table} ${tableStyles.memberTable}`}><thead><tr><th aria-label={t("manager.performance.avatar")}/><th>{t("manager.performance.junior")}</th><th>{t("manager.performance.groupFtem")}</th><th>{t("manager.performance.attendance")}</th><th>{t("manager.performance.training")}</th><th>{t("manager.performance.objective")}</th><th>{t("manager.performance.competitions")}</th><th>{t("manager.performance.progress")}</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}><td><ManagerMemberAvatar name={row.name} avatarUrl={row.avatarUrl}/></td><td data-label={t("manager.performance.junior")}><span className={tableStyles.cellValue}><Link className={styles.tableLink} href={`/manager/user-management/players/${row.memberId}?club=${clubId}&season=${seasonId}&tab=statistics`}>{row.name}</Link></span></td><td data-label={t("manager.performance.groupFtem")}><span className={tableStyles.cellValue}>{row.groupName ?? t("manager.performance.noGroup")}<small> · {row.ftemCode ?? t("manager.performance.noFtem")}</small></span></td><td data-label={t("manager.performance.attendance")}><span className={tableStyles.cellValue}>{number(row.attendance.rate," %")}<small> · {count("activityCount", row.attendance.denominator)}</small></span></td><td data-label={t("manager.performance.training")}><span className={tableStyles.cellValue}>{duration(row.trainingMinutes)}</span></td><td data-label={t("manager.performance.objective")}><span className={tableStyles.cellValue}>{number(row.objectiveRate," %")}</span></td><td data-label={t("manager.performance.competitions")}><span className={tableStyles.cellValue}>{row.competitions}</span></td><td data-label={t("manager.performance.progress")}><span className={tableStyles.cellValue}>{row.progressionSignals?.length ? signals(row.progressionSignals) : t("manager.performance.insufficient")}</span></td></tr>) : <tr><td colSpan={8}><div className={styles.empty}>{t("manager.performance.noJuniors")}</div></td></tr>}</tbody></table></div></section>; }
function AttentionList({ rows, juniors, clubId, seasonId }: { rows: Attention[]; juniors: JuniorRow[]; clubId: string; seasonId: string }) { const { t, juniorAttention } = useManagerPerformanceLabels(); return <section className={campStyles.panel}><Header title={t("manager.performance.attention")} text={t("manager.performance.juniorAttentionHelp")}/><div className={styles.attention}>{rows.length ? rows.map((row,index) => <Link key={`${row.playerId}-${row.reason}-${index}`} className={row.severity === 'positive' ? styles.positive : row.severity === 'warning' ? styles.warning : ''} href={`/manager/user-management/players/${juniors.find((junior) => junior.id === row.playerId)?.memberId ?? row.playerId}?club=${clubId}&season=${seasonId}&tab=statistics`}><b>{row.playerName}</b><span>{t(`manager.performance.juniorAttention.${row.type}`)}</span><span>{juniorAttention(row)}</span></Link>) : <div className={styles.empty}>{t("manager.performance.noAttention")}</div>}</div></section>; }
