"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions -- concise loading-state branch */

import { useI18n } from "@/components/i18n/AppI18nProvider";
import { managerPerformanceFormatters } from "@/lib/managerPerformancePresentation";
import { managerAdministrationFeedback, managerAdministrationFormat } from "@/lib/managerAdministrationPresentation";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ListLoadingBlock } from "@/components/ui/LoadingBlocks";
import campStyles from "@/app/manager/camps/Camps.module.css";
import styles from "@/components/manager/Performance.module.css";
import coachStyles from "@/components/manager/CoachPerformance.module.css";
import { performanceHeaders } from "@/components/manager/usePerformanceContext";

type Coach = { id: string; memberId: string; name: string; groups: Array<{ id: string; name: string; role: string; juniors: number }>; activities: number; coachHours: number; previousCoachHours: number; uniquePlayers: number; medianGroupSize: number | null; activeWeeks: number; camps: number; evaluationsExpected: number; evaluationsCompleted: number; evaluationsInProgress: number; evaluationsOverdue: number; visibleFeedbackRate: number | null; lastActivity: string | null; activityTypes: string[]; evaluationTodo: Array<{ eventId: string; playerId: string; groupId: string | null; eventTitle: string; overdueAfterDays: number; reason: string }> };
type Data = { range: { from: string; to: string }; coach: Coach; distribution: { monthly: Array<{ month: string; activityHours: number; coachHours: number }> } };

export default function ManagerCoachStatistics({ clubId, coachId, seasonId, seasonFrom, seasonTo }: { clubId: string; coachId: string; seasonId: string; seasonFrom?: string; seasonTo?: string }) {
  const { t, locale } = useI18n();
  const { metric: display, date, month } = managerPerformanceFormatters(t, locale);
  const format = (key: string, values: Record<string, string | number>) => managerAdministrationFormat(t, key, values);
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("");
  async function load(background = false) { if (!clubId || !coachId || !seasonId) { setData(null); setLoading(false); return; } background ? setRefreshing(true) : setLoading(true); setError(""); try { const today = new Date().toISOString().slice(0,10); const query = new URLSearchParams({ coachId, season: seasonId, status: "all", from: seasonFrom ?? "", to: seasonTo && seasonTo < today ? seasonTo : today }); const response = await fetch(`/api/manager/clubs/${clubId}/performance/coaches?${query}`, { headers: await performanceHeaders(), cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.error ?? t("manager.settings.loadError")); setData(json); } catch (cause) { setError(cause instanceof Error ? cause.message : t("manager.settings.loadError")); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { void load(); }, [clubId, coachId, seasonId, seasonFrom, seasonTo]); // eslint-disable-line react-hooks/exhaustive-deps
  if (loading && !data) return <section className={campStyles.panel}><ListLoadingBlock label={t("manager.administration.stats.loading")}/></section>;
  if (error && !data) return <div className={styles.error} role="alert"><AlertTriangle size={15}/> {managerAdministrationFeedback(t, error)}</div>;
  if (!data?.coach) return <section className={campStyles.panel}><div className={styles.empty}>{t("manager.administration.stats.empty")}</div></section>;
  const coach = data.coach; const change = coach.previousCoachHours > 0 ? Math.round(((coach.coachHours - coach.previousCoachHours) / coach.previousCoachHours) * 1000) / 10 : null;
  return <div className={styles.page}>
    {error ? <div className={styles.error} role="alert">{managerAdministrationFeedback(t, error)}</div> : null}
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>{t("manager.administration.statistics")}</h2><p>{t("manager.administration.stats.lead")}</p></div><button type="button" className={styles.refresh} disabled={refreshing} onClick={() => void load(true)}><RefreshCw size={14}/>{refreshing ? t("manager.refreshing") : t("manager.refresh")}</button></div><div className={styles.kpis}><Kpi label={t("manager.administration.stats.groups")} value={display(coach.groups.length)} detail={t("manager.administration.stats.groupHelp")}/><Kpi label={t("manager.administration.stats.activities")} value={display(coach.activities)} detail={t("manager.administration.stats.assignmentHelp")}/><Kpi label={t("manager.administration.stats.hours")} value={display(coach.coachHours," h")} detail={change == null ? t("manager.administration.stats.noComparison") : format("stats.change", { change: `${change >= 0 ? "+" : ""}${display(change)}` })}/><Kpi label={t("manager.administration.stats.juniors")} value={display(coach.uniquePlayers)} detail={t("manager.administration.stats.uniqueJuniors")}/><Kpi label={t("manager.administration.stats.median")} value={display(coach.medianGroupSize)} detail={t("manager.administration.stats.medianHelp")}/><Kpi label={t("manager.administration.stats.weeks")} value={display(coach.activeWeeks)} detail={t("manager.administration.stats.weeksHelp")}/><Kpi label={t("manager.administration.stats.camps")} value={display(coach.camps)} detail={t("manager.administration.stats.campsHelp")}/><Kpi label={t("manager.performance.completedEvaluations")} value={`${display(coach.evaluationsCompleted)} / ${display(coach.evaluationsExpected)}`} detail={format("stats.overdueCount", { count: display(coach.evaluationsOverdue) })}/></div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>{t("manager.administration.stats.workload")}</h2><p>{t("manager.administration.stats.workloadHelp")}</p></div></div><div className={styles.chart} role="img" aria-label={t("manager.administration.stats.monthly")}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.distribution.monthly}><CartesianGrid stroke="#e7ece6" vertical={false}/><XAxis tickFormatter={month} dataKey="month" tick={{fontSize:10}}/><YAxis unit=" h" tick={{fontSize:10}}/><Tooltip labelFormatter={(value) => month(String(value))} formatter={(value) => display(typeof value === "number" ? value : null, " h")}/><Bar dataKey="coachHours" name={t("manager.performance.coachHours")} fill="#526e54" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>{t("manager.administration.stats.groupsTitle")}</h2><p>{t("manager.administration.stats.groupsLead")}</p></div></div><div className={campStyles.tableWrap}><table className={`${campStyles.table} ${coachStyles.groupTable}`}><thead><tr><th>{t("manager.content.group")}</th><th>{t("manager.performance.role")}</th><th>{t("manager.content.juniors")}</th></tr></thead><tbody>{coach.groups.length ? coach.groups.map((group) => <tr key={group.id}><td data-label={t("manager.content.group")}><Link className={styles.tableLink} href={`/manager/groups/${group.id}`}>{group.name}</Link></td><td data-label={t("manager.performance.role")}>{group.role === "Responsable" ? t("manager.performance.head") : group.role === "Assistant" ? t("manager.performance.assistant") : group.role}</td><td data-label={t("manager.content.juniors")}>{display(group.juniors)}</td></tr>) : <tr><td colSpan={3}><div className={styles.empty}>{t("manager.administration.stats.noGroups")}</div></td></tr>}</tbody></table></div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>{t("manager.administration.stats.todo")}</h2><p>{t("manager.administration.stats.todoHelp")}</p></div></div><div className={styles.attention}>{coach.evaluationTodo.length ? coach.evaluationTodo.map((item) => <Link href={item.groupId ? `/manager/groups/${item.groupId}/planning/${item.eventId}` : "/manager/calendar"} key={`${item.eventId}-${item.playerId}`}><b>{item.eventTitle}</b><span>{format("stats.overdueReason", { days: display(item.overdueAfterDays) })}</span><span>{t("manager.administration.stats.viewActivity")}</span></Link>) : <div className={styles.empty}>{t("manager.administration.stats.noOverdue")}</div>}</div></section>
    <section className={campStyles.panel}><div className={styles.sectionHeader}><div><h2>{t("manager.administration.stats.quality")}</h2><p>{t("manager.administration.stats.qualityHelp")}</p></div></div><div className={styles.smallGrid}><Small label={t("manager.administration.stats.inProgress")} value={display(coach.evaluationsInProgress)}/><Small label={t("manager.performance.coachAttention.evaluation")} value={display(coach.evaluationsOverdue)}/><Small label={t("manager.administration.stats.feedback")} value={display(coach.visibleFeedbackRate, " %")}/><Small label={t("manager.performance.lastActivity")} value={date(coach.lastActivity)}/></div></section>
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.kpi}><span>{label}</span><b>{value}</b><small>{detail}</small></article>; }
function Small({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><b>{value}</b></div>; }
