"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertCircle, ArrowRight, CalendarCheck, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Dumbbell, Flag, MapPin, TentTree, Trophy, TrendingDown, TrendingUp, Users, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import { resolveEffectivePlayerContext } from "@/lib/effectivePlayer";
import { createAppNotification, getEventCoachUserIds } from "@/lib/notifications";
import { getNotificationMessage } from "@/lib/notificationMessages";
import { invalidateClientPageCacheByPrefix } from "@/lib/clientPageCache";
import { AttendanceToggle } from "@/components/ui/AttendanceToggle";
import { useI18n } from "@/components/i18n/AppI18nProvider";
import { pickLocaleText } from "@/lib/i18n/pickLocaleText";
import PlayerBreadcrumb from "@/components/player/PlayerBreadcrumb";
import managerStyles from "@/app/manager/camps/Camps.module.css";
import PlayerTrainingNewClient from "./new/PlayerTrainingNewClient";
import styles from "./PlayerActivities.module.css";
import ActivityDateTile from "@/components/ui/ActivityDateTile";

type CalendarView = "season" | "month" | "week" | "day";
type PlannerType = "training" | "competition" | "camp";
type StatusFilter = "all" | "upcoming" | "past" | "evaluation" | "completed";
type ParticipationFilter = "all" | "present" | "absent" | "expected";
type AttendanceStatus = "expected" | "present" | "absent" | "excused" | "not_registered" | null;
type SessionRow = { id:string; start_at:string; location_text:string|null; session_type:"club"|"private"|"individual"; club_id:string|null; total_minutes:number|null; motivation:number|null; difficulty:number|null; satisfaction:number|null; club_event_id:string|null; player_camp_id?:string|null; player_camp_title?:string|null; player_camp_coach_name?:string|null };
type PlannedEventRow = { id:string; event_type:"training"|"interclub"|"camp"|"session"|"event"|"competition"|null; title:string|null; starts_at:string; ends_at:string|null; duration_minutes:number; location_text:string|null; club_id:string; group_id:string|null; status:"scheduled"|"cancelled"; requires_evaluation:boolean; competition_category?:"u10"|"u12"|"u14"|"u16"|"u18"|"all"|null; competition_note?:string|null };
type PersonalEventRow = { id:string; event_type:"competition"|"camp"; title:string; starts_at:string; ends_at:string; location_text:string|null; notes:string|null; status:"scheduled"|"cancelled" };
type ApiResponse = { viewerUserId:string; effectiveUserId:string; effectivePlayerName:string; performanceEnabled:boolean; sessions:SessionRow[]; attendeeEvents:PlannedEventRow[]; attendeeStatusByEventId:Record<string,AttendanceStatus>; competitionEvents:PersonalEventRow[]; clubNameById:Record<string,string>; groupNameById:Record<string,string> };
type Activity = { key:string; id:string; startsAt:string; endsAt:string; type:string; typeValue:string; title:string; organizer:string; location:string; attendance:AttendanceStatus; isFuture:boolean; isCompetition:boolean; needsEvaluation:boolean; completed:boolean; detail:string|null; category:string|null; event?:PlannedEventRow; session?:SessionRow };

function addDays(d:Date,n:number){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function startDay(d:Date){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function startWeek(d:Date){return addDays(startDay(d),-((d.getDay()+6)%7))}
function ymd(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function localDateTimeValue(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}T${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`}
function defaultPlannerStart(){const date=new Date();date.setDate(date.getDate()+1);date.setHours(18,0,0,0);return localDateTimeValue(date)}
function cap(s:string){return s.charAt(0).toUpperCase()+s.slice(1)}
function eventType(v:PlannedEventRow["event_type"],l:string){if(v==="training")return pickLocaleText(l,"Entraînement","Training");if(v==="interclub")return "Interclub";if(v==="camp")return pickLocaleText(l,"Stage","Camp");if(v==="session")return pickLocaleText(l,"Réunion","Session");if(v==="competition")return pickLocaleText(l,"Compétition","Competition");return pickLocaleText(l,"Événement","Event")}
function sessionType(v:SessionRow["session_type"],l:string){if(v==="private")return pickLocaleText(l,"Cours privé","Private lesson");if(v==="individual")return pickLocaleText(l,"Entraînement individuel","Individual training");return pickLocaleText(l,"Entraînement","Training")}
function participation(s:AttendanceStatus):ParticipationFilter{if(s==="absent"||s==="excused"||s==="not_registered")return "absent";if(s==="present")return "present";return "expected"}
function category(v:PlannedEventRow["competition_category"],l:string){if(!v)return pickLocaleText(l,"Catégorie non précisée","Category not specified");return v==="all"?pickLocaleText(l,"Toutes catégories","All categories"):v.toUpperCase()}
function dedupePlannedActivities(items:Activity[]){const unique=new Map<string,Activity>();items.forEach(item=>{const key=[item.typeValue,new Date(item.startsAt).getTime(),new Date(item.endsAt).getTime(),item.title.trim().toLocaleLowerCase(),item.location.trim().toLocaleLowerCase(),item.event?.club_id??""].join("|");const current=unique.get(key);if(!current||(!current.session&&item.session))unique.set(key,item)});return Array.from(unique.values())}

export default function PlayerActivitiesPage(){
  const {locale}=useI18n(); const router=useRouter(); const searchParams=useSearchParams(); const tr=useCallback((fr:string,en:string)=>pickLocaleText(locale,fr,en),[locale]);
  const dateLocale=locale==="fr"?"fr-CH":locale==="de"?"de-CH":locale==="it"?"it-CH":"en-US";
  const [now]=useState(()=>Date.now()); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const [sessions,setSessions]=useState<SessionRow[]>([]); const [events,setEvents]=useState<PlannedEventRow[]>([]); const [personal,setPersonal]=useState<PersonalEventRow[]>([]);
  const [attendance,setAttendance]=useState<Record<string,AttendanceStatus>>({}); const [clubs,setClubs]=useState<Record<string,string>>({}); const [groups,setGroups]=useState<Record<string,string>>({});
  const [completeIds,setCompleteIds]=useState<Set<string>>(new Set()); const [performance,setPerformance]=useState(false); const [viewerId,setViewerId]=useState(""); const [playerId,setPlayerId]=useState(""); const [playerName,setPlayerName]=useState("");
  const [busyId,setBusyId]=useState(""); const [view,setView]=useState<CalendarView>("month"); const [typeFilter,setTypeFilter]=useState("all"); const [statusFilter,setStatusFilter]=useState<StatusFilter>(searchParams.get("view")==="evaluations"?"evaluation":"upcoming"); const [participationFilter,setParticipationFilter]=useState<ParticipationFilter>("all"); const [anchor,setAnchor]=useState(()=>new Date()); const [expanded,setExpanded]=useState<string|null>(null);
  const [plannerType,setPlannerType]=useState<PlannerType|null>(()=>searchParams.get("plan")==="training"?"training":null);const [plannerTitle,setPlannerTitle]=useState("");const [plannerLocation,setPlannerLocation]=useState("");const [plannerNotes,setPlannerNotes]=useState("");const [plannerStart,setPlannerStart]=useState(defaultPlannerStart);const [plannerEnd,setPlannerEnd]=useState(()=>{const date=new Date(defaultPlannerStart());date.setHours(date.getHours()+2);return localDateTimeValue(date)});const [plannerBusy,setPlannerBusy]=useState(false);const [reloadKey,setReloadKey]=useState(0);

  useEffect(()=>{let cancelled=false;void(async()=>{setLoading(true);setError(null);try{
    const [{data:auth},ctx]=await Promise.all([supabase.auth.getSession(),resolveEffectivePlayerContext()]); const token=auth.session?.access_token??""; if(!token)throw new Error(tr("Session invalide.","Invalid session."));
    const q=new URLSearchParams(); const child=String(searchParams.get("child_id")??"").trim(); const requested=child||(ctx.viewerUserId!==ctx.effectiveUserId?ctx.effectiveUserId:"");if(requested)q.set("child_id",requested);
    const res=await fetch(`/api/player/trainings${q.size?`?${q}`:""}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"}); const json=(await res.json().catch(()=>({}))) as ApiResponse&{error?:string};if(!res.ok)throw new Error(String(json.error??tr("Chargement impossible.","Unable to load.")));
    const loaded=json.sessions??[];const ids=loaded.map(s=>s.id);const rows=ids.length?await supabase.from("training_session_items").select("session_id,minutes").in("session_id",ids):{data:[],error:null};const withContent=new Set<string>();(rows.data??[]).forEach((r:{session_id:string;minutes:number})=>{if(Number(r.minutes)>0)withContent.add(r.session_id)});const done=new Set<string>();loaded.forEach(s=>{if(withContent.has(s.id)&&[s.motivation,s.difficulty,s.satisfaction].every(v=>typeof v==="number"))done.add(s.id)});if(cancelled)return;
    setSessions(loaded);setEvents(json.attendeeEvents??[]);setPersonal(json.competitionEvents??[]);setAttendance(json.attendeeStatusByEventId??{});setClubs(json.clubNameById??{});setGroups(json.groupNameById??{});setCompleteIds(done);setPerformance(Boolean(json.performanceEnabled));setViewerId(json.viewerUserId??"");setPlayerId(json.effectiveUserId??"");setPlayerName(json.effectivePlayerName??tr("Joueur","Player"));
  }catch(e){if(!cancelled)setError(e instanceof Error?e.message:tr("Chargement impossible.","Unable to load."))}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[reloadKey,searchParams,tr]);

  const activities=useMemo<Activity[]>(()=>{
    const byEvent=new Map<string,SessionRow>();sessions.forEach(s=>{if(s.club_event_id&&!byEvent.has(s.club_event_id))byEvent.set(s.club_event_id,s)});
    const planned=dedupePlannedActivities(events.filter(e=>e.status==="scheduled").map(e=>{const s=byEvent.get(e.id);const att=attendance[e.id]??null;const end=e.ends_at??new Date(new Date(e.starts_at).getTime()+Math.max(1,e.duration_minutes)*60000).toISOString();const future=new Date(end).getTime()>=now;const canEval=performance&&e.requires_evaluation&&e.event_type==="training"&&!future&&!["absent","excused","not_registered"].includes(String(att));const done=Boolean(s&&completeIds.has(s.id));const type=eventType(e.event_type,locale);const group=e.group_id?groups[e.group_id]:"";return{key:`event-${e.id}`,id:e.id,startsAt:e.starts_at,endsAt:end,type,typeValue:e.event_type??"event",title:e.title?.trim()||(group?`${type} · ${group}`:type),organizer:clubs[e.club_id]??tr("Club","Club"),location:e.location_text?.trim()||tr("Lieu non renseigné","Location not specified"),attendance:att,isFuture:future,isCompetition:e.event_type==="competition"||e.event_type==="interclub",needsEvaluation:canEval&&!done,completed:!future&&(!canEval||done),detail:e.competition_note?.trim()||null,category:e.event_type==="competition"?category(e.competition_category,locale):null,event:e,session:s} as Activity}));
    const standalone=sessions.filter(s=>!s.club_event_id).map(s=>{const future=new Date(s.start_at).getTime()>=now;const done=completeIds.has(s.id);const type=s.player_camp_id?tr("Stage","Camp"):sessionType(s.session_type,locale);return{key:`session-${s.id}`,id:s.id,startsAt:s.start_at,endsAt:new Date(new Date(s.start_at).getTime()+Math.max(1,Number(s.total_minutes??60))*60000).toISOString(),type,typeValue:s.player_camp_id?"camp":s.session_type,title:s.player_camp_title?.trim()||type,organizer:s.player_camp_coach_name?.trim()||(s.club_id?clubs[s.club_id]:"")||tr("Activité personnelle","Personal activity"),location:s.location_text?.trim()||tr("Lieu non renseigné","Location not specified"),attendance:null,isFuture:future,isCompetition:false,needsEvaluation:performance&&!future&&!done,completed:!future&&(!performance||done),detail:null,category:null,session:s}});
    const own=personal.filter(e=>e.status==="scheduled").map(e=>{const future=new Date(e.ends_at||e.starts_at).getTime()>=now;return{key:`personal-${e.id}`,id:e.id,startsAt:e.starts_at,endsAt:e.ends_at,type:e.event_type==="camp"?tr("Stage","Camp"):tr("Compétition","Competition"),typeValue:e.event_type,title:e.title,organizer:tr("Activité personnelle","Personal activity"),location:e.location_text?.trim()||tr("Lieu non renseigné","Location not specified"),attendance:null,isFuture:future,isCompetition:e.event_type==="competition",needsEvaluation:false,completed:!future,detail:e.notes?.trim()||null,category:null}});
    return [...planned,...standalone,...own].sort((a,b)=>new Date(a.startsAt).getTime()-new Date(b.startsAt).getTime()) as Activity[];
  },[attendance,clubs,completeIds,events,groups,locale,now,performance,personal,sessions,tr]);

  const stats=useMemo(()=>{const today=new Date(now);const seasonStart=new Date(today.getFullYear(),0,1).getTime();const currentStart=new Date(today.getFullYear(),today.getMonth(),1).getTime();const previousStart=new Date(today.getFullYear(),today.getMonth()-1,1).getTime();const allowedTypes=new Set(["training","interclub","camp","event","session"]);const attendanceFor=(from:number,to:number)=>{const eligible=activities.filter(a=>{const time=new Date(a.startsAt).getTime();return Boolean(a.event)&&time>=from&&time<to&&time<now&&allowedTypes.has(a.typeValue)&&(a.attendance==="present"||a.attendance==="absent")});const present=eligible.filter(a=>a.attendance==="present").length;return{present,expected:eligible.length,rate:eligible.length?Math.round(present/eligible.length*100):0}};const current=attendanceFor(currentStart,now);const previous=attendanceFor(previousStart,currentStart);const season=attendanceFor(seasonStart,now);const upcoming=activities.filter(a=>a.isFuture);const counts=new Map<string,number>();upcoming.forEach(a=>counts.set(a.type,(counts.get(a.type)??0)+1));return{upcoming:upcoming.length,upcomingByType:Array.from(counts.entries()).sort((a,b)=>b[1]-a[1]),evaluation:activities.filter(a=>a.needsEvaluation).length,attendance:current.expected?current.rate:null,attendancePresent:current.present,attendanceExpected:current.expected,seasonAttendance:season.expected?season.rate:null,seasonPresent:season.present,seasonExpected:season.expected,trend:current.expected&&previous.expected?current.rate-previous.rate:null}},[activities,now]);
  const nextCompetition=useMemo(()=>activities.filter(a=>a.isCompetition&&a.isFuture)[0]??null,[activities]);
  const visible=useMemo(()=>{const from=view==="season"?new Date(anchor.getFullYear(),0,1):view==="month"?new Date(anchor.getFullYear(),anchor.getMonth(),1):view==="week"?startWeek(anchor):startDay(anchor);const to=view==="season"?new Date(anchor.getFullYear()+1,0,1):view==="month"?new Date(anchor.getFullYear(),anchor.getMonth()+1,1):view==="week"?addDays(from,7):addDays(from,1);return activities.filter(a=>{const t=new Date(a.startsAt).getTime();if(t<from.getTime()||t>=to.getTime())return false;if(typeFilter!=="all"&&a.typeValue!==typeFilter)return false;if(statusFilter==="upcoming"&&!a.isFuture)return false;if(statusFilter==="past"&&a.isFuture)return false;if(statusFilter==="evaluation"&&!a.needsEvaluation)return false;if(statusFilter==="completed"&&!a.completed)return false;if(participationFilter!=="all"&&participation(a.attendance)!==participationFilter)return false;return true})},[activities,anchor,participationFilter,statusFilter,typeFilter,view]);
  const byDay=useMemo(()=>visible.reduce<Record<string,Activity[]>>((r,a)=>{(r[ymd(new Date(a.startsAt))]??=[]).push(a);return r},{}),[visible]);
  const periodLabel=useMemo(()=>{if(view==="season")return String(anchor.getFullYear());if(view==="month")return cap(new Intl.DateTimeFormat(dateLocale,{month:"long",year:"numeric"}).format(anchor));if(view==="week"){const s=startWeek(anchor),e=addDays(s,6);return `${new Intl.DateTimeFormat(dateLocale,{day:"numeric",month:"short"}).format(s)} – ${new Intl.DateTimeFormat(dateLocale,{day:"numeric",month:"short",year:"numeric"}).format(e)}`}return cap(new Intl.DateTimeFormat(dateLocale,{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(anchor))},[anchor,dateLocale,view]);
  function move(n:-1|1){if(view==="season")setAnchor(d=>new Date(d.getFullYear()+n,0,1));else if(view==="month")setAnchor(d=>new Date(d.getFullYear(),d.getMonth()+n,1));else setAnchor(d=>addDays(d,n*(view==="week"?7:1)))}
  function changeView(next:CalendarView){setView(next);if(next==="season")setStatusFilter("all")}
  function showEvaluations(){router.push("/player/golf/trainings/to-complete")}
  async function updateAttendance(e:PlannedEventRow,next:"present"|"absent"){if(!playerId||busyId)return;setBusyId(e.id);setError(null);const result=await supabase.from("club_event_attendees").update({status:next}).eq("event_id",e.id).eq("player_id",playerId);if(result.error){setError(result.error.message);setBusyId("");return}setAttendance(x=>({...x,[e.id]:next}));invalidateClientPageCacheByPrefix("page-cache:player-home:");invalidateClientPageCacheByPrefix("page-cache:player-trainings:");try{const recipients=await getEventCoachUserIds(e.id,e.group_id);if(recipients.length&&viewerId){const type=eventType(e.event_type,locale);if(next==="absent"){const msg=await getNotificationMessage("notif.playerMarkedAbsent",locale==="fr"?"fr":"en",{playerName:playerName||tr("Joueur","Player"),eventType:type,dateTime:new Intl.DateTimeFormat(dateLocale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(e.starts_at))});await createAppNotification({actorUserId:viewerId,kind:"player_marked_absent",title:msg.title,body:msg.body,data:{event_id:e.id,group_id:e.group_id,url:`/coach/groups/${e.group_id??""}/planning/${e.id}`},recipientUserIds:recipients})}else await createAppNotification({actorUserId:viewerId,kind:"player_marked_present",title:tr("Présence confirmée","Attendance confirmed"),body:`${playerName||tr("Joueur","Player")} · ${type}`,data:{event_id:e.id,group_id:e.group_id,url:`/coach/groups/${e.group_id??""}/planning/${e.id}`},recipientUserIds:recipients})}}catch{}setBusyId("")}
  function toggle(a:Activity){if(!a.event)return;const next=participation(a.attendance)==="absent"?"present":"absent";if(window.confirm(next==="absent"?tr("Confirmer votre absence ?","Confirm your absence?"):tr("Confirmer votre présence ?","Confirm your attendance?")))void updateAttendance(a.event,next)}
  function openPlanner(type:PlannerType){const start=defaultPlannerStart();const end=new Date(start);end.setHours(end.getHours()+2);setPlannerType(current=>current===type?null:type);setPlannerTitle("");setPlannerLocation("");setPlannerNotes("");setPlannerStart(start);setPlannerEnd(localDateTimeValue(end));setError(null)}
  async function savePersonalActivity(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!plannerType||plannerType==="training"||plannerBusy)return;if(!playerId){setError(tr("Session invalide.","Invalid session."));return}const startsAt=new Date(plannerStart);const endsAt=new Date(plannerEnd);const title=plannerTitle.trim();if(Number.isNaN(startsAt.getTime())){setError(tr("Date et heure invalides.","Invalid date and time."));return}if(!title){setError(plannerType==="camp"?tr("Le nom du stage est requis.","Camp title is required."):tr("Le nom de la compétition est requis.","Competition title is required."));return}if(Number.isNaN(endsAt.getTime())||endsAt<=startsAt){setError(tr("La fin doit être postérieure au début.","The end must be after the start."));return}setPlannerBusy(true);setError(null);const result=await supabase.from("player_activity_events").insert({user_id:playerId,event_type:plannerType,title,starts_at:startsAt.toISOString(),ends_at:endsAt.toISOString(),location_text:plannerLocation.trim()||null,notes:plannerNotes.trim()||null,status:"scheduled"}).select("id,event_type,title,starts_at,ends_at,location_text,notes,status").single();if(result.error){setError(result.error.message);setPlannerBusy(false);return}setPersonal(current=>[result.data as PersonalEventRow,...current]);invalidateClientPageCacheByPrefix("page-cache:player-home:");invalidateClientPageCacheByPrefix("page-cache:player-trainings:");setAnchor(startsAt);setStatusFilter(startsAt.getTime()>=Date.now()?"upcoming":"all");setPlannerType(null);setPlannerBusy(false)}

  return <div className={`player-dashboard-bg ${styles.page}`}><div className={`app-shell ${styles.shell}`}>
    <PlayerBreadcrumb items={[{label:"Player",href:"/player"},{label:tr("Mes activités","My activities")}]} />
    <header className={managerStyles.topline}><div><h1>{tr("Mes activités","My activities")}</h1><p className={managerStyles.lead}>{tr("Retrouvez votre programme, confirmez vos présences et complétez vos évaluations.","Review your schedule, confirm attendance and complete your evaluations.")}</p></div></header>
    {error?<div className={styles.error} role="alert">{error}</div>:null}
    <section aria-label={tr("Vue d’ensemble","Overview")}><div className={styles.statsGrid}>
      <AttendanceStat icon={<Users size={18}/>} label={tr("Assiduité du mois","Monthly attendance")} rate={stats.attendance} present={stats.attendancePresent} expected={stats.attendanceExpected} trend={stats.trend} locale={locale}/>
      <AttendanceStat icon={<CalendarCheck size={18}/>} label={tr("Assiduité de la saison","Season attendance")} rate={stats.seasonAttendance} present={stats.seasonPresent} expected={stats.seasonExpected} locale={locale}/>
      <UpcomingStat icon={<CalendarDays size={18}/>} label={tr("Activités à venir","Upcoming activities")} value={stats.upcoming} counts={stats.upcomingByType}/>
      <button className={`${styles.statCard} ${styles.actionStat}`} type="button" onClick={showEvaluations} disabled={!stats.evaluation}><div className={styles.statTitle}><span className={styles.statIcon}><AlertCircle size={18}/></span><h3>{tr("À évaluer","To evaluate")}</h3></div><strong>{stats.evaluation}</strong><small>{stats.evaluation?tr("Voir les activités","View activities"):tr("Vous êtes à jour","You are up to date")}{stats.evaluation?<ArrowRight size={13}/>:<Check size={13}/>}</small></button>
    </div></section>
    <section className={styles.plannerSection} aria-labelledby="personal-planning-title"><div className={styles.plannerHeading}><h2 id="personal-planning-title">{tr("Compléter mon planning","Complete my schedule")}</h2><p>{tr("Ajoutez vos activités personnelles au calendrier.","Add your personal activities to the calendar.")}</p></div><div className={styles.plannerShortcuts}>
      <PlannerShortcut active={plannerType==="training"} icon={<Dumbbell size={19}/>} title={tr("Ajouter / planifier un entraînement","Add / schedule a training")} onClick={()=>openPlanner("training")}/>
      <PlannerShortcut active={plannerType==="competition"} icon={<Trophy size={19}/>} title={tr("Ajouter / planifier une compétition","Add / schedule a competition")} onClick={()=>openPlanner("competition")}/>
      <PlannerShortcut active={plannerType==="camp"} icon={<TentTree size={19}/>} title={tr("Ajouter / planifier un stage","Add / schedule a camp")} onClick={()=>openPlanner("camp")}/>
    </div>{plannerType?<div className={`${styles.plannerPanel} ${plannerType==="training"?styles.trainingPlannerPanel:""}`}><div className={styles.plannerPanelHeading}><div><span>{plannerType==="training"?tr("Entraînement personnel","Personal training"):plannerType==="competition"?tr("Compétition personnelle","Personal competition"):tr("Stage personnel","Personal camp")}</span><h3>{plannerType==="training"?tr("Ajouter ou planifier un entraînement","Add or schedule a training"):plannerType==="competition"?tr("Planifier une compétition","Schedule a competition"):tr("Planifier un stage","Schedule a camp")}</h3></div><button type="button" onClick={()=>setPlannerType(null)} aria-label={tr("Fermer le formulaire","Close form")}><X size={17}/></button></div>{plannerType==="training"?<div className={styles.embeddedTrainingForm}><PlayerTrainingNewClient embedded embeddedSubmitClassName={styles.saveButton} embeddedSubmitLabel={tr("Ajouter au calendrier","Add to calendar")} onSaved={()=>{setPlannerType(null);setReloadKey(current=>current+1)}}/></div>:<form className={styles.plannerForm} onSubmit={savePersonalActivity}>
      <label className={styles.wideField}><span>{plannerType==="camp"?tr("Nom du stage","Camp name"):tr("Nom de la compétition","Competition name")}</span><input value={plannerTitle} onChange={e=>setPlannerTitle(e.target.value)} required placeholder={plannerType==="camp"?tr("Stage de printemps","Spring camp"):tr("Championnat du club","Club championship")}/></label>
      <label><span>{tr("Début","Start")}</span><input type="datetime-local" value={plannerStart} onChange={e=>{setPlannerStart(e.target.value);const next=new Date(e.target.value);if(!Number.isNaN(next.getTime())){next.setHours(next.getHours()+2);setPlannerEnd(localDateTimeValue(next))}}} required/></label>
      <label><span>{tr("Fin","End")}</span><input type="datetime-local" value={plannerEnd} onChange={e=>setPlannerEnd(e.target.value)} required/></label>
      <label className={styles.wideField}><span>{tr("Lieu","Location")}</span><input value={plannerLocation} onChange={e=>setPlannerLocation(e.target.value)} placeholder={tr("Lieu de l’activité","Activity location")}/></label>
      <label className={styles.wideField}><span>{tr("Notes","Notes")}</span><textarea rows={3} value={plannerNotes} onChange={e=>setPlannerNotes(e.target.value)} placeholder={tr("Informations utiles…","Useful information…")}/></label>
      <div className={styles.plannerActions}><button type="button" className={styles.cancelButton} onClick={()=>setPlannerType(null)} disabled={plannerBusy}>{tr("Annuler","Cancel")}</button><button type="submit" className={styles.saveButton} disabled={plannerBusy}>{plannerBusy?tr("Enregistrement…","Saving…"):tr("Ajouter au calendrier","Add to calendar")}</button></div>
    </form>}</div>:null}</section>
    {nextCompetition?<section><Heading eyebrow={tr("À ne pas manquer","Don't miss")} title={tr("Prochaine compétition","Next competition")} /><article className={styles.competitionCard}><DateTile iso={nextCompetition.startsAt} locale={dateLocale}/><div className={styles.competitionContent}><div className={styles.competitionTitle}><span className={styles.typePill}><Flag size={13}/>{nextCompetition.type}</span><h3>{nextCompetition.title}</h3><p>{nextCompetition.organizer}</p></div><div className={styles.competitionMeta}><span><Clock3 size={15}/>{schedule(nextCompetition.startsAt,nextCompetition.endsAt,dateLocale)}</span><span><MapPin size={15}/>{nextCompetition.location}</span><span><Users size={15}/>{nextCompetition.category??tr("Catégorie personnelle","Personal category")}</span></div></div><button className={styles.secondaryButton} type="button" onClick={()=>setExpanded(expanded===nextCompetition.key?null:nextCompetition.key)}>{tr("Voir le détail","View details")}<ArrowRight size={15}/></button>{expanded===nextCompetition.key?<div className={styles.competitionDetail}>{nextCompetition.detail||tr("Toutes les informations disponibles figurent ci-dessus.","All available information is shown above.")}</div>:null}</article></section>:null}
    <section id="activities-calendar" className={styles.calendarSection}><div className={styles.controls}>
      <div className={styles.controlsHeading}><h2>{tr("Calendrier des activités","Activity calendar")}</h2></div>
      <div className={styles.filters}><Select label={tr("Type d’activité","Activity type")} value={typeFilter} onChange={setTypeFilter} options={[["all",tr("Tous les types","All types")],["training",tr("Entraînement","Training")],["club",tr("Entraînement club","Club training")],["individual",tr("Individuel","Individual")],["private",tr("Cours privé","Private lesson")],["competition",tr("Compétition","Competition")],["interclub","Interclub"],["camp",tr("Stage","Camp")],["session",tr("Réunion","Session")],["event",tr("Événement","Event")]]}/><Select label={tr("Statut","Status")} value={statusFilter} onChange={v=>setStatusFilter(v as StatusFilter)} options={[["all",tr("Tous les statuts","All statuses")],["upcoming",tr("À venir","Upcoming")],["past",tr("Passées","Past")],["evaluation",tr("À évaluer","To evaluate")],["completed",tr("Terminées","Completed")]]}/><Select label={tr("Participation","Participation")} value={participationFilter} onChange={v=>setParticipationFilter(v as ParticipationFilter)} options={[["all",tr("Toutes","All")],["present",tr("Présent","Present")],["absent",tr("Absent / excusé","Absent / excused")],["expected",tr("À confirmer","To confirm")]]}/></div>
      <div className={styles.controlFooter}><div className={styles.viewSwitch}>{(["season","month","week","day"] as CalendarView[]).map(v=><button key={v} type="button" className={view===v?styles.active:""} onClick={()=>changeView(v)}>{v==="season"?tr("Saison","Season"):v==="month"?tr("Mois","Month"):v==="week"?tr("Semaine","Week"):tr("Jour","Day")}</button>)}</div><div className={styles.periodNav}><button type="button" onClick={()=>move(-1)} aria-label={tr("Période précédente","Previous period")}><ChevronLeft size={17}/></button><button type="button" onClick={()=>setAnchor(new Date())}>{tr("Aujourd’hui","Today")}</button><button type="button" onClick={()=>move(1)} aria-label={tr("Période suivante","Next period")}><ChevronRight size={17}/></button></div></div>
    </div><div className={`${styles.agendaPanel} ${view==="season"?styles.seasonPanel:""}`}><div className={styles.agendaHeading}><h2>{periodLabel}</h2></div>{loading?<CalendarLoadingSkeleton label={tr("Chargement des activités…","Loading activities…")}/>:view==="season"?<SeasonOverview activities={visible} year={anchor.getFullYear()} dateLocale={dateLocale}/>:Object.keys(byDay).length===0?<div className={styles.empty}><CalendarDays size={22}/><strong>{tr("Aucune activité sur cette période","No activity in this period")}</strong><span>{tr("Modifiez les filtres ou consultez une autre période.","Change the filters or browse another period.")}</span></div>:<div className={styles.agenda}>{Object.entries(byDay).map(([day,items])=><ActivityDay key={day} date={new Date(`${day}T12:00:00`)} items={items} locale={locale} dateLocale={dateLocale} busyId={busyId} expanded={expanded} setExpanded={setExpanded} toggle={toggle}/>)}</div>}</div></section>
  </div></div>
}

function Heading({eyebrow,title,description}:{eyebrow:string;title:string;description?:string}){return <div className={styles.sectionHeading}><div><span className={styles.eyebrow}>{eyebrow}</span><h2>{title}</h2>{description?<p>{description}</p>:null}</div></div>}
function UpcomingStat({icon,label,value,counts}:{icon:React.ReactNode;label:string;value:number;counts:Array<[string,number]>}){return <article className={styles.statCard}><div className={styles.statTitle}><span className={styles.statIcon}>{icon}</span><h3>{label}</h3></div><strong>{value}</strong><div className={styles.typeCounts}>{counts.map(([type,count])=><span key={type}><b>{count}</b> {type}</span>)}</div></article>}
function AttendanceStat({icon,label,rate,present,expected,trend,locale}:{icon:React.ReactNode;label:string;rate:number|null;present:number;expected:number;trend?:number|null;locale:string}){const tr=(fr:string,en:string)=>pickLocaleText(locale,fr,en);return <article className={`${styles.statCard} ${styles.attendanceCard}`}><div className={styles.statTitle}><span className={styles.statIcon}>{icon}</span><h3>{label}</h3></div><div className={styles.attendanceProgress}><strong>{rate==null?"—":`${rate}%`}</strong><div className="bar" role="progressbar" aria-valuenow={rate??0} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${rate??0}%`}}/></div></div><span className={styles.attendanceRatio}>{present} {tr("activité","activity")}{present>1?"s":""} {tr("sur","out of")} {expected}</span><div className={styles.attendanceTags}>{trend!=null?trend>0?<span className={`${styles.attendanceTag} ${styles.positive}`}><TrendingUp size={12}/>+{trend} {tr("pts vs mois précédent","pts vs previous month")}</span>:trend<0?<span className={`${styles.attendanceTag} ${styles.caution}`}><TrendingDown size={12}/>−{Math.abs(trend)} {tr("pts vs mois précédent","pts vs previous month")}</span>:<span className={styles.attendanceTag}><ArrowRight size={12}/>{tr("Stable vs mois précédent","Stable vs previous month")}</span>:null}{rate===100&&expected>0?<span className={`${styles.attendanceTag} ${styles.positive}`}><CheckCircle2 size={12}/>{tr("Objectif atteint","Goal reached")}</span>:null}</div></article>}
function PlannerShortcut({active=false,icon,title,onClick}:{active?:boolean;icon:React.ReactNode;title:string;onClick:()=>void}){return <button type="button" className={`${styles.plannerShortcut} ${active?styles.plannerShortcutActive:""}`} onClick={onClick} aria-expanded={active}><span>{icon}</span><strong>{title}</strong><ArrowRight size={16}/></button>}
function CalendarLoadingSkeleton({label}:{label:string}){return <div className={styles.calendarSkeleton} aria-live="polite" aria-busy="true" aria-label={label}>{Array.from({length:3},(_,index)=><div className={styles.calendarSkeletonRow} key={index}><span className={styles.calendarSkeletonDate}/><div><span/><span/><span/></div><span className={styles.calendarSkeletonAction}/></div>)}</div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([id,text])=><option key={id} value={id}>{text}</option>)}</select></label>}
function DateTile({iso,locale}:{iso:string;locale:string}){return <ActivityDateTile startsAt={iso} locale={locale} className={styles.dateTile}/>}
function schedule(a:string,b:string,l:string){const x=new Date(a),y=new Date(b);const time=(d:Date)=>new Intl.DateTimeFormat(l,{hour:"2-digit",minute:"2-digit"}).format(d);return ymd(x)===ymd(y)?`${time(x)} – ${time(y)}`:`${new Intl.DateTimeFormat(l,{day:"numeric",month:"short"}).format(x)} – ${new Intl.DateTimeFormat(l,{day:"numeric",month:"short"}).format(y)}`}
function SeasonOverview({activities,year,dateLocale}:{activities:Activity[];year:number;dateLocale:string}){const weekdays=Array.from({length:7},(_,index)=>new Intl.DateTimeFormat(dateLocale,{weekday:"narrow"}).format(addDays(new Date(2024,0,1),index)));return <div className={styles.seasonMonths}>{Array.from({length:12},(_,month)=>{const monthActivities=activities.filter(a=>{const date=new Date(a.startsAt);return date.getFullYear()===year&&date.getMonth()===month});const byDate=monthActivities.reduce<Record<number,Activity[]>>((result,item)=>{const day=new Date(item.startsAt).getDate();(result[day]??=[]).push(item);return result},{});const offset=(new Date(year,month,1).getDay()+6)%7;const daysInMonth=new Date(year,month+1,0).getDate();return <section key={month} className={styles.seasonMonth}><h3>{cap(new Intl.DateTimeFormat(dateLocale,{month:"long"}).format(new Date(year,month,1)))}</h3><div className={styles.seasonWeekdays}>{weekdays.map((day,index)=><span key={`${day}-${index}`}>{day}</span>)}</div><div className={styles.seasonGrid}>{Array.from({length:daysInMonth},(_,index)=>{const day=index+1;const items=byDate[day]??[];const position=offset+index;const types=Array.from(new Set(items.map(item=>item.type)));return <article key={day} className={`${styles.seasonActivity} ${items.length===0?styles.seasonEmptyDay:""}`} style={{gridColumn:position%7+1,gridRow:Math.floor(position/7)+1}}><span className={styles.seasonDate}><b>{day}</b></span>{types.length?<div>{types.map(type=><span key={type}>{type}</span>)}</div>:null}</article>})}</div></section>})}</div>}
function ActivityDay({date,items,locale,dateLocale,busyId,expanded,setExpanded,toggle}:{date:Date;items:Activity[];locale:string;dateLocale:string;busyId:string;expanded:string|null;setExpanded:(v:string|null)=>void;toggle:(a:Activity)=>void}){const tr=(fr:string,en:string)=>pickLocaleText(locale,fr,en);return <article className={styles.dayCard}><DateTile iso={date.toISOString()} locale={dateLocale}/><div className={styles.dayActivities}>{items.map(a=>{const detailHref=a.session?`/player/golf/trainings/${a.session.id}`:null;const evalHref=a.session?`/player/golf/trainings/${a.session.id}/edit`:a.event?`/player/golf/trainings/new?club_event_id=${a.event.id}`:null;const open=expanded===a.key;return <div key={a.key} className={styles.activityRow}><div className={styles.time}><Clock3 size={14}/>{schedule(a.startsAt,a.endsAt,dateLocale)}</div><div className={styles.activityMain}><span className={styles.typePill}>{a.type}</span><h3>{a.title}</h3><p><span>{a.organizer}</span><span><MapPin size={13}/>{a.location}</span></p></div><div className={styles.activityAction}>{a.isFuture&&a.event&&!a.isCompetition?<AttendanceToggle variant="pill" checked={participation(a.attendance)!=="absent"} onToggle={()=>toggle(a)} disabled={busyId===a.id} disabledCursor="wait" ariaLabel={tr(`Présence pour ${a.title}`,`Attendance for ${a.title}`)} leftLabel={tr("Absent","Absent")} rightLabel={tr("Présent","Present")}/>:null}{a.isFuture&&a.isCompetition?<><span className={`${styles.status} ${styles.upcoming}`}>{tr("À venir","Upcoming")}</span><button type="button" className={styles.textButton} onClick={()=>setExpanded(open?null:a.key)}>{tr("Détails","Details")}<ArrowRight size={14}/></button></>:null}{a.needsEvaluation?<><span className={`${styles.status} ${styles.warning}`}><AlertCircle size={13}/>{tr("À évaluer","To evaluate")}</span>{evalHref?<Link className={styles.primaryButton} href={evalHref}>{tr("Évaluer","Evaluate")}</Link>:null}</>:null}{a.completed?<><span className={`${styles.status} ${styles.done}`}><Check size={13}/>{tr("Terminée","Completed")}</span>{detailHref?<Link className={styles.textButton} href={detailHref}>{tr("Détails","Details")}<ArrowRight size={14}/></Link>:null}</>:null}{a.isFuture&&!a.event&&!a.isCompetition&&detailHref?<Link className={styles.textButton} href={detailHref}>{tr("Détails","Details")}<ArrowRight size={14}/></Link>:null}</div>{open?<div className={styles.inlineDetail}>{a.category?<span><strong>{tr("Catégorie","Category")}</strong>{a.category}</span>:null}<span><strong>{tr("Horaire","Schedule")}</strong>{schedule(a.startsAt,a.endsAt,dateLocale)}</span><span><strong>{tr("Lieu","Location")}</strong>{a.location}</span>{a.detail?<p>{a.detail}</p>:null}</div>:null}</div>})}</div></article>}
