import { NextResponse, type NextRequest } from "next/server";
import { calculateActivityAndCoachHours, eventMinutes, isoWeekKey, median, percentage, PERFORMANCE_THRESHOLDS, round1 } from "@/lib/managerPerformance";
import { dateKey, performanceContext, queryRows, resolveRange, startIso } from "../_lib";

type MemberRow = { id: string; user_id: string; is_active: boolean; profiles: { first_name: string | null; last_name: string | null; staff_function: string | null; avatar_url: string | null } | null };
type ProfileRow = { id: string; first_name: string | null; last_name: string | null; staff_function: string | null; avatar_url: string | null };
type SeasonRecord = { club_member_id: string; registration_status: string };
type GroupRow = { id: string; name: string; head_coach_user_id: string | null };
type GroupCoach = { group_id: string; coach_user_id: string; is_head: boolean };
type GroupPlayer = { group_id: string; player_user_id: string };
type EventRow = { id: string; group_id: string | null; title: string; event_type: string | null; starts_at: string; ends_at: string | null; duration_minutes: number | null; status: string | null; requires_evaluation: boolean };
type EventCoach = { event_id: string; coach_id: string };
type Attendee = { event_id: string; player_id: string; status: string | null };
type Feedback = { event_id: string; player_id: string; coach_id: string; engagement: number | null; attitude: number | null; performance: number | null; visible_to_player: boolean };
type CampDay = { camp_id: string; event_id: string };
type CampCoach = { camp_id: string; coach_id: string };

const nameOf = (coach: MemberRow) => `${coach.profiles?.first_name ?? ""} ${coach.profiles?.last_name ?? ""}`.trim() || "Coach";

export async function GET(req: NextRequest, ctx: { params: Promise<{ clubId: string }> }) {
  try {
    const { clubId } = await ctx.params; const auth = await performanceContext(req, clubId);
    if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });
    const { range, previous, season, seasons } = await resolveRange(req, auth.db, clubId); const today = new Date().toISOString(); const futureTo = new Date(Date.now() + 60 * 86400000).toISOString();
    const [members, seasonRecords, groups, events] = await Promise.all([
      queryRows<MemberRow>(auth.db.from("club_members").select("id,user_id,is_active").eq("club_id", clubId).eq("role", "coach")),
      season ? queryRows<SeasonRecord>(auth.db.from("club_coach_season_records").select("club_member_id,registration_status").eq("club_season_id", season.id)) : Promise.resolve([]),
      queryRows<GroupRow>(auth.db.from("coach_groups").select("id,name,head_coach_user_id").eq("club_id", clubId).eq("club_season_id", season?.id ?? "00000000-0000-0000-0000-000000000000").eq("is_active", true)),
      queryRows<EventRow>(auth.db.from("club_events").select("id,group_id,title,event_type,starts_at,ends_at,duration_minutes,status,requires_evaluation").eq("club_id", clubId).gte("starts_at", startIso(previous.from)).lte("starts_at", futureTo).limit(15000)),
    ]);
    const coachIds = members.map((member) => member.user_id); const profiles = coachIds.length ? await queryRows<ProfileRow>(auth.db.from("profiles").select("id,first_name,last_name,staff_function,avatar_url").in("id", coachIds)) : []; const profileMap = new Map(profiles.map((profile) => [profile.id, profile])); for (const member of members) member.profiles = profileMap.get(member.user_id) ?? null; const eventIds = events.map((event) => event.id); const groupIds = groups.map((group) => group.id);
    const [groupCoaches, groupPlayers, eventCoaches, attendees, feedback, campDays] = await Promise.all([
      groupIds.length ? queryRows<GroupCoach>(auth.db.from("coach_group_coaches").select("group_id,coach_user_id,is_head").in("group_id", groupIds)) : Promise.resolve([]),
      groupIds.length ? queryRows<GroupPlayer>(auth.db.from("coach_group_players").select("group_id,player_user_id").in("group_id", groupIds)) : Promise.resolve([]),
      eventIds.length ? queryRows<EventCoach>(auth.db.from("club_event_coaches").select("event_id,coach_id").in("event_id", eventIds).limit(30000)) : Promise.resolve([]),
      eventIds.length ? queryRows<Attendee>(auth.db.from("club_event_attendees").select("event_id,player_id,status").in("event_id", eventIds).limit(50000)) : Promise.resolve([]),
      eventIds.length ? queryRows<Feedback>(auth.db.from("club_event_coach_feedback").select("event_id,player_id,coach_id,engagement,attitude,performance,visible_to_player").in("event_id", eventIds).limit(50000)) : Promise.resolve([]),
      eventIds.length ? queryRows<CampDay>(auth.db.from("club_camp_days").select("camp_id,event_id").in("event_id", eventIds)) : Promise.resolve([]),
    ]);
    const campIds = Array.from(new Set(campDays.map((day) => day.camp_id))); const campCoaches = campIds.length ? await queryRows<CampCoach>(auth.db.from("club_camp_coaches").select("camp_id,coach_id").in("camp_id", campIds)) : [];
    const seasonRecordMap = new Map(seasonRecords.map((record) => [record.club_member_id, record])); const eventMap = new Map(events.map((event) => [event.id, event])); const groupMap = new Map(groups.map((group) => [group.id, group])); const eventAssignments = new Map<string, string[]>(); for (const assignment of eventCoaches) eventAssignments.set(assignment.event_id, [...(eventAssignments.get(assignment.event_id) ?? []), assignment.coach_id]);
    const periodEnd = Math.min(Date.now(), new Date(`${range.to}T23:59:59Z`).getTime());
    const validCurrentEvents = events.filter((event) => dateKey(event.starts_at) >= range.from && dateKey(event.starts_at) <= range.to && event.status !== "cancelled" && new Date(event.ends_at ?? event.starts_at).getTime() <= periodEnd);
    const futureEvents = events.filter((event) => new Date(event.starts_at).getTime() > new Date(today).getTime() && new Date(event.starts_at).getTime() <= new Date(futureTo).getTime() && event.status !== "cancelled");
    const expectedOwner = (event: EventRow) => { const assigned = eventAssignments.get(event.id) ?? []; if (assigned.length === 1) return assigned[0]; const head = event.group_id ? groupMap.get(event.group_id)?.head_coach_user_id : null; return head && assigned.includes(head) ? head : null; };
    const coachRows = members.map((coach) => {
      const active = coach.is_active && (seasonRecordMap.get(coach.id)?.registration_status ?? "active") === "active"; const memberships = groupCoaches.filter((item) => item.coach_user_id === coach.user_id); const ownedGroups = groups.filter((group) => group.head_coach_user_id === coach.user_id || memberships.some((item) => item.group_id === group.id));
      const assignments = eventCoaches.filter((item) => item.coach_id === coach.user_id); const assignedIds = new Set(assignments.map((item) => item.event_id)); const currentEvents = validCurrentEvents.filter((event) => assignedIds.has(event.id)); const previousEvents = events.filter((event) => assignedIds.has(event.id) && dateKey(event.starts_at) >= previous.from && dateKey(event.starts_at) <= previous.to && event.status !== "cancelled");
      const currentMinutes = currentEvents.reduce((sum, event) => sum + eventMinutes({ startsAt: event.starts_at, endsAt: event.ends_at, durationMinutes: event.duration_minutes }), 0); const previousMinutes = previousEvents.reduce((sum, event) => sum + eventMinutes({ startsAt: event.starts_at, endsAt: event.ends_at, durationMinutes: event.duration_minutes }), 0);
      const currentEventIds = new Set(currentEvents.map((event) => event.id)); const attendeeRows = attendees.filter((item) => currentEventIds.has(item.event_id)); const players = new Set(attendeeRows.map((item) => item.player_id)); const groupSizes = currentEvents.map((event) => attendees.filter((item) => item.event_id === event.id && item.status !== "not_registered").length); const expectedEvents = currentEvents.filter((event) => event.requires_evaluation && expectedOwner(event) === coach.user_id); const expectedPairs = expectedEvents.flatMap((event) => attendees.filter((item) => item.event_id === event.id && item.status !== "absent" && item.status !== "excused" && item.status !== "not_registered").map((item) => `${event.id}|${item.player_id}`)); const completedPairs = new Set(feedback.filter((item) => item.coach_id === coach.user_id).map((item) => `${item.event_id}|${item.player_id}`)); const completeFeedback = feedback.filter((item) => item.coach_id === coach.user_id && currentEventIds.has(item.event_id) && item.engagement != null && item.attitude != null && item.performance != null); const partialFeedback = feedback.filter((item) => item.coach_id === coach.user_id && currentEventIds.has(item.event_id) && (item.engagement == null || item.attitude == null || item.performance == null)); const overdue = expectedPairs.filter((key) => { const event = eventMap.get(key.split("|")[0]); return event && Date.now() - new Date(event.starts_at).getTime() >= PERFORMANCE_THRESHOLDS.coachEvaluationOverdueDays * 86400000 && !completedPairs.has(key); });
      const headGroups = ownedGroups.filter((group) => group.head_coach_user_id === coach.user_id).length; const last = currentEvents.map((event) => event.starts_at).sort().at(-1) ?? null; const weeks = new Set(currentEvents.map((event) => isoWeekKey(event.starts_at))).size; const currentCampIds = new Set(campDays.filter((day) => currentEventIds.has(day.event_id)).map((day) => day.camp_id)); const camps = new Set(campCoaches.filter((item) => item.coach_id === coach.user_id && currentCampIds.has(item.camp_id)).map((item) => item.camp_id)).size;
      return { id: coach.user_id, memberId: coach.id, name: nameOf(coach), avatarUrl: coach.profiles?.avatar_url ?? null, function: coach.profiles?.staff_function ?? null, active, groups: ownedGroups.map((group) => ({ id: group.id, name: group.name, role: group.head_coach_user_id === coach.user_id ? "Responsable" : "Assistant", juniors: groupPlayers.filter((item) => item.group_id === group.id).length })), groupCount: ownedGroups.length, role: headGroups ? `${headGroups} responsable${headGroups > 1 ? "s" : ""}` : ownedGroups.length ? "Assistant" : "Sans groupe", activities: currentEvents.length, coachHours: round1(currentMinutes / 60), previousCoachHours: round1(previousMinutes / 60), uniquePlayers: players.size, medianGroupSize: median(groupSizes), activeWeeks: weeks, camps, evaluationsExpected: expectedPairs.length, evaluationsCompleted: expectedPairs.filter((key) => completedPairs.has(key)).length, evaluationsInProgress: partialFeedback.length, evaluationsOverdue: overdue.length, visibleFeedbackRate: percentage(completeFeedback.filter((item) => item.visible_to_player).length, completeFeedback.length), lastActivity: last, activityTypes: Array.from(new Set(currentEvents.map((event) => event.event_type).filter(Boolean))), evaluationTodo: overdue.slice(0, 20).map((key) => { const [eventId, playerId] = key.split("|"); return { eventId, playerId, eventTitle: eventMap.get(eventId)?.title ?? "Activité", reason: `Évaluation en retard de plus de ${PERFORMANCE_THRESHOLDS.coachEvaluationOverdueDays} jours` }; }) };
    });
    const filterGroup = req.nextUrl.searchParams.get("group") ?? "all"; const filterRole = req.nextUrl.searchParams.get("role") ?? "all"; const filterStatus = req.nextUrl.searchParams.get("status") ?? "active"; const requestedCoach = req.nextUrl.searchParams.get("coachId"); const rows = coachRows.filter((row) => (!requestedCoach || row.id === requestedCoach) && (filterGroup === "all" || row.groups.some((group) => group.id === filterGroup)) && (filterRole === "all" || (filterRole === "head" ? row.groups.some((group) => group.role === "Responsable") : row.groups.some((group) => group.role === "Assistant"))) && (filterStatus === "all" || (filterStatus === "active" ? row.active : !row.active)));
    if (requestedCoach && !rows.length) return NextResponse.json({ error: "Coach introuvable dans ce club." }, { status: 404 });
    const allCurrentAssignments = eventCoaches.filter((item) => validCurrentEvents.some((event) => event.id === item.event_id)); const hours = calculateActivityAndCoachHours(validCurrentEvents.map((event) => ({ id: event.id, startsAt: event.starts_at, endsAt: event.ends_at, durationMinutes: event.duration_minutes })), allCurrentAssignments.map((item) => ({ eventId: item.event_id, coachId: item.coach_id }))); const expected = rows.reduce((sum, row) => sum + row.evaluationsExpected, 0); const completed = rows.reduce((sum, row) => sum + row.evaluationsCompleted, 0);
    const groupsWithoutHead = groups.filter((group) => !group.head_coach_user_id).map((group) => ({ id: group.id, name: group.name })); const singleCoachGroups = groups.filter((group) => { const coaches = new Set(groupCoaches.filter((item) => item.group_id === group.id).map((item) => item.coach_user_id)); if (group.head_coach_user_id) coaches.add(group.head_coach_user_id); return coaches.size <= 1; }).map((group) => ({ id: group.id, name: group.name })); const futureWithoutCoach = futureEvents.filter((event) => !(eventAssignments.get(event.id)?.length)).map((event) => ({ id: event.id, title: event.title, startsAt: event.starts_at })); const pendingAttendance = attendees.filter((item) => { const event = eventMap.get(item.event_id); return event && dateKey(event.starts_at) >= range.from && dateKey(event.starts_at) <= range.to && item.status === "expected"; }).length;
    const clubMedianHours = median(rows.map((row) => row.coachHours)); const attention = [...futureWithoutCoach.map((event) => ({ type: "future-no-coach", reason: "Activité future sans coach explicite", label: event.title, value: event.startsAt, href: "/manager/calendar" })), ...groupsWithoutHead.map((group) => ({ type: "group-no-head", reason: "Groupe sans responsable principal", label: group.name, value: "Responsable à définir", href: `/manager/groups/${group.id}` })), ...rows.filter((row) => row.evaluationsOverdue).map((row) => ({ type: "evaluation", reason: "Évaluations en retard", label: row.name, value: String(row.evaluationsOverdue), href: `/manager/user-management/coaches/${row.memberId}?club=${clubId}&season=${season?.id ?? ""}&tab=statistics` })), ...rows.filter((row) => clubMedianHours != null && (row.coachHours > clubMedianHours * 1.75 || (clubMedianHours > 0 && row.coachHours < clubMedianHours * 0.25))).map((row) => ({ type: "load", reason: "Charge éloignée de la médiane", label: row.name, value: `${row.coachHours} h · médiane ${clubMedianHours} h`, href: `/manager/user-management/coaches/${row.memberId}?club=${clubId}&season=${season?.id ?? ""}&tab=statistics` }))];
    const chartEvents = requestedCoach ? validCurrentEvents.filter((event) => eventAssignments.get(event.id)?.includes(requestedCoach)) : validCurrentEvents; const monthly = Array.from(new Set(chartEvents.map((event) => event.starts_at.slice(0, 7)))).sort().map((month) => { const monthEvents = chartEvents.filter((event) => event.starts_at.startsWith(month)); const monthAssignments = allCurrentAssignments.filter((item) => monthEvents.some((event) => event.id === item.event_id) && (!requestedCoach || item.coach_id === requestedCoach)); const value = calculateActivityAndCoachHours(monthEvents.map((event) => ({ id: event.id, startsAt: event.starts_at, endsAt: event.ends_at, durationMinutes: event.duration_minutes })), monthAssignments.map((item) => ({ eventId: item.event_id, coachId: item.coach_id }))); return { month, activities: monthEvents.length, ...value }; });
    return NextResponse.json({ generatedAt: new Date().toISOString(), clubId, range, previous, season, seasons, filters: { groups }, overview: { activeCoaches: rows.filter((row) => row.active).length, activities: validCurrentEvents.length, activityHours: hours.activityHours, coachHours: hours.coachHours, medianPlayers: median(rows.map((row) => row.uniquePlayers)), coverageRate: percentage(validCurrentEvents.filter((event) => eventAssignments.get(event.id)?.length).length, validCurrentEvents.length), evaluationCompletionRate: percentage(completed, expected), pendingAttendance }, distribution: { medianCoachHours: clubMedianHours, monthly }, coverage: { groupsWithoutHead, singleCoachGroups, futureWithoutCoach }, evaluations: { expected, completed, overdue: rows.reduce((sum, row) => sum + row.evaluationsOverdue, 0), completionRate: percentage(completed, expected) }, rows, attention, coach: requestedCoach ? rows[0] : null });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Erreur serveur." }, { status: 500 }); }
}
