-- Read-only. Every row must return ok=true after applying batch 3.
select '01 junior invitation kind' as check_name, exists(select 1 from pg_constraint where conrelid='public.access_invitation_tokens'::regclass and conname='access_invitation_tokens_kind_check' and pg_get_constraintdef(oid) like '%junior_access%' and pg_get_constraintdef(oid) like '%account_recovery%') as ok
union all select '02 invitation recipient', exists(select 1 from information_schema.columns where table_schema='public' and table_name='access_invitation_tokens' and column_name='recipient_user_id')
union all select '03 invitation RLS', relrowsecurity from pg_class where oid='public.access_invitation_tokens'::regclass
union all select '04 invitation private', not has_table_privilege('authenticated','public.access_invitation_tokens','SELECT,INSERT,UPDATE,DELETE') and not has_table_privilege('anon','public.access_invitation_tokens','SELECT,INSERT,UPDATE,DELETE')
union all select '05 invitation claim private', not has_function_privilege('authenticated','public.claim_access_invitation_v1(text,boolean)','EXECUTE') and not has_function_privilege('anon','public.claim_access_invitation_v1(text,boolean)','EXECUTE')
union all select '06 invitation claim server', has_function_privilege('service_role','public.claim_access_invitation_v1(text,boolean)','EXECUTE')
union all select '07 delivery RLS', relrowsecurity from pg_class where oid='public.club_news_email_deliveries'::regclass
union all select '08 delivery private', not has_table_privilege('authenticated','public.club_news_email_deliveries','SELECT,INSERT,UPDATE,DELETE') and not has_table_privilege('anon','public.club_news_email_deliveries','SELECT,INSERT,UPDATE,DELETE')
union all select '09 delivery unique recipient', exists(select 1 from pg_constraint where conrelid='public.club_news_email_deliveries'::regclass and contype='p' and pg_get_constraintdef(oid)='PRIMARY KEY (news_id, recipient_user_id)')
union all select '10 delivery claim private', not has_function_privilege('authenticated','public.claim_manager_news_email_v1(uuid,uuid,uuid,uuid,text)','EXECUTE') and not has_function_privilege('anon','public.claim_manager_news_email_v1(uuid,uuid,uuid,uuid,text)','EXECUTE')
union all select '11 delivery finish private', not has_function_privilege('authenticated','public.finish_manager_news_email_v1(uuid,uuid,uuid,uuid,uuid,text,text)','EXECUTE') and not has_function_privilege('anon','public.finish_manager_news_email_v1(uuid,uuid,uuid,uuid,uuid,text,text)','EXECUTE')
union all select '12 delivery server functions', has_function_privilege('service_role','public.claim_manager_news_email_v1(uuid,uuid,uuid,uuid,text)','EXECUTE') and has_function_privilege('service_role','public.finish_manager_news_email_v1(uuid,uuid,uuid,uuid,uuid,text,text)','EXECUTE')
union all select '13 protected function paths', count(*)=3 and bool_and(prosecdef and proconfig @> array['search_path=public, pg_temp']) from pg_proc where oid in ('public.claim_access_invitation_v1(text,boolean)'::regprocedure,'public.claim_manager_news_email_v1(uuid,uuid,uuid,uuid,text)'::regprocedure,'public.finish_manager_news_email_v1(uuid,uuid,uuid,uuid,uuid,text,text)'::regprocedure)
union all select '14 delivery statuses', exists(select 1 from pg_constraint where conrelid='public.club_news_email_deliveries'::regclass and contype='c' and pg_get_constraintdef(oid) like '%uncertain%')
order by check_name;
