import type { AppLocale } from "@/lib/i18n/messages";

export type HelpBlock = {
  heading?: string;
  paragraphs?: string[];
  bullets?: string[];
  ordered?: string[];
};

export type HelpSection = {
  id: string;
  title: string;
  intro?: string;
  blocks: HelpBlock[];
};

type TranslatedLocale = Exclude<AppLocale, "fr">;

export const localizedHelpSections: Record<TranslatedLocale, HelpSection[]> = {
  en: [
    { id: "intro", title: "ActiviTee – Junior Golf Platform", intro: "Organize. Track. Develop.", blocks: [{ paragraphs: ["ActiviTee brings together the junior’s club schedule, personal golf activity and progress. Players, parents and coaches share one clear view while keeping their own responsibilities."], bullets: ["Organization of club and personal activities", "Tracking of training, rounds and progress", "Support for a more independent approach to golf"] }] },
    { id: "consentements", title: "Consent", blocks: [{ paragraphs: ["Most players are minors. A parent or legal representative must therefore approve the required consents before the junior account can be used. The club remains responsible for account administration and can explain how consent may be withdrawn."], bullets: ["Use of the platform and activation of the junior account", "Recording and monitoring sports activity", "Access for the linked parent or legal representative"] }] },
    { id: "installation", title: "Install ActiviTee", blocks: [{ heading: "iPhone and iPad", ordered: ["Open ActiviTee in Safari.", "Tap Share.", "Choose Add to Home Screen, then confirm."] }, { heading: "Android", ordered: ["Open ActiviTee in Chrome.", "Open the browser menu.", "Choose Install app or Add to Home screen, then confirm."] }] },
    { id: "notifications", title: "Notifications", blocks: [{ paragraphs: ["Notifications can announce new or changed activities, cancellations, evaluations and reminders. Open the bell, then notification settings, to choose the channels you want. Push notifications require the installed PWA and permission from the phone." ] }] },
    { id: "activites", title: "How activities work", blocks: [{ paragraphs: ["Club activities are created by the club or coaching team. Personal activities are entered by the player. Use My activities to review dates, attendance and evaluations."], bullets: ["Club: training sessions, interclubs, camps and group events", "Personal: competitions, individual training, private lessons and camps"] }] },
    { id: "performance", title: "Performance mode", blocks: [{ paragraphs: ["The club can activate Performance mode for juniors whose programme requires more detailed monitoring. It adds training structure, feelings, rounds, statistics, coach evaluations and the order of merit. The club decides when this mode is appropriate."] }] },
    { id: "evaluation-coachs", title: "Coach evaluations", blocks: [{ paragraphs: ["After a club session, the coach may assess engagement, attitude and application, together with club-specific criteria. These observations help the player understand what is progressing and what to work on next."] }] },
    { id: "volume", title: "Training volume", blocks: [{ paragraphs: ["Training volume combines the duration of documented sessions and compares it with the FTEM objective configured for the player. Enter activities consistently so weekly and monthly trends remain meaningful."] }] },
    { id: "page-accueil", title: "Page • Home", blocks: [{ paragraphs: ["Home summarizes upcoming activities, club news, items requiring attention, validations, attendance, training volume and recent marketplace listings. Use the shortcuts on each card to open the corresponding detail."] }] },
    { id: "page-mon-activite", title: "Page • My activities", blocks: [{ paragraphs: ["This page combines the club programme with personal activities. Filter the list, confirm attendance when requested, open an activity for details and add personal training, competitions or camps when available."] }] },
    { id: "page-a-completer", title: "Page • Activities to evaluate", blocks: [{ paragraphs: ["Past sessions that still require player feedback appear here. Open an item, enter the completed structure and your feelings, then save. Activities marked absent or excused do not require a player evaluation."] }] },
    { id: "dashboard", title: "Page • My golf dashboard", blocks: [{ paragraphs: ["The dashboard brings together training volume, feelings, coach feedback, rounds and playing indicators for the selected period. Charts describe the data recorded in ActiviTee; they are not medical or performance predictions."] }] },
    { id: "mes-parcours", title: "Page • My rounds", blocks: [{ paragraphs: ["Review saved rounds, scorecards and the main playing indicators. A complete hole-by-hole entry makes fairways, greens, putting and score trends more useful."] }] },
    { id: "ajouter-parcours", title: "Page • Add a round", blocks: [{ paragraphs: ["Choose the date, handicap and round type, then search for the course and tee. For a manual course, enter the required rating and par information. Save the setup before completing the scorecard hole by hole."] }] },
    { id: "ordre-merite", title: "Order of merit", blocks: [{ paragraphs: ["When Performance mode is enabled, the order of merit summarizes results and participation according to the rules configured by the organization. Gross and net rankings may use competition results, attendance and eligible bonuses. The displayed season and eligibility rules apply."] }] },
    { id: "marketplace", title: "Marketplace", blocks: [{ paragraphs: ["The marketplace is limited to the player’s clubs. Browse active listings, open a listing for contact details, and manage your own listings from My listings. Do not publish sensitive information in the description or photos."] }] },
    { id: "profil", title: "Page • My profile", blocks: [{ paragraphs: ["Keep identity, contact details, handicap and profile photo up to date. Some fields are managed by the club or are visible only when the organization enables them. A linked parent can switch between authorized children from the Player menu."] }] },
  ],
  de: [
    { id: "intro", title: "ActiviTee – Junior-Golf-Plattform", intro: "Organisieren. Verfolgen. Entwickeln.", blocks: [{ paragraphs: ["ActiviTee bündelt Clubprogramm, persönliche Golfaktivitäten und Entwicklung eines Juniors. Spieler, Eltern und Trainer arbeiten mit einer gemeinsamen, klaren Übersicht und behalten ihre jeweiligen Aufgaben."], bullets: ["Organisation von Club- und persönlichen Aktivitäten", "Erfassung von Training, Runden und Entwicklung", "Unterstützung eines selbstständigeren Golfwegs"] }] },
    { id: "consentements", title: "Einwilligungen", blocks: [{ paragraphs: ["Die meisten Spieler sind minderjährig. Deshalb muss ein Elternteil oder eine gesetzliche Vertretung die erforderlichen Einwilligungen bestätigen, bevor das Junior-Konto genutzt werden kann. Der Club bleibt für die Kontoverwaltung verantwortlich."], bullets: ["Nutzung der Plattform und Aktivierung des Junior-Kontos", "Erfassung und Auswertung sportlicher Aktivitäten", "Zugriff für verknüpfte Eltern oder gesetzliche Vertretungen"] }] },
    { id: "installation", title: "ActiviTee installieren", blocks: [{ heading: "iPhone und iPad", ordered: ["ActiviTee in Safari öffnen.", "Auf Teilen tippen.", "Zum Home-Bildschirm wählen und bestätigen."] }, { heading: "Android", ordered: ["ActiviTee in Chrome öffnen.", "Das Browsermenü öffnen.", "App installieren oder Zum Startbildschirm hinzufügen wählen und bestätigen."] }] },
    { id: "notifications", title: "Benachrichtigungen", blocks: [{ paragraphs: ["Benachrichtigungen informieren über neue oder geänderte Aktivitäten, Absagen, Bewertungen und Erinnerungen. Über die Glocke und die Benachrichtigungseinstellungen lassen sich die gewünschten Kanäle wählen. Push-Mitteilungen benötigen die installierte PWA und die Freigabe des Telefons."] }] },
    { id: "activites", title: "So funktionieren Aktivitäten", blocks: [{ paragraphs: ["Clubaktivitäten werden vom Club oder Trainerteam erstellt. Persönliche Aktivitäten erfasst der Spieler. Unter Meine Aktivitäten werden Termine, Anwesenheit und Bewertungen angezeigt."], bullets: ["Club: Trainings, Interclubs, Camps und Gruppenveranstaltungen", "Persönlich: Wettkämpfe, individuelles Training, Privatlektionen und Camps"] }] },
    { id: "performance", title: "Performance-Modus", blocks: [{ paragraphs: ["Der Club kann den Performance-Modus für Juniors aktivieren, deren Programm eine detailliertere Begleitung benötigt. Er ergänzt Trainingsstruktur, Empfindungen, Runden, Statistiken, Trainerbewertungen und die Rangliste. Der Club entscheidet über die Aktivierung."] }] },
    { id: "evaluation-coachs", title: "Trainerbewertungen", blocks: [{ paragraphs: ["Nach einem Clubtraining kann der Trainer Engagement, Haltung und Umsetzung sowie clubspezifische Kriterien bewerten. Diese Rückmeldungen zeigen, was sich entwickelt und woran als Nächstes gearbeitet werden kann."] }] },
    { id: "volume", title: "Trainingsumfang", blocks: [{ paragraphs: ["Der Trainingsumfang kombiniert die Dauer dokumentierter Einheiten und vergleicht sie mit dem FTEM-Ziel des Spielers. Aktivitäten sollten regelmässig erfasst werden, damit Wochen- und Monatstrends aussagekräftig bleiben."] }] },
    { id: "page-accueil", title: "Seite • Startseite", blocks: [{ paragraphs: ["Die Startseite fasst kommende Aktivitäten, Clubnews, offene Punkte, Validierungen, Anwesenheit, Trainingsumfang und neue Marktplatzanzeigen zusammen. Jede Karte führt zur passenden Detailansicht."] }] },
    { id: "page-mon-activite", title: "Seite • Meine Aktivitäten", blocks: [{ paragraphs: ["Diese Seite verbindet das Clubprogramm mit persönlichen Aktivitäten. Die Liste kann gefiltert werden; wenn verlangt, lässt sich die Anwesenheit bestätigen. Details und persönliche Trainings, Wettkämpfe oder Camps werden hier geöffnet beziehungsweise hinzugefügt."] }] },
    { id: "page-a-completer", title: "Seite • Zu bewertende Aktivitäten", blocks: [{ paragraphs: ["Vergangene Einheiten mit ausstehender Rückmeldung erscheinen hier. Aktivität öffnen, ausgeführte Struktur und Empfindungen eintragen und speichern. Bei Abwesenheit oder Entschuldigung ist keine Spielerbewertung nötig."] }] },
    { id: "dashboard", title: "Seite • Mein Golf – Übersicht", blocks: [{ paragraphs: ["Die Übersicht verbindet Trainingsumfang, Empfindungen, Trainerrückmeldungen, Runden und Spielindikatoren für den gewählten Zeitraum. Diagramme beschreiben die in ActiviTee erfassten Daten; sie sind keine medizinischen oder sportlichen Prognosen."] }] },
    { id: "mes-parcours", title: "Seite • Meine Runden", blocks: [{ paragraphs: ["Gespeicherte Runden, Scorekarten und die wichtigsten Spielindikatoren werden hier angezeigt. Eine vollständige Loch-für-Loch-Erfassung verbessert die Auswertung von Fairways, Greens, Putts und Scoreentwicklung."] }] },
    { id: "ajouter-parcours", title: "Seite • Runde hinzufügen", blocks: [{ paragraphs: ["Datum, Handicap und Rundentyp wählen, danach Platz und Abschlag suchen. Bei einem manuellen Platz müssen Rating und Par erfasst werden. Zuerst die Konfiguration speichern, anschliessend die Scorekarte Loch für Loch ausfüllen."] }] },
    { id: "ordre-merite", title: "Rangliste", blocks: [{ paragraphs: ["Bei aktiviertem Performance-Modus fasst die Rangliste Ergebnisse und Teilnahme nach den Regeln der Organisation zusammen. Brutto- und Nettowertung können Wettkampfergebnisse, Anwesenheit und berechtigte Boni berücksichtigen. Es gelten die angezeigte Saison und Teilnahmebedingungen."] }] },
    { id: "marketplace", title: "Marktplatz", blocks: [{ paragraphs: ["Der Marktplatz ist auf die Clubs des Spielers beschränkt. Aktive Anzeigen können durchsucht und für Kontaktdaten geöffnet werden; eigene Anzeigen werden unter Meine Anzeigen verwaltet. Keine sensiblen Daten in Texten oder Bildern veröffentlichen."] }] },
    { id: "profil", title: "Seite • Mein Profil", blocks: [{ paragraphs: ["Identität, Kontaktdaten, Handicap und Profilfoto sollten aktuell bleiben. Einige Felder verwaltet der Club oder zeigt sie nur nach Freigabe an. Verknüpfte Eltern können im Player-Menü zwischen berechtigten Kindern wechseln."] }] },
  ],
  it: [
    { id: "intro", title: "ActiviTee – Piattaforma golf junior", intro: "Organizzare. Seguire. Crescere.", blocks: [{ paragraphs: ["ActiviTee riunisce il programma del club, le attività personali e i progressi del giovane golfista. Giocatori, genitori e coach condividono una visione chiara, mantenendo responsabilità distinte."], bullets: ["Organizzazione delle attività del club e personali", "Monitoraggio di allenamenti, percorsi e progressi", "Sostegno a un percorso golfistico più autonomo"] }] },
    { id: "consentements", title: "Consensi", blocks: [{ paragraphs: ["La maggior parte dei giocatori è minorenne. Un genitore o rappresentante legale deve quindi approvare i consensi richiesti prima dell’uso dell’account junior. Il club resta responsabile della gestione degli account."], bullets: ["Uso della piattaforma e attivazione dell’account junior", "Registrazione e monitoraggio dell’attività sportiva", "Accesso per il genitore o rappresentante legale collegato"] }] },
    { id: "installation", title: "Installare ActiviTee", blocks: [{ heading: "iPhone e iPad", ordered: ["Apri ActiviTee in Safari.", "Tocca Condividi.", "Scegli Aggiungi alla schermata Home e conferma."] }, { heading: "Android", ordered: ["Apri ActiviTee in Chrome.", "Apri il menu del browser.", "Scegli Installa app o Aggiungi alla schermata Home e conferma."] }] },
    { id: "notifications", title: "Notifiche", blocks: [{ paragraphs: ["Le notifiche possono segnalare attività nuove o modificate, annullamenti, valutazioni e promemoria. Apri la campana e poi le impostazioni delle notifiche per scegliere i canali. Le notifiche push richiedono la PWA installata e l’autorizzazione del telefono."] }] },
    { id: "activites", title: "Come funzionano le attività", blocks: [{ paragraphs: ["Le attività del club sono create dal club o dal team di coach. Le attività personali sono inserite dal giocatore. Le mie attività permette di consultare date, presenze e valutazioni."], bullets: ["Club: allenamenti, interclub, stage e attività di gruppo", "Personali: gare, allenamenti individuali, lezioni private e stage"] }] },
    { id: "performance", title: "Modalità Performance", blocks: [{ paragraphs: ["Il club può attivare la modalità Performance per i junior che richiedono un monitoraggio più dettagliato. Aggiunge struttura degli allenamenti, sensazioni, percorsi, statistiche, valutazioni dei coach e ordine di merito. Il club decide quando attivarla."] }] },
    { id: "evaluation-coachs", title: "Valutazioni dei coach", blocks: [{ paragraphs: ["Dopo un allenamento del club, il coach può valutare impegno, atteggiamento e applicazione, insieme ai criteri specifici del club. Questi riscontri aiutano a capire i progressi e il prossimo obiettivo di lavoro."] }] },
    { id: "volume", title: "Volume di allenamento", blocks: [{ paragraphs: ["Il volume di allenamento somma la durata delle sessioni documentate e la confronta con l’obiettivo FTEM del giocatore. Registra le attività con regolarità per mantenere significative le tendenze settimanali e mensili."] }] },
    { id: "page-accueil", title: "Pagina • Home", blocks: [{ paragraphs: ["La Home riassume prossime attività, notizie del club, elementi da controllare, validazioni, presenze, volume di allenamento e annunci recenti. Ogni scheda apre il dettaglio corrispondente."] }] },
    { id: "page-mon-activite", title: "Pagina • Le mie attività", blocks: [{ paragraphs: ["Questa pagina unisce il programma del club e le attività personali. Filtra l’elenco, conferma la presenza quando richiesto, apri i dettagli e aggiungi allenamenti, gare o stage personali quando disponibili."] }] },
    { id: "page-a-completer", title: "Pagina • Attività da valutare", blocks: [{ paragraphs: ["Le sessioni concluse che richiedono ancora un riscontro appaiono qui. Apri l’attività, inserisci la struttura svolta e le sensazioni, quindi salva. Le attività segnate come assenza o giustificate non richiedono una valutazione del giocatore."] }] },
    { id: "dashboard", title: "Pagina • Il mio golf – Panoramica", blocks: [{ paragraphs: ["La panoramica riunisce volume di allenamento, sensazioni, riscontri dei coach, percorsi e indicatori di gioco per il periodo scelto. I grafici descrivono i dati registrati in ActiviTee; non sono previsioni mediche o di prestazione."] }] },
    { id: "mes-parcours", title: "Pagina • I miei percorsi", blocks: [{ paragraphs: ["Consulta percorsi salvati, scorecard e principali indicatori di gioco. Una registrazione completa buca per buca rende più utili le tendenze di fairway, green, putt e punteggio."] }] },
    { id: "ajouter-parcours", title: "Pagina • Aggiungi un percorso", blocks: [{ paragraphs: ["Scegli data, handicap e tipo di percorso, poi cerca campo e tee. Per un campo manuale inserisci rating e par richiesti. Salva la configurazione prima di completare la scorecard buca per buca."] }] },
    { id: "ordre-merite", title: "Ordine di merito", blocks: [{ paragraphs: ["Con la modalità Performance attiva, l’ordine di merito riassume risultati e partecipazione secondo le regole dell’organizzazione. Le classifiche lordo e netto possono includere risultati di gara, presenze e bonus ammessi. Valgono la stagione e i criteri mostrati."] }] },
    { id: "marketplace", title: "Marketplace", blocks: [{ paragraphs: ["Il marketplace è limitato ai club del giocatore. Sfoglia gli annunci attivi, aprili per i contatti e gestisci i tuoi da I miei annunci. Non pubblicare informazioni sensibili nelle descrizioni o nelle foto."] }] },
    { id: "profil", title: "Pagina • Il mio profilo", blocks: [{ paragraphs: ["Mantieni aggiornati identità, contatti, handicap e foto profilo. Alcuni campi sono gestiti dal club o visibili solo se l’organizzazione li abilita. Un genitore collegato può passare tra i figli autorizzati dal menu Player."] }] },
  ],
};
