import { NextResponse, type NextRequest } from "next/server";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { cleanFamilyEmail, defaultFamilyMailConfig, renderFamilyTemplate } from "@/lib/familyAccess";
import { deliveryGroupKey, nextReportDate, periodLabel, previousCivilPeriod, type ReportFrequency } from "@/lib/periodicReports";
import { buildPeriodicReportContent } from "@/lib/periodicReportContent";

export const runtime = "nodejs";
function authorized(req: NextRequest) { const expected = process.env.CRON_SECRET; return Boolean(expected && (req.headers.get("authorization") === `Bearer ${expected}` || req.nextUrl.searchParams.get("secret") === expected)); }
function appUrl() { return String(process.env.APP_URL || process.env.NEXT_PUBLIC_APP_URL || "https://www.activitee.golf").replace(/\/+$/, ""); }
type ConfigRow = { club_id: string; player_user_id: string; frequency: ReportFrequency; send_day: number; next_send_at: string; locale: string; recipient_user_ids: string[]; sections?: Record<string, boolean>; coach_priority?: string | null; coach_objective?: string | null; coach_encouragement?: string | null; coach_comment?: string | null };
type Group = { config: ConfigRow; recipientId: string; rows: ConfigRow[]; period: { from: string; to: string } };
type ProcessResult = { recipient: string; status: "sent" | "skipped" | "failed"; reports?: number; error?: string };
async function authEmails(db: SupabaseClient, ids: string[]) { const wanted = new Set(ids); const result = new Map<string, string>(); for (let page = 1; wanted.size && page <= 20; page += 1) { const response = await db.auth.admin.listUsers({ page, perPage: 1000 }); if (response.error) throw response.error; for (const user of response.data.users) { const email = cleanFamilyEmail(user.email); if (wanted.has(user.id) && email) { result.set(user.id, email); wanted.delete(user.id); } } if (response.data.users.length < 1000) break; } return result; }
async function send(to: string, subject: string, body: string) { const transport = process.env.PERIODIC_REPORT_TRANSPORT || (process.env.NODE_ENV === "production" ? "brevo" : "mock"); if (transport === "mock") return `mock-${crypto.randomUUID()}`; const from = String(process.env.MAIL_FROM || "ActiviTee <noreply@activitee.golf>"); const match = from.match(/^(.+?)\s*<([^>]+)>$/); const sender = match ? { name: match[1].trim(), email: match[2].trim() } : { name: "ActiviTee", email: from }; const response = await fetch("https://api.brevo.com/v3/smtp/email", { method: "POST", headers: { "api-key": String(process.env.BREVO_API_KEY ?? ""), "Content-Type": "application/json" }, body: JSON.stringify({ sender, to: [{ email: to }], subject, textContent: body }) }); const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(String(json.message ?? "Échec de l’envoi")); return String(json.messageId ?? "brevo"); }

export async function GET(req: NextRequest) {
  if (!authorized(req)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) return NextResponse.json({ error: "Supabase environment missing" }, { status: 500 }); const db = createClient(url, key, { auth: { persistSession: false } }); const now = new Date();
  const due = await db.from("player_periodic_report_configs").select("*").eq("is_enabled", true).lte("next_send_at", now.toISOString()).limit(500); if (due.error) return NextResponse.json({ error: due.error.message }, { status: 500 });
  const configs = (due.data ?? []) as ConfigRow[]; const emailMap = await authEmails(db, Array.from(new Set(configs.flatMap((row) => row.recipient_user_ids ?? [])))); const groups = new Map<string, Group>();
  for (const config of configs) { const frequency = config.frequency as ReportFrequency; const period = previousCivilPeriod(frequency, now); for (const recipientId of config.recipient_user_ids ?? []) { if (!emailMap.has(recipientId)) continue; const keyValue = `${config.club_id}|${deliveryGroupKey({ recipientId, frequency, period, sendAt: config.next_send_at, locale: config.locale })}`; const group = groups.get(keyValue) ?? { config, recipientId, rows: [], period }; group.rows.push(config); groups.set(keyValue, group); } }
  const results: ProcessResult[] = [];
  for (const group of groups.values()) { try { const existing = await db.from("player_periodic_report_deliveries").select("id,status,attempt_count").eq("club_id", group.config.club_id).eq("recipient_user_id", group.recipientId).eq("period_from", group.period.from).eq("period_to", group.period.to).eq("locale", group.config.locale).eq("delivery_mode", "automatic").maybeSingle(); if (existing.data?.status === "sent") { results.push({ recipient: group.recipientId, status: "skipped" }); continue; }
      const contents = await Promise.all(group.rows.map((row) => buildPeriodicReportContent(db, { ...row, frequency: row.frequency as ReportFrequency }, group.period))); const reportIds: string[] = []; for (let index = 0; index < group.rows.length; index += 1) { const row = group.rows[index]; const content = contents[index]; const report = await db.from("player_periodic_reports").upsert({ club_id: row.club_id, player_user_id: row.player_user_id, period_from: group.period.from, period_to: group.period.to, period_label: content.periodLabel, statistics_snapshot: content, published_content: content, personalized_comment: row.coach_comment, generated_at: now.toISOString() }, { onConflict: "club_id,player_user_id,period_from,period_to" }).select("id").single(); if (report.error) throw new Error(report.error.message); reportIds.push(report.data.id); }
      const pendingPayload = { club_id: group.config.club_id, recipient_user_id: group.recipientId, report_ids: reportIds, player_user_ids: group.rows.map((row) => row.player_user_id), period_from: group.period.from, period_to: group.period.to, locale: group.config.locale, delivery_mode: "automatic", status: "pending", attempt_count: Number(existing.data?.attempt_count ?? 0) + 1, error_message: null };
      const pending = existing.data ? await db.from("player_periodic_report_deliveries").update(pendingPayload).eq("id", existing.data.id).select("id").single() : await db.from("player_periodic_report_deliveries").insert(pendingPayload).select("id").single(); if (pending.error) throw new Error(pending.error.message);
      try {
        const templateResult = await db.from("club_access_invitation_mail_configs").select("periodic_report_subject,periodic_report_body").eq("club_id", group.config.club_id).maybeSingle(); const defaults = defaultFamilyMailConfig(); const juniorNames = contents.map((item) => item.playerName).join(", "); const summary = contents.map((item) => item.summary).join("\n"); const variables = { club_name: contents[0]?.clubName ?? "Club", parent_name: "Parent", period_label: contents[0]?.periodLabel ?? periodLabel(group.period), junior_names: juniorNames, summary, report_url: `${appUrl()}/parent/report-deliveries/${pending.data.id}` }; const subject = renderFamilyTemplate(templateResult.data?.periodic_report_subject ?? defaults.periodic_report_subject, variables); const body = renderFamilyTemplate(templateResult.data?.periodic_report_body ?? defaults.periodic_report_body, variables); const providerId = await send(emailMap.get(group.recipientId)!, subject, body);
        const delivery = await db.from("player_periodic_report_deliveries").update({ status: "sent", provider_message_id: providerId, sent_at: now.toISOString(), error_message: null }).eq("id", pending.data.id); if (delivery.error) throw new Error(delivery.error.message);
      } catch (error) {
        await db.from("player_periodic_report_deliveries").update({ status: "failed", error_message: error instanceof Error ? error.message : "Échec de l’envoi" }).eq("id", pending.data.id);
        throw error;
      }
      for (const row of group.rows) await db.from("player_periodic_report_configs").update({ last_sent_at: now.toISOString(), last_status: "sent", next_send_at: nextReportDate(row.frequency, row.send_day, now), updated_at: now.toISOString() }).eq("club_id", row.club_id).eq("player_user_id", row.player_user_id); results.push({ recipient: group.recipientId, status: "sent", reports: reportIds.length });
    } catch (error) { results.push({ recipient: group.recipientId, status: "failed", error: error instanceof Error ? error.message : "failed" }); for (const row of group.rows) await db.from("player_periodic_report_configs").update({ last_status: "failed", updated_at: now.toISOString() }).eq("club_id", row.club_id).eq("player_user_id", row.player_user_id); } }
  return NextResponse.json({ processed: results.length, sent: results.filter((row) => row.status === "sent").length, failed: results.filter((row) => row.status === "failed").length, results });
}
