const fr = {
  admin: "Administration", title: "Étiquette & esprit du jeu", management: "Gestion de l’étiquette & de l’esprit du jeu",
  content: "Contenus pédagogiques", managementLead: "12 thèmes · 36 fiches rédigées · validation éditoriale avant publication",
  themes: "Thèmes", themesHint: "Accès direct aux 12 thèmes", theme: "Thème", cards: "Trois fiches pédagogiques",
  cardsHint: "Ouvrez une fiche pour modifier, prévisualiser et approuver son contenu.", approvedCount: "fiches approuvées",
  published: "Publié", review: "En validation", draft: "Brouillon", approved: "Approuvée", toReview: "À réviser",
  frenchTitle: "Titre français", saveTheme: "Enregistrer le thème", publishTheme: "Publier le thème complet",
  ready: "Prêt à publier", required: "Validation requise", publishHint: "Trois fiches complètes et approuvées sont nécessaires.",
  card: "Fiche", cardTitle: "Titre court", cardLead: "Rédigez, prévisualisez et validez la fiche avant publication du thème.",
  contentHint: "Les neuf champs éditoriaux sont obligatoires.", situation: "La situation", understand: "Comprendre",
  action: "Le bon réflexe", avoid: "À éviter", mission: "Ma mission sur le parcours", coachTip: "Conseil pédagogique Coach",
  reference: "Référence et illustration", referenceHint: "Précisez s’il s’agit d’une règle, d’un code, d’une consigne locale ou d’une bonne pratique.",
  referenceName: "Référence ou nature du conseil", referenceVersion: "Version de référence", kind: "Nature",
  rule: "Règle de golf", code: "Code de conduite", club: "Consigne locale", practice: "Bonne pratique",
  imageUrl: "URL de l’illustration (facultative)", imageAlt: "Texte alternatif de l’illustration",
  preview: "Prévisualiser", previewHeading: "Prévisualisation et validation", previewHint: "La validation humaine verrouille cette version, sans publier automatiquement le thème.",
  readyReview: "Prête pour la revue humaine", incomplete: "Contenu incomplet", versionHint: "Les fiches publiées restent intactes pendant la préparation d’une nouvelle version.",
  newVersion: "Préparer une nouvelle version", approve: "Approuver la fiche", save: "Enregistrer", close: "Fermer", refresh: "Actualiser",
  approvedVersion: "Version approuvée", version: "Version", sourceFrench: "français source", back: "Retour au module",
} as const;

const en: Record<keyof typeof fr, string> = {
  admin: "Administration", title: "Etiquette & spirit of the game", management: "Etiquette and spirit of the game management",
  content: "Learning content", managementLead: "12 themes · 36 written cards · editorial approval before publication",
  themes: "Themes", themesHint: "Direct access to all 12 themes", theme: "Theme", cards: "Three learning cards",
  cardsHint: "Open a card to edit, preview and approve its content.", approvedCount: "approved cards",
  published: "Published", review: "Under review", draft: "Draft", approved: "Approved", toReview: "Needs review",
  frenchTitle: "French title", saveTheme: "Save theme", publishTheme: "Publish complete theme",
  ready: "Ready to publish", required: "Approval required", publishHint: "Three complete, approved cards are required.",
  card: "Card", cardTitle: "Short title", cardLead: "Write, preview and approve the card before publishing the theme.",
  contentHint: "All nine editorial fields are required.", situation: "The situation", understand: "Understand",
  action: "What to do", avoid: "Avoid", mission: "My on-course mission", coachTip: "Coach tip",
  reference: "Reference and illustration", referenceHint: "Indicate whether this is a Rule, a code, local guidance or good practice.",
  referenceName: "Reference or type of advice", referenceVersion: "Reference version", kind: "Type",
  rule: "Rule of Golf", code: "Code of conduct", club: "Local guidance", practice: "Good practice",
  imageUrl: "Illustration URL (optional)", imageAlt: "Illustration alternative text",
  preview: "Preview", previewHeading: "Preview and approval", previewHint: "Human approval locks this version without publishing the theme.",
  readyReview: "Ready for human review", incomplete: "Incomplete content", versionHint: "Published cards stay intact while a new version is prepared.",
  newVersion: "Prepare a new version", approve: "Approve card", save: "Save", close: "Close", refresh: "Refresh",
  approvedVersion: "Approved version", version: "Version", sourceFrench: "French source", back: "Back to module",
};

const de: Record<keyof typeof fr, string> = {
  admin: "Administration", title: "Etikette & Geist des Spiels", management: "Verwaltung von Etikette und Spielgeist",
  content: "Lerninhalte", managementLead: "12 Themen · 36 ausgearbeitete Karten · redaktionelle Freigabe vor Veröffentlichung",
  themes: "Themen", themesHint: "Direkter Zugang zu allen 12 Themen", theme: "Thema", cards: "Drei Lernkarten",
  cardsHint: "Karte öffnen, um Inhalt zu bearbeiten, anzusehen und freizugeben.", approvedCount: "freigegebene Karten",
  published: "Veröffentlicht", review: "In Prüfung", draft: "Entwurf", approved: "Freigegeben", toReview: "Zu prüfen",
  frenchTitle: "Französischer Titel", saveTheme: "Thema speichern", publishTheme: "Vollständiges Thema veröffentlichen",
  ready: "Bereit zur Veröffentlichung", required: "Freigabe erforderlich", publishHint: "Drei vollständige, freigegebene Karten sind erforderlich.",
  card: "Karte", cardTitle: "Kurztitel", cardLead: "Karte verfassen, ansehen und freigeben, bevor das Thema veröffentlicht wird.",
  contentHint: "Alle neun redaktionellen Felder sind Pflichtfelder.", situation: "Die Situation", understand: "Verstehen",
  action: "Das richtige Verhalten", avoid: "Vermeiden", mission: "Meine Aufgabe auf dem Platz", coachTip: "Tipp für Coaches",
  reference: "Quelle und Illustration", referenceHint: "Kennzeichnen, ob es sich um eine Regel, einen Verhaltenskodex, eine Clubvorgabe oder eine gute Praxis handelt.",
  referenceName: "Quelle oder Art des Hinweises", referenceVersion: "Version der Quelle", kind: "Art",
  rule: "Golfregel", code: "Verhaltenskodex", club: "Clubvorgabe", practice: "Gute Praxis",
  imageUrl: "Bild-URL (optional)", imageAlt: "Alternativtext zum Bild",
  preview: "Vorschau", previewHeading: "Vorschau und Freigabe", previewHint: "Die menschliche Freigabe sperrt diese Version, ohne das Thema zu veröffentlichen.",
  readyReview: "Bereit für die redaktionelle Prüfung", incomplete: "Unvollständiger Inhalt", versionHint: "Veröffentlichte Karten bleiben erhalten, während eine neue Version vorbereitet wird.",
  newVersion: "Neue Version vorbereiten", approve: "Karte freigeben", save: "Speichern", close: "Schließen", refresh: "Aktualisieren",
  approvedVersion: "Freigegebene Version", version: "Version", sourceFrench: "französischer Ausgangstext", back: "Zurück zum Modul",
};

const it: Record<keyof typeof fr, string> = {
  admin: "Amministrazione", title: "Etichetta & spirito del gioco", management: "Gestione dell’etichetta e dello spirito del gioco",
  content: "Contenuti didattici", managementLead: "12 temi · 36 schede complete · approvazione editoriale prima della pubblicazione",
  themes: "Temi", themesHint: "Accesso diretto ai 12 temi", theme: "Tema", cards: "Tre schede didattiche",
  cardsHint: "Apri una scheda per modificarla, visualizzarla e approvarla.", approvedCount: "schede approvate",
  published: "Pubblicato", review: "In revisione", draft: "Bozza", approved: "Approvata", toReview: "Da rivedere",
  frenchTitle: "Titolo francese", saveTheme: "Salva tema", publishTheme: "Pubblica il tema completo",
  ready: "Pronto per la pubblicazione", required: "Approvazione necessaria", publishHint: "Servono tre schede complete e approvate.",
  card: "Scheda", cardTitle: "Titolo breve", cardLead: "Scrivi, visualizza e approva la scheda prima di pubblicare il tema.",
  contentHint: "Tutti e nove i campi editoriali sono obbligatori.", situation: "La situazione", understand: "Capire",
  action: "Il gesto giusto", avoid: "Da evitare", mission: "La mia missione sul campo", coachTip: "Consiglio per il coach",
  reference: "Fonte e illustrazione", referenceHint: "Indica se si tratta di una Regola, di un codice, di una direttiva locale o di una buona pratica.",
  referenceName: "Fonte o tipo di consiglio", referenceVersion: "Versione della fonte", kind: "Tipo",
  rule: "Regola del golf", code: "Codice di condotta", club: "Direttiva locale", practice: "Buona pratica",
  imageUrl: "URL dell’illustrazione (facoltativo)", imageAlt: "Testo alternativo dell’illustrazione",
  preview: "Anteprima", previewHeading: "Anteprima e approvazione", previewHint: "L’approvazione umana blocca questa versione senza pubblicare il tema.",
  readyReview: "Pronta per la revisione umana", incomplete: "Contenuto incompleto", versionHint: "Le schede pubblicate restano intatte mentre si prepara una nuova versione.",
  newVersion: "Prepara una nuova versione", approve: "Approva scheda", save: "Salva", close: "Chiudi", refresh: "Aggiorna",
  approvedVersion: "Versione approvata", version: "Versione", sourceFrench: "testo originale francese", back: "Torna al modulo",
};

export function etiquetteAdminText(locale: string): Record<keyof typeof fr, string> {
  return { fr, en, de, it }[locale as "fr" | "en" | "de" | "it"] ?? fr;
}
