"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ChevronRight, Edit3, ImagePlus, Languages, Newspaper, Plus, Save, Trash2, X } from "lucide-react";
import { supabase } from "@/lib/supabaseClient";
import styles from "./AdminNewsWorkspace.module.css";

const LOCALES = ["fr", "en", "de", "it"] as const;
type Locale = typeof LOCALES[number];
type Translation = { title: string; summary: string; body: string };
type AudienceRole = "player" | "coach" | "manager";
type NewsTarget = { club_id: string; roles: AudienceRole[] };
type NewsRow = { id: string; status: string; scheduled_for: string | null; published_at: string | null; visible_on_home: boolean; image_url: string | null; updated_at: string; targets: NewsTarget[]; translations: Partial<Record<Locale, Translation>> };
type Club = { id: string; name: string };
const ROLES: Array<{key:AudienceRole;label:string}> = [{key:"player",label:"Joueurs"},{key:"coach",label:"Coachs"},{key:"manager",label:"Managers"}];
const emptyTranslations = (): Record<Locale, Translation> => ({ fr:{title:"",summary:"",body:""}, en:{title:"",summary:"",body:""}, de:{title:"",summary:"",body:""}, it:{title:"",summary:"",body:""} });
const emptyForm = () => ({ id:"", status:"draft", scheduled_for:"", visible_on_home:false, image_url:"", targets:[] as NewsTarget[], translations:emptyTranslations() });
const statusLabel: Record<string,string> = { draft:"Brouillon", scheduled:"Programmée", published:"Publiée", archived:"Archivée" };

export default function AdminNewsWorkspace() {
  const [clubs,setClubs]=useState<Club[]>([]); const [news,setNews]=useState<NewsRow[]>([]); const [form,setForm]=useState(emptyForm());
  const [locale,setLocale]=useState<Locale>("fr"); const [editing,setEditing]=useState(false); const [busy,setBusy]=useState(false); const [translating,setTranslating]=useState(false);
  const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);

  const headers=useCallback(async(json=true)=>{ const session=await supabase.auth.getSession(); const token=session.data.session?.access_token; if(!token) throw new Error("Session invalide."); return {Authorization:`Bearer ${token}`,...(json?{"Content-Type":"application/json"}:{})}; },[]);
  const load=useCallback(async()=>{ setBusy(true); setError(null); try{ const response=await fetch("/api/admin/news",{headers:await headers(false),cache:"no-store"}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error); setClubs(payload.clubs??[]); setNews(payload.news??[]); }catch(cause){setError(cause instanceof Error?cause.message:"Chargement impossible.");}finally{setBusy(false);} },[headers]);
  useEffect(()=>{void load();},[load]);
  function begin(row?:NewsRow){ if(row){ const texts=emptyTranslations(); for(const key of LOCALES){const value=row.translations?.[key];if(value)texts[key]={title:value.title??"",summary:value.summary??"",body:value.body??""};} setForm({id:row.id,status:row.status,scheduled_for:row.scheduled_for?row.scheduled_for.slice(0,16):"",visible_on_home:row.visible_on_home,image_url:row.image_url??"",targets:(row.targets??[]).map(target=>({...target,roles:[...target.roles]})),translations:texts}); } else setForm(emptyForm()); setLocale("fr"); setEditing(true); setError(null); setSuccess(null); }
  function setText(field:keyof Translation,value:string){setForm(previous=>({...previous,translations:{...previous.translations,[locale]:{...previous.translations[locale],[field]:value}}}));}
  function hasRole(clubId:string,role:AudienceRole){return form.targets.some(target=>target.club_id===clubId&&target.roles.includes(role));}
  function toggleTarget(clubId:string,role:AudienceRole){setForm(previous=>{const current=previous.targets.find(target=>target.club_id===clubId);const roles=current?.roles??[];const nextRoles=roles.includes(role)?roles.filter(value=>value!==role):[...roles,role];return {...previous,targets:nextRoles.length?[...previous.targets.filter(target=>target.club_id!==clubId),{club_id:clubId,roles:nextRoles}]:previous.targets.filter(target=>target.club_id!==clubId)};});}
  function selectAllTargets(){setForm(previous=>({...previous,targets:clubs.map(club=>({club_id:club.id,roles:ROLES.map(role=>role.key)}))}));}
  function isRoleSelectedForAll(role:AudienceRole){return clubs.length>0&&clubs.every(club=>form.targets.some(target=>target.club_id===club.id&&target.roles.includes(role)));}
  function toggleRoleForAll(role:AudienceRole){setForm(previous=>{const shouldRemove=clubs.length>0&&clubs.every(club=>previous.targets.some(target=>target.club_id===club.id&&target.roles.includes(role)));const targets=clubs.map(club=>{const current=previous.targets.find(target=>target.club_id===club.id);const roles=current?.roles??[];return {club_id:club.id,roles:shouldRemove?roles.filter(value=>value!==role):Array.from(new Set([...roles,role]))};}).filter(target=>target.roles.length>0);return {...previous,targets};});}
  async function save(){setBusy(true);setError(null);try{const response=await fetch(form.id?`/api/admin/news/${form.id}`:"/api/admin/news",{method:form.id?"PATCH":"POST",headers:await headers(),body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setSuccess(form.id?"Actualité mise à jour.":"Actualité créée.");setEditing(false);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Enregistrement impossible.");}finally{setBusy(false);}}
  async function remove(id:string){if(!window.confirm("Supprimer définitivement cette actualité ?"))return;setBusy(true);try{const response=await fetch(`/api/admin/news/${id}`,{method:"DELETE",headers:await headers(false)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);await load();}catch(cause){setError(cause instanceof Error?cause.message:"Suppression impossible.");}finally{setBusy(false);}}
  async function upload(file:File){setBusy(true);setError(null);try{const data=new FormData();data.set("image",file);const response=await fetch("/api/admin/news/image",{method:"POST",headers:await headers(false),body:data});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setForm(previous=>({...previous,image_url:payload.image_url}));}catch(cause){setError(cause instanceof Error?cause.message:"Upload impossible.");}finally{setBusy(false);}}
  async function translateWithOpenAI(){const source=form.translations.fr;if(!source.title.trim()){setError("Renseigne d’abord le titre français.");setLocale("fr");return;}const hasExisting=["en","de","it"].some(key=>form.translations[key as Locale].title||form.translations[key as Locale].summary||form.translations[key as Locale].body);if(hasExisting&&!window.confirm("Remplacer les traductions anglaise, allemande et italienne existantes ?"))return;setTranslating(true);setError(null);try{const response=await fetch("/api/admin/news/translate",{method:"POST",headers:await headers(),body:JSON.stringify(source)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setForm(previous=>({...previous,translations:{...previous.translations,en:payload.translations.en,de:payload.translations.de,it:payload.translations.it}}));setSuccess("Traductions proposées par OpenAI. Vérifie-les avant d’enregistrer.");setLocale("en");}catch(cause){setError(cause instanceof Error?cause.message:"Traduction impossible.");}finally{setTranslating(false);}}

  return <div className={styles.page}>
    <nav className={styles.breadcrumb}><Link href="/admin">Administration</Link><ChevronRight size={14}/><span>Actualités ActiviTee</span></nav>
    <header className={styles.topline}><div><p className={styles.eyebrow}>Communication plateforme</p><h1>Actualités ActiviTee</h1><p>Publiez une seule actualité, traduite et distribuée aux clubs sélectionnés.</p></div><button className={styles.primary} onClick={()=>begin()}><Plus size={16}/>Nouvelle actualité</button></header>
    {error?<div className={styles.error} role="alert">{error}</div>:null}{success?<div className={styles.success}>{success}</div>:null}
    {editing?<section className={styles.panel}>
      <div className={styles.panelHead}><div><h2>{form.id?"Modifier l’actualité":"Créer une actualité"}</h2><p>Le français est obligatoire. Les autres langues utilisent le français comme repli.</p></div><button className={styles.icon} onClick={()=>setEditing(false)} aria-label="Fermer"><X size={18}/></button></div>
      <div className={styles.translationBar}><div className={styles.localeTabs}>{LOCALES.map(key=><button key={key} aria-pressed={locale===key} onClick={()=>setLocale(key)}>{key.toUpperCase()} {form.translations[key].title?"✓":""}</button>)}</div><button className={styles.translateButton} onClick={()=>void translateWithOpenAI()} disabled={translating}><Languages size={15}/>{translating?"Traduction…":"Traduire DE · EN · IT avec OpenAI"}</button></div>
      <div className={styles.fields}><label className={styles.full}>Titre {locale==="fr"?"*":""}<input value={form.translations[locale].title} onChange={e=>setText("title",e.target.value)}/></label><label className={styles.full}>Résumé<textarea rows={2} value={form.translations[locale].summary} onChange={e=>setText("summary",e.target.value)}/></label><label className={styles.full}>Contenu<textarea rows={7} value={form.translations[locale].body} onChange={e=>setText("body",e.target.value)}/></label>
        <label>Statut<select value={form.status} onChange={e=>setForm(p=>({...p,status:e.target.value}))}><option value="draft">Brouillon</option><option value="scheduled">Programmée</option><option value="published">Publiée</option><option value="archived">Archivée</option></select></label>{form.status==="scheduled"?<label>Publication prévue<input type="datetime-local" value={form.scheduled_for} onChange={e=>setForm(p=>({...p,scheduled_for:e.target.value}))}/></label>:null}
      </div>
      <div className={styles.targetSection}><div className={styles.targetHeading}><div><h3>Matrice des destinataires *</h3><p>Choisis précisément les rôles concernés dans chaque club.</p></div><div><button className={styles.secondary} onClick={selectAllTargets}>Tout sélectionner</button><button className={styles.secondary} onClick={()=>setForm(p=>({...p,targets:[]}))}>Effacer</button></div></div><div className={styles.rolePresets} aria-label="Sélection rapide par type de destinataire"><span>Par type :</span>{ROLES.map(role=><button key={role.key} type="button" aria-pressed={isRoleSelectedForAll(role.key)} onClick={()=>toggleRoleForAll(role.key)}>Tous les {role.label.toLowerCase()}</button>)}</div><div className={styles.targetMatrix} role="table" aria-label="Matrice des clubs et des types de destinataires"><div className={`${styles.targetRow} ${styles.targetHeader}`} role="row"><span role="columnheader">Club</span>{ROLES.map(role=><span role="columnheader" key={role.key}>{role.label}</span>)}</div>{clubs.map(club=><div className={styles.targetRow} role="row" key={club.id}><strong role="rowheader">{club.name}</strong>{ROLES.map(role=><label className={styles.targetCell} key={role.key}><input type="checkbox" checked={hasRole(club.id,role.key)} onChange={()=>toggleTarget(club.id,role.key)} aria-label={`${role.label} · ${club.name}`}/><span aria-hidden="true"/></label>)}</div>)}</div><p className={styles.targetSummary}>{form.targets.reduce((total,target)=>total+target.roles.length,0)} sélection{form.targets.reduce((total,target)=>total+target.roles.length,0)!==1?"s":""} dans {form.targets.length} club{form.targets.length!==1?"s":""}.</p></div>
      <div className={styles.media}><div>{form.image_url?<img src={form.image_url} alt="Aperçu"/>:<span><ImagePlus size={24}/>Format 16:9 recommandé</span>}</div><label className={styles.secondary}><ImagePlus size={15}/>Choisir une image<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}}/></label>{form.image_url?<button className={styles.secondary} onClick={()=>setForm(p=>({...p,image_url:""}))}>Retirer</button>:null}</div>
      <label className={styles.homeToggle}><input type="checkbox" checked={form.visible_on_home} onChange={e=>setForm(p=>({...p,visible_on_home:e.target.checked}))}/>Afficher également sur les pages d’accueil</label>
      <div className={styles.formActions}><button className={styles.secondary} onClick={()=>setEditing(false)}>Annuler</button><button className={styles.primary} onClick={()=>void save()} disabled={busy}><Save size={16}/>{busy?"Enregistrement…":"Enregistrer"}</button></div>
    </section>:null}
    <section className={styles.panel}><div className={styles.panelHead}><div><h2>Actualités</h2><p>{news.length} actualité{news.length!==1?"s":""} au niveau de la plateforme.</p></div></div>
      {busy&&!news.length?<div className={styles.empty}>Chargement…</div>:news.length===0?<div className={styles.empty}><Newspaper size={22}/>Aucune actualité.</div>:<div className={styles.list}>{news.map(row=>{const fr=row.translations.fr;return <article key={row.id} className={styles.card}>{row.image_url?<img src={row.image_url} alt=""/>:null}<div className={styles.cardBody}><div className={styles.meta}><span>{statusLabel[row.status]??row.status}</span><span>{row.targets.length} club{row.targets.length!==1?"s":""}</span><span>{row.targets.reduce((total,target)=>total+target.roles.length,0)} cible{row.targets.reduce((total,target)=>total+target.roles.length,0)!==1?"s":""}</span><span>{Object.keys(row.translations).length}/4 langues</span></div><h3>{fr?.title??"Sans titre"}</h3>{fr?.summary?<p>{fr.summary}</p>:null}<div className={styles.cardActions}><button className={styles.icon} onClick={()=>begin(row)} aria-label="Modifier"><Edit3 size={16}/></button><button className={`${styles.icon} ${styles.danger}`} onClick={()=>void remove(row.id)} aria-label="Supprimer"><Trash2 size={16}/></button></div></div></article>})}</div>}
    </section>
  </div>;
}
