import { NextResponse, type NextRequest } from "next/server";
import { calculateAttendance, calculateProratedTrainingObjective, calculateRegularity, handicapProgression, uniqueTrainingRows } from "@/lib/playerStatistics";
import { ageCategory, attendanceTrend, isAssiduous, median, percentage, PERFORMANCE_THRESHOLDS, round1 } from "@/lib/managerPerformance";
import { dateKey, endIso, performanceContext, queryRows, resolveRange, startIso } from "../_lib";

type MemberRow = { id: string; user_id: string; is_active: boolean; profiles: { first_name: string | null; last_name: string | null; birth_date: string | null; handicap: number | null; avatar_url: string | null } | null };
type ProfileRow = { id: string; first_name: string | null; last_name: string | null; birth_date: string | null; handicap: number | null; avatar_url: string | null };
type SeasonRecord = { club_member_id: string; group_id: string | null; registration_status: string };
type GroupRow = { id: string; name: string };
type EventRow = { id: string; group_id: string | null; event_type: string | null; title: string; starts_at: string; status: string | null; requires_evaluation: boolean; duration_minutes: number | null };
type AttendeeRow = { event_id: string; player_id: string; status: string | null };
type TrainingRow = { id: string; user_id: string; start_at: string; total_minutes: number | null; session_type: string | null; club_event_id: string | null; club_id: string | null };
type RoundRow = { id: string; user_id: string; start_at: string; round_type: string | null; total_score: number | null };
type HandicapRow = { user_id: string; effective_date: string; value: number };
type FeedbackRow = { event_id: string; player_id: string; coach_id: string };
type TargetRow = { ftem_code: string; level_label: string; handicap_min: number | null; handicap_max: number | null; minutes_offseason: number; minutes_inseason: number };

const nameOf = (member: MemberRow) => `${member.profiles?.first_name ?? ""} ${member.profiles?.last_name ?? ""}`.trim() || "Junior";
const targetFor = (targets: TargetRow[], handicap: number | null) => targets.find((target) => handicap != null && (target.handicap_min == null || handicap >= target.handicap_min) && (target.handicap_max == null || handicap <= target.handicap_max)) ?? null;

export async function GET(req: NextRequest, ctx: { params: Promise<{ clubId: string }> }) {
  try {
    const { clubId } = await ctx.params; const auth = await performanceContext(req, clubId);
    if (!auth.ok) return NextResponse.json({ error: auth.error }, { status: auth.status });
    const { range, previous, season, seasons } = await resolveRange(req, auth.db, clubId);
    const earliest = previous.from;
    const [members, groups, seasonRecords, events, settingsResult, targets] = await Promise.all([
      queryRows<MemberRow>(auth.db.from("club_members").select("id,user_id,is_active").eq("club_id", clubId).eq("role", "player")),
      queryRows<GroupRow>(auth.db.from("coach_groups").select("id,name").eq("club_id", clubId).eq("club_season_id", season?.id ?? "00000000-0000-0000-0000-000000000000").eq("is_active", true)),
      season ? queryRows<SeasonRecord>(auth.db.from("club_player_season_records").select("club_member_id,group_id,registration_status").eq("club_season_id", season.id)) : Promise.resolve([]),
      queryRows<EventRow>(auth.db.from("club_events").select("id,group_id,event_type,title,starts_at,status,requires_evaluation,duration_minutes").eq("club_id", clubId).gte("starts_at", startIso(earliest)).lte("starts_at", endIso(range.to)).limit(10000)),
      auth.db.from("training_volume_settings").select("season_months,offseason_months").eq("organization_id", clubId).maybeSingle(),
      queryRows<TargetRow>(auth.db.from("training_volume_targets").select("ftem_code,level_label,handicap_min,handicap_max,minutes_offseason,minutes_inseason").eq("organization_id", clubId).order("sort_order")),
    ]);
    if (settingsResult.error) throw new Error(settingsResult.error.message);
    const memberIds = members.map((member) => member.user_id); const profiles = memberIds.length ? await queryRows<ProfileRow>(auth.db.from("profiles").select("id,first_name,last_name,birth_date,handicap,avatar_url").in("id", memberIds)) : []; const profileMap = new Map(profiles.map((profile) => [profile.id, profile])); for (const member of members) member.profiles = profileMap.get(member.user_id) ?? null; const eventIds = events.map((event) => event.id);
    const [attendees, trainings, rounds, handicaps, feedback] = await Promise.all([
      eventIds.length && memberIds.length ? queryRows<AttendeeRow>(auth.db.from("club_event_attendees").select("event_id,player_id,status").in("event_id", eventIds).in("player_id", memberIds).limit(30000)) : Promise.resolve([]),
      memberIds.length ? queryRows<TrainingRow>(auth.db.from("training_sessions").select("id,user_id,start_at,total_minutes,session_type,club_event_id,club_id").in("user_id", memberIds).gte("start_at", startIso(earliest)).lte("start_at", endIso(range.to)).limit(30000)) : Promise.resolve([]),
      memberIds.length ? queryRows<RoundRow>(auth.db.from("golf_rounds").select("id,user_id,start_at,round_type,total_score").in("user_id", memberIds).gte("start_at", startIso(earliest)).lte("start_at", endIso(range.to)).limit(10000)) : Promise.resolve([]),
      memberIds.length ? queryRows<HandicapRow>(auth.db.from("player_handicap_history").select("user_id,effective_date,value").in("user_id", memberIds).lte("effective_date", range.to).limit(20000)) : Promise.resolve([]),
      eventIds.length && memberIds.length ? queryRows<FeedbackRow>(auth.db.from("club_event_coach_feedback").select("event_id,player_id,coach_id").in("event_id", eventIds).in("player_id", memberIds).limit(30000)) : Promise.resolve([]),
    ]);
    const eventMap = new Map(events.map((event) => [event.id, event])); const recordMap = new Map(seasonRecords.map((record) => [record.club_member_id, record])); const groupMap = new Map(groups.map((group) => [group.id, group.name]));
    const filterGroup = req.nextUrl.searchParams.get("group") ?? "all"; const filterFtem = req.nextUrl.searchParams.get("ftem") ?? "all"; const filterAge = req.nextUrl.searchParams.get("age") ?? "all"; const filterStatus = req.nextUrl.searchParams.get("status") ?? "active"; const filterType = req.nextUrl.searchParams.get("activityType") ?? "all";
    const attendanceInput = (playerId: string) => attendees.filter((row) => row.player_id === playerId).flatMap((row) => { const event = eventMap.get(row.event_id); return event && (filterType === "all" || event.event_type === filterType) ? [{ id: event.id, startsAt: event.starts_at, status: row.status, eventStatus: event.status, eventType: event.event_type }] : []; });
    const rows = members.map((member) => {
      const record = recordMap.get(member.id); const handicap = member.profiles?.handicap == null ? null : Number(member.profiles.handicap); const ftem = targetFor(targets, handicap); const age = ageCategory(member.profiles?.birth_date);
      const attendanceRows = attendanceInput(member.user_id); const currentAttendance = calculateAttendance(attendanceRows, range); const previousAttendance = calculateAttendance(attendanceRows, previous); const trend = attendanceTrend(currentAttendance, previousAttendance);
      const playerTrainings = uniqueTrainingRows(trainings.filter((row) => row.user_id === member.user_id && (row.club_id == null || row.club_id === clubId)).map((row) => ({ id: row.id, startAt: row.start_at, minutes: Number(row.total_minutes ?? 0), sessionType: row.session_type, clubEventId: row.club_event_id })));
      const currentTrainings = playerTrainings.filter((row) => dateKey(row.startAt) >= range.from && dateKey(row.startAt) <= range.to); const previousTrainings = playerTrainings.filter((row) => dateKey(row.startAt) >= previous.from && dateKey(row.startAt) <= previous.to); const trainingMinutes = currentTrainings.reduce((sum, row) => sum + Number(row.minutes ?? 0), 0); const previousMinutes = previousTrainings.reduce((sum, row) => sum + Number(row.minutes ?? 0), 0); const regularity = calculateRegularity(currentTrainings, range); const previousRegularity = calculateRegularity(previousTrainings, previous);
      const history = handicaps.filter((row) => row.user_id === member.user_id).map((row) => ({ effectiveDate: row.effective_date, value: Number(row.value) })); const handicapChange = handicapProgression(history, range, handicap).change;
      const objective = calculateProratedTrainingObjective({ range, seasonMonths: (settingsResult.data?.season_months ?? []).map(Number), targets, handicapHistory: history, currentHandicap: handicap }); const objectiveRate = objective.minutes ? round1((trainingMinutes / objective.minutes) * 100) : null;
      const playerRounds = rounds.filter((round) => round.user_id === member.user_id && dateKey(round.start_at) >= range.from); const competitions = playerRounds.filter((round) => round.round_type === "competition"); const invitedEvaluationEvents = new Set(attendees.filter((item) => item.player_id === member.user_id && eventMap.get(item.event_id)?.requires_evaluation && dateKey(eventMap.get(item.event_id)!.starts_at) >= range.from).map((item) => item.event_id)); const completedEvaluations = new Set(feedback.filter((item) => item.player_id === member.user_id && invitedEvaluationEvents.has(item.event_id)).map((item) => item.event_id)).size;
      const reasons: string[] = []; if (handicapChange != null && handicapChange > 0) reasons.push(`Handicap −${handicapChange.toLocaleString("fr-CH")}`); if (trend.status === "up") reasons.push(`Assiduité +${trend.change} points`); const regularityChange = regularity.rate != null && previousRegularity.rate != null ? round1(regularity.rate - previousRegularity.rate) : null; if (regularityChange != null && regularityChange >= 15) reasons.push(`Régularité +${regularityChange} points`); if (previousMinutes > 0 && trainingMinutes >= previousMinutes * 1.15) reasons.push(`Volume +${round1(((trainingMinutes - previousMinutes) / previousMinutes) * 100)} %`);
      const lastActivity = attendanceRows.filter((item) => item.status === "present" && dateKey(item.startsAt) <= range.to).map((item) => item.startsAt).sort().at(-1) ?? null;
      return { id: member.user_id, memberId: member.id, name: nameOf(member), avatarUrl: member.profiles?.avatar_url ?? null, active: member.is_active && (record?.registration_status ?? "active") === "active", status: record?.registration_status ?? "active", groupId: record?.group_id ?? null, groupName: record?.group_id ? groupMap.get(record.group_id) ?? "Groupe" : null, ageCategory: age, ftemCode: ftem?.ftem_code ?? null, ftemLabel: ftem?.level_label ?? null, attendance: currentAttendance, attendanceTrend: trend, assiduous: isAssiduous(currentAttendance), trainingMinutes, trainingSessions: currentTrainings.length, regularityRate: regularity.rate, objectiveRate, handicap, handicapChange, competitions: competitions.length, rounds: playerRounds.length, missingCompetitionResults: competitions.filter((round) => round.total_score == null).length, evaluationsExpected: invitedEvaluationEvents.size, evaluationsCompleted: completedEvaluations, evaluationCoverage: percentage(completedEvaluations, invitedEvaluationEvents.size), reasons, progression: reasons.length > 0, lastActivity };
    }).filter((row) => (filterGroup === "all" || row.groupId === filterGroup) && (filterFtem === "all" || row.ftemCode === filterFtem) && (filterAge === "all" || row.ageCategory === filterAge) && (filterStatus === "all" || (filterStatus === "active" ? row.active : !row.active)));
    if (req.nextUrl.searchParams.get("comparison") === "none") for (const row of rows) { row.attendanceTrend = { status: "insufficient", change: null }; row.reasons = row.reasons.filter((reason) => reason.startsWith("Handicap")); row.progression = row.reasons.length > 0; }
    const attendancePresent = rows.reduce((sum, row) => sum + row.attendance.present, 0); const attendanceDenominator = rows.reduce((sum, row) => sum + row.attendance.denominator, 0); const evaluationsExpected = rows.reduce((sum, row) => sum + row.evaluationsExpected, 0); const evaluationsCompleted = rows.reduce((sum, row) => sum + row.evaluationsCompleted, 0); const now = new Date(`${range.to}T23:59:59Z`).getTime();
    const attention = rows.flatMap((row) => { const items: Array<{ type: string; severity: "neutral" | "warning" | "positive"; reason: string; value: string }> = []; if (row.attendanceTrend.status === "down") items.push({ type: "attendance-down", severity: "warning", reason: "Assiduité en baisse", value: `${row.attendanceTrend.change} points` }); if (row.attendance.pending) items.push({ type: "attendance-pending", severity: "warning", reason: "Présences à traiter", value: `${row.attendance.pending}` }); if (!row.lastActivity || now - new Date(row.lastActivity).getTime() > PERFORMANCE_THRESHOLDS.recentActivityDays * 86400000) items.push({ type: "inactive", severity: "neutral", reason: "Aucune activité récente", value: row.lastActivity ? `Depuis le ${new Intl.DateTimeFormat("fr-CH").format(new Date(row.lastActivity))}` : "Aucune présence enregistrée" }); if (row.objectiveRate != null && row.objectiveRate < PERFORMANCE_THRESHOLDS.objectiveFarBelowRate) items.push({ type: "objective", severity: "neutral", reason: "Repère d’entraînement éloigné", value: `${row.objectiveRate} %` }); if (row.evaluationsExpected > row.evaluationsCompleted) items.push({ type: "evaluation", severity: "warning", reason: "Évaluations en attente", value: `${row.evaluationsExpected - row.evaluationsCompleted}` }); if (row.missingCompetitionResults) items.push({ type: "competition", severity: "warning", reason: "Résultat de compétition manquant", value: `${row.missingCompetitionResults}` }); if (row.progression && row.reasons.length >= 2) items.push({ type: "progress", severity: "positive", reason: "Progression à valoriser", value: row.reasons.join(" · ") }); return items.map((item) => ({ ...item, playerId: row.id, playerName: row.name })); });
    const monthly = Array.from(new Set(events.filter((event) => dateKey(event.starts_at) >= range.from).map((event) => event.starts_at.slice(0, 7)))).sort().map((month) => { const monthRows = rows.flatMap((row) => attendanceInput(row.id)); const period = { from: `${month}-01`, to: `${month}-${String(new Date(Number(month.slice(0, 4)), Number(month.slice(5, 7)), 0).getDate()).padStart(2, "0")}` }; const metric = calculateAttendance(monthRows, period); return { month, rate: metric.rate, present: metric.present, absent: metric.absent, excused: metric.excused, pending: metric.pending }; });
    const byGroup = groups.map((group) => { const values = rows.filter((row) => row.groupId === group.id); const present = values.reduce((sum, row) => sum + row.attendance.present, 0); const denominator = values.reduce((sum, row) => sum + row.attendance.denominator, 0); return { id: group.id, label: group.name, count: values.length, attendanceRate: percentage(present, denominator), medianTrainingMinutes: median(values.map((row) => row.trainingMinutes)) }; }).filter((group) => group.count);
    return NextResponse.json({ generatedAt: new Date().toISOString(), clubId, range, previous, season, seasons, filters: { groups, ftem: targets.map((target) => ({ code: target.ftem_code, label: target.level_label })), activityTypes: Array.from(new Set(events.map((event) => event.event_type).filter(Boolean))) }, overview: { activeJuniors: rows.filter((row) => row.active).length, attendanceRate: percentage(attendancePresent, attendanceDenominator), medianActivities: median(rows.map((row) => row.attendance.invited)), medianTrainingMinutes: median(rows.map((row) => row.trainingMinutes)), progressing: rows.filter((row) => row.progression).length, evaluationCoverage: percentage(evaluationsCompleted, evaluationsExpected), competitionParticipation: percentage(rows.filter((row) => row.competitions > 0).length, rows.length), dataCompleteness: percentage(rows.filter((row) => row.attendance.invited || row.trainingSessions || row.rounds || row.evaluationsCompleted).length, rows.length) }, attendance: { monthly, present: rows.reduce((sum, row) => sum + row.attendance.present, 0), absent: rows.reduce((sum, row) => sum + row.attendance.absent, 0), excused: rows.reduce((sum, row) => sum + row.attendance.excused, 0), pending: rows.reduce((sum, row) => sum + row.attendance.pending, 0), assiduous: rows.filter((row) => row.assiduous).length, progressing: rows.filter((row) => row.attendanceTrend.status === "up").length, declining: rows.filter((row) => row.attendanceTrend.status === "down").length }, training: { totalMinutes: rows.reduce((sum, row) => sum + row.trainingMinutes, 0), medianMinutes: median(rows.map((row) => row.trainingMinutes)), medianObjectiveRate: median(rows.map((row) => row.objectiveRate)), medianRegularityRate: median(rows.map((row) => row.regularityRate)), objectiveDistribution: { below60: rows.filter((row) => row.objectiveRate != null && row.objectiveRate < 60).length, from60to89: rows.filter((row) => row.objectiveRate != null && row.objectiveRate >= 60 && row.objectiveRate < 90).length, from90to120: rows.filter((row) => row.objectiveRate != null && row.objectiveRate >= 90 && row.objectiveRate <= 120).length, above120: rows.filter((row) => row.objectiveRate != null && row.objectiveRate > 120).length, undefined: rows.filter((row) => row.objectiveRate == null).length } }, competition: { participating: rows.filter((row) => row.competitions > 0).length, medianCompetitions: median(rows.map((row) => row.competitions)), rounds: rows.reduce((sum, row) => sum + row.rounds, 0), missingResults: rows.reduce((sum, row) => sum + row.missingCompetitionResults, 0) }, evaluations: { expected: evaluationsExpected, completed: evaluationsCompleted, missing: Math.max(0, evaluationsExpected - evaluationsCompleted), coverage: percentage(evaluationsCompleted, evaluationsExpected) }, byGroup, rows, attention });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Erreur serveur." }, { status: 500 }); }
}
