-- Read-only postflight after 20261101_legal_remaining_rpc_batch.sql on isolated TEST.
-- Every wrapper: anon=false, authenticated=true, service=true, checks_legal_gate=true.
-- Every business function: anon=false, authenticated=false, service=true.
with signatures(signature,kind) as (values
  ('public.copy_manager_event_structure_v1(uuid,jsonb)','wrapper'),
  ('public.copy_manager_event_structure_v1_business(uuid,jsonb)','business'),
  ('public.get_manager_competition_snapshot_v1(uuid)','wrapper'),
  ('public.get_manager_competition_snapshot_v1_business(uuid)','business'),
  ('public.get_manager_evaluation_snapshot_v1(uuid,uuid)','wrapper'),
  ('public.get_manager_evaluation_snapshot_v1_business(uuid,uuid)','business'),
  ('public.get_manager_planning_snapshot_v1(uuid)','wrapper'),
  ('public.get_manager_planning_snapshot_v1_business(uuid)','business'),
  ('public.save_manager_competition_v1(uuid,jsonb,jsonb)','wrapper'),
  ('public.save_manager_competition_v1_business(uuid,jsonb,jsonb)','business'),
  ('public.save_manager_event_feedback_v1(uuid,uuid,jsonb)','wrapper'),
  ('public.save_manager_event_feedback_v1_business(uuid,uuid,jsonb)','business'),
  ('public.save_manager_event_feedback_v2(uuid,uuid,jsonb,jsonb)','wrapper'),
  ('public.save_manager_event_feedback_v2_business(uuid,uuid,jsonb,jsonb)','business'),
  ('public.get_manager_om_data_v1(uuid,text)','wrapper'),
  ('public.get_manager_om_data_v1_business(uuid,text)','business'),
  ('public.get_manager_om_contest_v1(uuid)','wrapper'),
  ('public.get_manager_om_contest_v1_business(uuid)','business'),
  ('public.get_manager_om_ranking_v1(uuid,date,date,uuid)','wrapper'),
  ('public.get_manager_om_ranking_v1_business(uuid,date,date,uuid)','business'),
  ('public.ensure_event_thread_for_event(uuid)','wrapper'),
  ('public.ensure_event_thread_for_event_business(uuid)','business'),
  ('public.sync_event_thread_participants(uuid)','wrapper'),
  ('public.sync_event_thread_participants_business(uuid)','business'),
  ('public.start_rules_quiz(uuid,uuid)','wrapper'),
  ('public.start_rules_quiz_business(uuid,uuid)','business'),
  ('public.submit_rules_quiz(uuid)','wrapper'),
  ('public.submit_rules_quiz_business(uuid)','business'),
  ('public.create_manager_activity_batch_v1(uuid,jsonb)','wrapper'),
  ('public.create_manager_activity_batch_v1_business(uuid,jsonb)','business'),
  ('public.coach_group_delete_category(uuid,uuid)','wrapper'),
  ('public.coach_group_delete_category_business(uuid,uuid)','business'),
  ('public.coach_group_delete_player(uuid,uuid)','wrapper'),
  ('public.coach_group_delete_player_business(uuid,uuid)','business'),
  ('public.answer_rules_quiz_question(uuid,uuid,uuid[])','wrapper'),
  ('public.answer_rules_quiz_question_business(uuid,uuid,uuid[])','business'),
  ('public.get_rules_quiz_question(uuid,smallint)','wrapper'),
  ('public.get_rules_quiz_question_business(uuid,smallint)','business'),
  ('public.get_rules_quiz_result(uuid)','wrapper'),
  ('public.get_rules_quiz_result_business(uuid)','business'),
  ('public.etiquette_publish_theme(uuid)','wrapper'),
  ('public.etiquette_publish_theme_business(uuid)','business'),
  ('public.om_sync_bonus_for_attendee(uuid,uuid,text)','internal'))
select s.signature,s.kind,p.prosecdef as security_definer,
  has_function_privilege('anon',p.oid,'EXECUTE') as anon_execute,
  has_function_privilege('authenticated',p.oid,'EXECUTE') as authenticated_execute,
  has_function_privilege('service_role',p.oid,'EXECUTE') as service_execute,
  case when s.kind='wrapper' then position('legal_required_' in pg_get_functiondef(p.oid))>0 else null end as checks_legal_gate,
  (select enabled from public.legal_enforcement_control where singleton=true) as legal_gate_enabled,
  (select count(*) from public.legal_documents where active) as active_legal_documents
from signatures s left join pg_proc p on p.oid=to_regprocedure(s.signature)
order by s.signature;
