-- Additive and rerunnable seed. Existing edits and approvals are preserved.
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('01',1,jsonb_build_object('fr','L’esprit du golf'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('02',2,jsonb_build_object('fr','La sécurité'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('03',3,jsonb_build_object('fr','Bien préparer sa partie'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('04',4,jsonb_build_object('fr','Au départ et sur le fairway'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('05',5,jsonb_build_object('fr','Garder un bon rythme'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('06',6,jsonb_build_object('fr','Dans un bunker'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('07',7,jsonb_build_object('fr','Sur le green'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('08',8,jsonb_build_object('fr','Respecter les autres'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('09',9,jsonb_build_object('fr','Prendre soin du parcours'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('10',10,jsonb_build_object('fr','Se comporter en compétition'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('11',11,jsonb_build_object('fr','Gagner et perdre'))
on conflict (stable_key) do nothing;
insert into public.etiquette_themes(stable_key,position,title_i18n)
values ('12',12,jsonb_build_object('fr','Devenir autonome'))
on conflict (stable_key) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'01.1',1 from public.etiquette_themes where stable_key='01'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Jouer avec honnêteté','Ta balle bouge légèrement pendant que tu la cherches. Personne dans ton groupe ne l’a remarqué, mais toi, tu l’as vue bouger.','L’honnêteté commence précisément quand personne ne peut vérifier ton geste. Au golf, tu appliques toi-même les Règles, y compris les pénalités qui te concernent. Dire ce qui s’est passé permet au groupe de trouver la bonne procédure ; cela ne signifie pas qu’une pénalité s’applique forcément. Une décision transparente vaut plus qu’un score arrangé.','Arrête-toi, décris les faits sans les embellir et demande la procédure adaptée avant de jouer. Si tu ignores la règle, dis-le simplement. Note ensuite le score correspondant à la décision prise.','Se convaincre que « ce n’était presque rien » et jouer vite pour éviter d’en parler. Le silence laisse ensuite un doute sur la position de la balle et sur ton score.','Après une partie, raconte une décision que tu as prise avec honnêteté, même si personne d’autre ne l’avait remarquée.','Propose une situation ambiguë à l’entraînement et laisse le junior exposer les faits avant de discuter de la règle. Valorise la démarche honnête, pas seulement la réponse juridique.','R&A, Règles de golf, règles 1.2a et 1.3b','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='01.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'01.2',2 from public.etiquette_themes where stable_key='01'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Compter ses coups et ses pénalités','Sur un trou, tu joues depuis le départ, puis tu dois rejouer une balle. À l’arrivée au green, tu hésites sur le nombre de coups à annoncer.','Le score d’un trou comprend les coups joués et, selon la situation, les coups de pénalité. Reconstituer le trou dans l’ordre évite d’oublier un coup d’essai qui a réellement frappé la balle, un coup rejoué ou une pénalité. La procédure exacte dépend de ce qui est arrivé : demande de l’aide si tu n’es pas sûr.','Avant d’annoncer ton score, repasse mentalement du départ au trou. Compte chaque coup joué, ajoute les pénalités applicables, puis compare ton décompte avec celui de ton marqueur. En compétition, vérifie les scores trou par trou avant de rendre la carte.','Donner le chiffre qui « semble juste » sans refaire le trajet du trou. Une simple hésitation devient plus difficile à résoudre après la partie.','Sur un trou, explique calmement à ton marqueur comment tu arrives au total annoncé.','Fais raconter un trou fictif avec un dégagement puis un coup rejoué ; demande au junior de séparer coups joués, procédures et pénalités avant d’additionner.','R&A, Règles de golf, règles 1.3b et 3.3b','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='01.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'01.3',3 from public.etiquette_themes where stable_key='01'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Bien réagir après un mauvais coup','Ton approche finit dans un endroit difficile. Tu sens la colère monter alors que tes partenaires attendent leur tour.','Un mauvais coup fait partie du jeu et ne dit rien de ta valeur. Une réaction brusque peut gêner les autres, abîmer le terrain ou devenir dangereuse si le club est lancé. Revenir au calme t’aide aussi à choisir le prochain coup avec lucidité. Tu peux être déçu sans te défouler sur le matériel ou sur quelqu’un.','Pose ton club, éloigne-toi de la zone de jeu immédiate, respire lentement une fois et formule une consigne simple pour la suite : « je retrouve ma balle, puis je décide ». Si tu as besoin d’aide, parle-en au coach ou à ton groupe au bon moment.','Jeter le club, taper le sol ou accuser un partenaire. Ces gestes prolongent la frustration et peuvent mettre les autres en danger.','Essaie une courte routine de retour au calme après un coup raté et observe si elle t’aide à reprendre le jeu.','En séance, entraîne la routine sur un coup volontairement difficile, sans juger l’émotion exprimée. Interviens immédiatement si un geste présente un risque.','R&A, Règles de golf, règle 1.2a ; conseil pédagogique ActiviTee','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='01.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'02.1',1 from public.etiquette_themes where stable_key='02'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Vérifier avant de jouer','Tu arrives sur ta balle près d’un chemin. Un jardinier travaille plus loin et un partenaire s’est arrêté à côté de toi.','Une balle, un club ou même un petit caillou peuvent blesser. Avant chaque coup, il faut regarder autour de la zone du swing et vers la trajectoire possible, y compris au-delà de la cible voulue. Le groupe précédent et le personnel d’entretien doivent être suffisamment éloignés. La sécurité passe avant l’envie de jouer vite.','Regarde derrière, à côté et devant toi. Vérifie que personne n’est à portée de ton club, puis que la zone où la balle pourrait partir est libre. Attends si un doute subsiste et demande au coach quand la visibilité est mauvaise.','Se fier uniquement à la direction dans laquelle on espère envoyer la balle. Un coup manqué peut partir nettement ailleurs.','Avant tes prochains coups, applique à voix basse ta vérification : autour de moi, trajectoire, groupe devant, entretien.','Fais varier la position de partenaires immobiles pendant un exercice sans balle et demande au junior de décider quand il peut jouer.','R&A, Règles de golf, règle 1.2a, sécurité des autres','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='02.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'02.2',2 from public.etiquette_themes where stable_key='02'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Crier « Fore ! »','Ta balle part vers des joueurs que tu n’avais pas vus à côté du fairway. Elle peut atteindre leur zone avant que tu puisses expliquer ce qui s’est passé.','L’alerte doit être immédiate et assez forte pour être entendue. « Fore ! » est le signal traditionnel qui prévient d’une balle dangereuse. Chercher d’abord à savoir si le coup était « vraiment mauvais » fait perdre de précieuses secondes. Prévenir n’efface pas la nécessité de vérifier avant le coup, mais peut aider les personnes exposées à se protéger.','Crie tout de suite « Fore ! » si ta balle risque de toucher quelqu’un, puis répète l’alerte si nécessaire. Avertis également ton groupe, attends que la situation soit sûre et suis les consignes de l’encadrement.','Rester silencieux par gêne ou murmurer seulement à son partenaire. Les personnes sur la trajectoire doivent recevoir l’avertissement.','Explique au coach quand tu donnerais l’alerte ; fais-le dans un exercice parlé, sans lancer de balle ni provoquer une fausse alerte.','Présente plusieurs trajectoires dessinées et demande au junior de désigner celles qui nécessitent l’alerte immédiate.','R&A, Règles de golf, règle 1.2a, avertissement de sécurité','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='02.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'02.3',3 from public.etiquette_themes where stable_key='02'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Réagir lorsqu’une balle arrive vers soi','Tu entends « Fore ! » pendant que ton groupe traverse une zone ouverte. Tu ne sais pas encore d’où vient la balle.','Chercher la balle du regard peut te faire perdre le temps nécessaire pour te protéger. Le signal indique un risque immédiat, même si la trajectoire exacte est inconnue. Le réflexe précis est celui enseigné par l’encadrement pour le terrain et la situation : se protéger rapidement, sans courir vers une trajectoire possible.','Interromps ce que tu fais, protège ta tête et adopte sans attendre la position de protection apprise avec ton coach. Reste ainsi le temps que le danger soit passé. Ensuite seulement, vérifie que chacun va bien et suis les indications de l’encadrement.','Lever les yeux pour chercher la balle ou traverser le fairway au hasard. Ces réactions peuvent t’exposer davantage.','Répète le réflexe avec ton coach dans un exercice sans balle, puis explique pourquoi la protection vient avant la recherche visuelle.','Enseigne une consigne de protection courte et cohérente à tout le groupe ; fais une répétition sans balle dans un espace sûr.','R&A, Règles de golf, règle 1.2a ; consigne de sécurité de l’encadrement','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','club_guidance'
from public.etiquette_cards where stable_key='02.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'03.1',1 from public.etiquette_themes where stable_key='03'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Arriver à l’heure','Ton départ est annoncé à 10 h 00. Tu franchis la porte du club à 9 h 59 avec ton sac encore à récupérer.','L’heure d’arrivée au club n’est pas l’heure à laquelle tu es prêt à jouer. En compétition, l’heure de départ est une donnée de jeu : il faut être prêt au point de départ à l’heure fixée, et la Règle 5.3a prévoit des conséquences en cas de retard. Hors compétition aussi, arriver préparé évite de mettre tout le groupe sous pression.','Prévois le trajet, l’accueil, les chaussures et l’échauffement. Fixe une heure d’arrivée qui te laisse une vraie marge. Avant de partir de chez toi, vérifie le lieu du départ et tout changement communiqué par l’organisateur.','Penser que se trouver sur le parking à l’heure indiquée suffit. Il reste parfois plusieurs étapes avant de pouvoir jouer.','Prépare un petit horaire pour ta prochaine partie, de l’arrivée au club jusqu’au moment où tu seras prêt au départ.','Fais comparer deux horaires réalistes, avec et sans marge. En compétition, montre où l’heure officielle est affichée.','R&A, Règles de golf, règle 5.3a','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='03.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'03.2',2 from public.etiquette_themes where stable_key='03'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Préparer son matériel','Au deuxième trou, tu découvres que tu n’as plus de balle de réserve et que ta gourde est restée au vestiaire.','Une préparation simple te rend autonome et évite les retours inutiles qui ralentissent ton groupe. Le contenu exact dépend de la météo, du parcours et de l’activité. L’idée n’est pas d’avoir un sac rempli, mais de disposer de ce dont tu auras réellement besoin sans gêner les autres.','La veille ou avant de partir, vérifie clubs, balles, tees, relève-pitch si nécessaire, eau et vêtements adaptés. Ajoute la carte de score ou le support demandé. Range les objets de façon à retrouver rapidement ce que tu cherches. Demande à l’encadrement ce qui est fourni.','Tout laisser au dernier moment et emprunter plusieurs objets en pleine partie. Cela peut interrompre le jeu et te distraire.','Prépare ton sac avec une checklist courte que tu pourras réutiliser avant la prochaine partie.','Demande au junior de bâtir sa propre liste selon une météo donnée. Vérifie l’autonomie sans imposer du matériel superflu.','Bonne pratique de préparation ActiviTee','Bonne pratique pédagogique ActiviTee ; relecture éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='03.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'03.3',3 from public.etiquette_themes where stable_key='03'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Lire les consignes locales','Avant la partie, tu vois un panneau sur une zone fermée et une annonce concernant l’interruption du jeu. Tu n’es pas sûr de ce qui s’applique aujourd’hui.','Les règles locales et les consignes d’un parcours complètent les Règles de golf dans un contexte précis. Certaines concernent le jeu ; d’autres concernent la sécurité ou l’accès aux zones. Elles peuvent changer selon l’état du terrain ou la compétition. Les ignorer risque de conduire à une mauvaise décision ou à un danger.','Lis les informations affichées ou communiquées pour ta partie. Repère les zones interdites, les signaux d’interruption et la personne à contacter en cas de doute. Si une consigne te paraît floue, demande avant de jouer plutôt que d’inventer une procédure.','Supposer que la consigne de la semaine précédente est toujours valable, ou confondre une règle locale avec une simple recommandation.','Identifie deux consignes affichées dans ton club et explique à qui tu demanderais une précision.','Montre où le club publie ses consignes et distingue avec le groupe une règle locale de jeu, une interdiction d’accès et une recommandation.','R&A, Règles de golf, règle 1.3a et règles locales du club','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','club_guidance'
from public.etiquette_cards where stable_key='03.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'04.1',1 from public.etiquette_themes where stable_key='04'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Attendre sans gêner','Un partenaire se prépare à jouer depuis le départ. Tu attends avec ton sac près de lui et tu hésites sur l’endroit où te tenir.','Le bon emplacement répond à deux questions : es-tu hors de portée du club et d’une balle mal frappée, et ta présence risque-t-elle de distraire le joueur ? La réponse dépend de l’espace, de la direction du coup et des autres personnes. Un lieu confortable pour toi peut gêner celui qui joue.','Avant que le partenaire se place, recule vers une zone sûre et visible pour le groupe, sans te mettre dans sa ligne de jeu. Garde le matériel immobile. Si tu hésites, demande brièvement où te placer, puis laisse-lui l’espace nécessaire.','Se déplacer au dernier instant juste derrière le joueur ou tout près de sa balle. Même silencieux, un mouvement peut interrompre sa préparation.','Choisis ton emplacement avant qu’un partenaire ne commence sa préparation, puis vérifie qu’il te voit et qu’il est à l’aise.','Mets en scène plusieurs positions d’attente sans swing ni balle et fais expliquer les critères de sécurité et de discrétion.','R&A, Règles de golf, règle 1.2a, sécurité et considération','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='04.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'04.2',2 from public.etiquette_themes where stable_key='04'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Respecter l’ordre de jeu et le ready golf','Sur le fairway, ta balle est plus proche du trou que celle d’un partenaire, mais tu es déjà prêt alors qu’il cherche son club.','L’ordre de jeu dépend de la formule. En stroke play, jouer prêt peut aider le rythme si c’est sûr et responsable ; les joueurs peuvent s’accorder pour le faire. En match play, l’ordre a un rôle différent et un adversaire peut demander qu’un coup joué hors tour soit annulé. Le ready golf n’autorise jamais à jouer vers quelqu’un.','Identifie d’abord la formule de jeu. Si le ready golf convient, annonce clairement que tu es prêt, vérifie que personne ne se trouve sur ta trajectoire et laisse le temps aux autres de s’écarter. En cas de doute, suis l’ordre prévu.','Croire que « je suis prêt » donne toujours priorité, y compris en match play ou quand un autre joueur se trouve devant.','Explique au coach un exemple de ready golf sûr et approprié en stroke play, puis ce qui changerait en match play.','Fais jouer verbalement deux scénarios, un en stroke play et un en match play, avant de laisser les juniors proposer l’ordre.','R&A, Règles de golf, règles 5.6b et 6.4','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='04.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'04.3',3 from public.etiquette_themes where stable_key='04'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Replacer ou réparer un divot','Après ton coup depuis le fairway, un morceau de gazon s’est soulevé. Tu vois aussi une trace près de la balle encore en jeu d’un autre joueur.','Réparer le terrain aide les groupes suivants et l’entretien du parcours. La bonne méthode dépend du type de gazon et des consignes du club : on replace parfois le morceau, ailleurs on utilise un mélange. Avant d’agir près d’une balle encore en jeu, il faut éviter d’améliorer les conditions qui pourraient affecter un coup à venir.','Demande quelle méthode le club recommande. Répare la trace de ton coup après avoir quitté la zone où les joueurs doivent encore jouer, sans modifier la ligne ou l’environnement immédiat d’une balle en jeu. Si la situation est délicate, attends ou demande au coach.','Replacer mécaniquement de la terre sur une zone qu’un partenaire doit encore utiliser, ou laisser le divot sans vérifier la méthode locale.','Demande la méthode du club et répare correctement un divot dans une situation où aucun coup restant ne peut être amélioré.','Montre deux types de surface et rappelle la limite de la Règle 8 avant toute réparation près d’une balle encore à jouer.','R&A, Règles de golf, règles 1.2a et 8.1 ; consignes d’entretien du club','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='04.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'05.1',1 from public.etiquette_themes where stable_key='05'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Être prêt à jouer','Tu attends ton tour sur le fairway. Quand les autres ont fini, tu commences seulement à chercher la distance et à choisir un club.','Une partie avance mieux lorsque chacun prépare son prochain coup pendant les moments disponibles. Cela ne signifie pas se précipiter dans la zone de swing d’un partenaire. Tu peux observer ta balle, estimer la distance et imaginer une option pendant que le groupe se déplace, puis faire ta routine sans retard inutile lorsque la voie est libre.','Entre deux coups, repère ta balle et la zone d’atterrissage souhaitée. Choisis une ou deux options de club pendant l’attente, sans faire de bruit ni te placer devant quelqu’un. Quand c’est ton tour, confirme la sécurité, puis joue.','Attendre d’être appelé pour commencer toute réflexion, ou préparer son coup en marchant dans la trajectoire d’un autre joueur.','Sur trois trous, anticipe ton choix de club pendant une attente sûre, puis note si tu étais prêt au bon moment.','Observe le temps de préparation sans chronométrer chaque junior. Donne une consigne concrète sur ce qui peut être préparé avant son tour.','R&A, Règles de golf, règle 5.6b, recommandations de cadence','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='05.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'05.2',2 from public.etiquette_themes where stable_key='05'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Rester au contact du groupe précédent','Ton groupe termine un trou et le départ suivant est libre. Vous continuez pourtant à discuter derrière le green pendant que le groupe devant s’éloigne.','Le rythme se juge surtout par la place que garde ton groupe sur le parcours. Prendre soin de son coup et avancer efficacement sont compatibles. Un groupe plus rapide derrière vous peut parfois passer, si les conditions et l’organisation du parcours le permettent. La décision se prend avec le groupe et selon les consignes du club.','Après le trou, quitte le green sans traîner et rejoins la zone du prochain départ. Observe l’écart avec le groupe devant. Si votre groupe perd durablement le contact, parle-en au coach ou au responsable ; suivez ensemble la procédure locale pour faciliter éventuellement un passage.','Regarder seulement le groupe derrière et accélérer en oubliant la sécurité, ou refuser tout passage sans tenir compte de l’écart devant.','Avec le coach, observe sur quelques trous où se trouve le groupe précédent et discute d’une action simple pour garder le rythme.','Aide les juniors à lire l’espace devant leur groupe et à distinguer attente normale, retard évitable et situation où un passage est adapté.','R&A, Règles de golf, règle 5.6b, recommandations de cadence','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='05.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'05.3',3 from public.etiquette_themes where stable_key='05'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Chercher une balle sans bloquer le parcours','Une balle part dans une zone d’herbes hautes. Plusieurs joueurs marchent dans des directions différentes sans se souvenir de son point de chute.','Un repère visuel rend la recherche plus efficace. Selon la Règle 18.2a, une balle est perdue si elle n’est pas trouvée dans les trois minutes après le début de la recherche par le joueur ou son cadet. Ce délai réglementaire n’est pas une invitation à chercher longtemps avant d’organiser le groupe. D’autres procédures, dont une balle provisoire, peuvent dépendre de la situation.','Regarde la trajectoire jusqu’au sol et retiens un arbre, une borne ou une pente proche. Cherchez méthodiquement dans la zone probable, sans piétiner inutilement. Faites appel au coach si la balle n’est pas retrouvée et appliquez la procédure correcte avant de poursuivre.','Courir tous au hasard, perdre le repère initial ou continuer la recherche après le délai applicable en supposant que le score n’en sera pas affecté.','Suis visuellement une balle jouée par un partenaire et mémorise un repère de chute que tu pourras lui indiquer.','Utilise un exercice de trajectoire sans balle perdue pour travailler les repères, puis explique quand le délai de trois minutes commence.','R&A, Règles de golf, règles 18.2a et 18.3','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='05.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'06.1',1 from public.etiquette_themes where stable_key='06'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Entrer au bon endroit','Ta balle repose au milieu d’un bunker. Le chemin le plus court passe par un bord abrupt et fragile.','Le bord d’un bunker peut s’effriter sous les chaussures et rendre la sortie dangereuse. Un accès légèrement plus long préserve la forme du terrain et évite de laisser des traces difficiles à réparer. Chaque bunker a sa géométrie ; il n’existe pas un point d’entrée identique partout.','Observe les accès possibles avant de descendre. Choisis un côté bas et stable si le terrain le permet, en restant attentif aux autres joueurs et aux balles. Rejoins ta balle par un trajet simple que tu pourras ratisser en repartant. Demande une autre solution si l’accès paraît glissant ou dangereux.','Sauter depuis le bord le plus haut pour gagner quelques pas. Cela peut endommager la lèvre du bunker et te faire perdre l’équilibre.','Avec ton coach, repère un accès approprié à un bunker d’entraînement et explique ton choix.','Fais comparer plusieurs accès depuis l’extérieur et prends en compte l’état du sable, le bord et la sécurité avant d’entrer.','R&A, Règles de golf, règle 1.2a, soin du parcours ; conseil d’entretien du club','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='06.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'06.2',2 from public.etiquette_themes where stable_key='06'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Ratisser toutes ses traces','Tu sors du bunker après un coup difficile. Tes pas et la trace de ton swing restent dans le sable derrière toi.','Une surface laissée irrégulière peut compliquer le coup du groupe suivant. Le râteau sert à rendre au sable un état aussi régulier que possible, en suivant la méthode du club. Pendant qu’une balle est encore en jeu dans le bunker, certaines actions peuvent affecter les conditions de jeu : en cas de doute, demande avant de ratisser près de cette balle.','Quand ton jeu dans cette zone est terminé et que tu ne risques pas d’améliorer un coup restant, ratisse tes pas, la trace du coup et le chemin de sortie. Tire le sable avec des gestes réguliers, puis vérifie la surface en te retournant.','Ratisser seulement l’endroit de la balle et laisser une chaîne d’empreintes. À l’inverse, ratisser autour d’une balle encore à jouer sans vérifier peut créer un problème de règles.','Après ton prochain passage dans un bunker d’entraînement, ratisse tes traces de pas et la zone du coup, puis regarde le résultat.','Montre une sortie complète et demande au junior d’identifier toutes les traces. Évoque la Règle 8 pour les situations près d’une balle encore en jeu.','R&A, Règles de golf, règles 1.2a, 8 et 12','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='06.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'06.3',3 from public.etiquette_themes where stable_key='06'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Quitter le bunker sans l’endommager','Tu as bien ratissé la zone du coup, mais tu dois encore remonter par une pente fragile. Le râteau est posé à côté de la sortie.','Le soin du bunker continue jusqu’à ce que tu sois complètement sorti. Les derniers pas peuvent recréer des traces et un appui sur un bord fragile peut le casser. La place du râteau n’est pas universelle : elle dépend des consignes du club et parfois du dessin du bunker.','Reprends le chemin d’accès le plus stable. Ratisse les dernières empreintes au fur et à mesure, sors sans prendre appui sur la lèvre fragile, puis replace le râteau là où le club le demande. Depuis l’extérieur, regarde une dernière fois si ton passage est visible.','Quitter le bunker en laissant les dernières empreintes près de la sortie ou ranger le râteau à une place supposée valable partout.','Vérifie derrière toi l’état du bunker et la place du râteau selon la consigne locale.','Demande aux juniors où le club veut les râteaux et fais observer la sortie depuis l’extérieur avant de conclure l’exercice.','R&A, Règles de golf, règle 1.2a ; consignes d’entretien du club','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','club_guidance'
from public.etiquette_cards where stable_key='06.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'07.1',1 from public.etiquette_themes where stable_key='07'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Relever un pitch','Ta balle tombe sur le green et laisse une petite marque. Plus loin, tu remarques un autre impact qui n’a pas été réparé.','Une marque d’impact non réparée peut gêner les putts suivants et abîmer durablement la surface. Le bon geste consiste à rapprocher doucement les bords de la marque selon la méthode enseignée par le club, sans soulever la terre du fond. La Règle 13.1c autorise la réparation de certains dommages sur le green, notamment les impacts de balle.','Repère la marque, utilise l’outil adapté et fais d’abord vérifier ton geste par un coach ou un adulte compétent. Travaille délicatement les bords vers le centre puis lisse avec le putter. Répare une autre marque seulement si tu peux le faire sans gêner le groupe ni retarder le jeu.','Soulever le centre de l’impact avec l’outil. Ce geste peut casser les racines et laisser une bosse plus difficile à réparer.','Fais vérifier ta technique, puis répare un impact supplémentaire sur un green où tu peux intervenir sans gêner le jeu.','Montre le geste sur une surface d’exercice et corrige la direction du mouvement avant de confier un impact réel au junior.','R&A, Règles de golf, règle 13.1c','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='07.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'07.2',2 from public.etiquette_themes where stable_key='07'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Respecter les lignes de jeu','Deux partenaires préparent leur putt. Pour rejoindre ta balle, le trajet le plus direct te ferait passer entre l’une de leurs balles et le trou.','Se déplacer devant quelqu’un qui vise ou projeter son ombre sur sa ligne peut le distraire. Le respect des lignes de jeu est surtout une question de considération et d’organisation. Il ne faut pas transformer cela en ancienne interdiction générale de toucher une ligne de putt : les Règles actuelles traitent plutôt les actions qui améliorent les conditions d’un coup.','Observe les balles, le trou et les joueurs avant de marcher. Contourne les lignes de putt lorsque c’est simple, reste immobile pendant leur préparation et déplace ton ombre si elle gêne. Demande où passer lorsque l’espace est réduit.','Traverser rapidement devant un joueur en pensant que la vitesse rend le passage invisible, ou annoncer à tort qu’un simple contact sur la ligne crée toujours une pénalité.','Choisis un trajet respectueux autour des lignes de putt de ton groupe et explique ton choix à un partenaire.','Dessine plusieurs lignes de putt et propose des déplacements possibles ; distingue discrétion et véritable amélioration des conditions de jeu.','R&A, Règles de golf, règles 1.2a, 8 et 13','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='07.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'07.3',3 from public.etiquette_themes where stable_key='07'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Manipuler le drapeau et protéger le trou','Ton groupe arrive sur le green. Un partenaire veut putter avec le drapeau en place, un autre envisage de le retirer.','La Règle 13.2 laisse des choix concernant le drapeau ; le groupe doit se coordonner avant chaque coup. Une manipulation brusque peut abîmer le bord du trou ou distraire celui qui putte. Le plus important est de respecter le choix du joueur et de garder le green en bon état.','Demande au joueur ce qu’il souhaite avant qu’il se prépare. Si le drapeau doit être retiré, attends le bon moment, tiens-le sans gêner et pose-le hors des lignes utiles. Replace-le verticalement et doucement quand le groupe a terminé, sans appuyer sur le bord du trou.','Retirer le drapeau au dernier instant sans prévenir ou le laisser tomber contre le trou. Ces gestes peuvent perturber le coup et marquer le green.','Quand le groupe en a besoin, retire puis replace soigneusement le drapeau avec l’accord des partenaires.','Fais répéter la coordination verbale avant le putt et le geste de remise en place sans balle, puis laisse les juniors agir en situation.','R&A, Règles de golf, règle 13.2','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='07.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'08.1',1 from public.etiquette_themes where stable_key='08'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Garder le silence au bon moment','Un partenaire commence sa routine avant un coup important. Ton téléphone vibre et tu racontes encore le trou précédent.','Le golf reste un jeu social : il n’est pas nécessaire de se taire pendant toute la partie. Mais au moment où quelqu’un prépare et joue son coup, une voix, une sonnerie ou un bruit de fermeture de sac peut casser sa concentration. Tenir compte de l’autre aide le groupe à jouer dans de bonnes conditions.','Mets ton téléphone en mode adapté à l’activité. Termine la conversation avant la routine du joueur, immobilise ton matériel et attends la fin de son coup pour reprendre. Si tu dois traiter une urgence, éloigne-toi dans une zone sûre et préviens le groupe.','Penser que parler doucement juste derrière le joueur ne le dérange pas, ou commencer à ranger des clubs pendant qu’il vise.','Pendant les coups de ton groupe, prépare un environnement calme : téléphone discret, matériel immobile et conversations au bon moment.','Fais écouter au groupe quelques bruits ordinaires de matériel et demande lesquels sont gênants pendant une routine de coup.','R&A, Règles de golf, règle 1.2a, considération envers les autres','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='08.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'08.2',2 from public.etiquette_themes where stable_key='08'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Bien se placer','Tu es à distance de sécurité, mais ton ombre traverse la zone où un partenaire veut putter. Tu changes de place pendant qu’il vise.','Être hors de danger ne suffit pas toujours pour respecter la concentration des autres. Un mouvement dans le champ de vision, une ombre qui bouge ou une présence directement derrière le joueur peuvent le distraire. Cette fiche complète la vérification de sécurité : elle concerne surtout le confort visuel et le calme du joueur.','Avant sa routine, observe la lumière et la direction du coup. Mets-toi sur le côté, à une distance confortable, puis reste immobile jusqu’à la fin. Si le partenaire te demande de bouger, fais-le avant qu’il reprenne sa préparation.','Se déplacer lentement pendant le backswing en croyant que cela ne se voit pas. Même sans bruit, le mouvement peut gêner.','Demande à un partenaire si l’emplacement choisi le gêne et ajuste-toi avant qu’il joue.','Place les juniors à plusieurs endroits sûrs et demande au joueur de décrire ce qu’il voit. Fais corriger avant le coup, sans humilier celui qui s’est trompé.','R&A, Règles de golf, règle 1.2a, considération envers les autres','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='08.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'08.3',3 from public.etiquette_themes where stable_key='08'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Encourager sans distraire','Une partenaire vient de rater un putt. Tu veux l’aider, mais elle se prépare déjà à jouer le coup suivant.','Un encouragement peut soutenir le groupe s’il arrive au bon moment et respecte la personne. Pendant la préparation d’un coup, même un compliment peut distraire. En compétition, indiquer un club ou une stratégie peut aussi constituer un conseil au sens de la Règle 10.2 ; un mot de soutien général est différent d’une instruction technique.','Attends que le coup soit terminé et que la joueuse soit disponible. Dis quelque chose de simple et sincère, comme « bien récupéré » ou « on continue ». Évite de commenter chaque geste. Garde les conseils techniques pour les moments et les formats où ils sont autorisés.','Donner une consigne de jeu non demandée au moment du swing ou affirmer qu’un encouragement ordinaire est toujours un conseil interdit.','Après un coup, adresse un encouragement simple à un partenaire et observe s’il le reçoit bien.','Mets en scène des phrases de soutien et des consignes techniques ; demande au groupe de repérer la différence selon le contexte de jeu.','R&A, Règles de golf, règles 1.2a et 10.2a','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='08.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'09.1',1 from public.etiquette_themes where stable_key='09'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Respecter les zones protégées','Ta balle semble avoir franchi une corde qui protège une zone humide. Tu pourrais la récupérer en quelques pas si tu passais sous la corde.','Une zone signalée peut protéger la nature, une partie fragile du parcours ou les personnes. La corde ou le panneau fixe une limite d’accès qu’il faut respecter, même si la balle est visible. La procédure de jeu dépend de la façon dont cette zone est définie dans les règles locales et les consignes du jour.','Reste hors de la zone. Lis la signalétique et appelle le coach ou la personne compétente pour savoir comment poursuivre le jeu. Accepte de laisser la balle si l’accès est interdit. Réfléchis à ce que la protection permet de préserver avant de passer au coup suivant.','Entrer rapidement parce que « personne ne regarde », ou appliquer de mémoire une procédure de dégagement qui ne correspond pas à cette zone.','Identifie une zone protégée de ton club, puis explique à quoi sert l’interdiction d’y entrer.','Présente la signalétique réelle du club et fais distinguer la restriction d’accès de la procédure de jeu éventuellement prévue par la règle locale.','Règles locales et consignes de protection du club','Consignes locales du club à vérifier pour chaque partie','club_guidance'
from public.etiquette_cards where stable_key='09.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'09.2',2 from public.etiquette_themes where stable_key='09'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Bien utiliser son sac et son chariot','Tu arrives près d’un green avec ton chariot. Le prochain départ se trouve derrière le green, mais tu laisses ton matériel devant l’entrée.','Un sac posé au mauvais endroit peut gêner les putts, bloquer le passage ou obliger le groupe à revenir sur ses pas. Certains clubs interdisent les chariots sur le green, les départs ou des zones humides. Bien préparer sa sortie aide le rythme sans sacrifier le soin du terrain.','Avant de rejoindre ta balle, repère le chemin autorisé vers le départ suivant. Place ton sac ou ton chariot à l’extérieur des zones interdites, du côté de la sortie, sans couper la trajectoire d’un autre joueur. En repartant, vérifie que tu n’as rien laissé.','Traverser le green avec le chariot parce que le prochain départ paraît proche, ou laisser le sac sur la route des autres groupes.','Sur un trou, place ton matériel vers le prochain départ dans une zone autorisée et observe si le départ du green devient plus simple.','Montre les cheminements locaux et demande au junior de choisir un emplacement qui respecte à la fois le terrain et le jeu du groupe.','Consignes de circulation et d’entretien du club','Consignes locales du club à vérifier pour chaque partie','club_guidance'
from public.etiquette_cards where stable_key='09.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'09.3',3 from public.etiquette_themes where stable_key='09'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Ne laisser aucun déchet','Après une collation, ton emballage glisse d’une poche du sac. Plus loin, tu vois aussi un objet inconnu près du chemin.','Un parcours propre est plus agréable et plus sûr pour les joueurs, le personnel et les animaux. Garder ses propres déchets est une responsabilité simple. Ramasser un objet inconnu n’est pas toujours une bonne idée : il peut être coupant, sale ou dangereux. Savoir demander de l’aide fait aussi partie du soin du terrain.','Garde tes emballages et petits déchets dans une poche fermée jusqu’à une poubelle. Avant de quitter une zone, regarde autour de ton sac. Si tu vois un objet inconnu ou potentiellement dangereux, ne le touche pas et signale-le à un adulte ou au personnel du club.','Laisser un petit déchet en se disant que le vent ou l’équipe d’entretien s’en chargera, ou toucher sans précaution un objet suspect.','Repars avec tous tes déchets ; pour un objet inconnu, coupant ou dangereux, demande de l’aide au lieu de le ramasser.','Prévois une poche à déchets dans le sac de démonstration et explique les cas dans lesquels un junior doit seulement signaler un objet.','R&A, Règles de golf, règle 1.2a, soin du parcours ; consignes du club','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='09.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'10.1',1 from public.etiquette_themes where stable_key='10'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Respecter partenaires et adversaires','Tu arrives à une compétition et rejoins des joueurs que tu ne connais pas. Plus tard, un score serré rend les échanges tendus.','Un groupe joue mieux quand chacun connaît les autres et communique clairement. Le respect ne dépend ni du score ni de la formule : il vaut pour les partenaires comme pour les adversaires. Tu peux exprimer un doute sur un fait ou une règle sans attaquer la personne. Les conditions de compétition peuvent aussi comporter un code de conduite précis.','Présente-toi avant le départ, écoute les noms et annonce clairement les informations nécessaires au jeu. En cas de désaccord, décris ce que tu as vu, laisse l’autre répondre et sollicite la personne compétente si besoin. Termine les échanges avec la même courtoisie que tu souhaites recevoir.','Faire une remarque blessante sous pression ou supposer qu’un adversaire cherche à tricher simplement parce qu’il a une autre lecture de la situation.','Commence ta prochaine partie par une présentation cordiale à chaque personne du groupe.','Fais répéter un désaccord factuel en deux versions, l’une accusatrice et l’autre précise et respectueuse ; discute de leurs effets.','R&A, Règles de golf, règle 1.2a','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='10.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'10.2',2 from public.etiquette_themes where stable_key='10'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Demander de l’aide en cas de doute','Une balle repose près d’une zone marquée et ton groupe hésite sur la bonne procédure. Personne n’est entièrement sûr de la limite.','Inventer une réponse rapide peut mener à jouer du mauvais endroit ou à enregistrer un score incorrect. Une bonne question de règle commence par les faits : où est la balle, quelle formule se joue, quels marquages sont visibles et que s’est-il passé ? En compétition, les procédures de la Règle 20 permettent de demander une décision selon le contexte.','Arrête-toi avant d’agir sur la balle. Décris la situation sans suggérer la réponse qui t’arrange, puis contacte le coach, l’arbitre ou le comité selon l’activité. Note les faits utiles. Si le jeu doit continuer, suis la procédure indiquée par la personne compétente.','Déplacer la balle d’abord puis demander ensuite si c’était permis. Les faits deviennent plus difficiles à vérifier.','À partir d’une situation d’entraînement, formule une question de règle avec les faits nécessaires et le bon interlocuteur.','Prépare un cas incomplet et fais demander aux juniors les informations manquantes avant de proposer une décision.','R&A, Règles de golf, règle 20','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='10.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'10.3',3 from public.etiquette_themes where stable_key='10'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Comprendre le code de conduite','Le règlement de ton tournoi mentionne un code de conduite. Tu te demandes si toutes les recommandations habituelles du club entraînent automatiquement une pénalité.','La Règle 1.2 décrit un comportement attendu de tous les joueurs. Un comité peut aussi adopter un code de conduite pour une compétition et définir des pénalités pour des manquements précis. Une recommandation générale de politesse n’est donc pas automatiquement une infraction pénalisée. Lire le document du tournoi évite de confondre ces niveaux.','Avant le départ, repère le code applicable, ses exemples concrets et la personne qui répond aux questions. Si un incident survient, explique les faits et demande comment le code s’applique. Continue à respecter les autres même quand aucun barème de pénalité n’est prévu.','Attribuer une pénalité à toute maladresse d’étiquette, ou croire qu’un code écrit remplace toutes les Règles de golf.','Repère où trouver le code de conduite de ton club ou d’un tournoi, puis cite une règle de comportement qu’il prévoit réellement.','Compare une attente générale de la Règle 1.2a avec une disposition d’un code de conduite local, sans inventer de sanction.','R&A, Règles de golf, règle 1.2b','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','code'
from public.etiquette_cards where stable_key='10.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'11.1',1 from public.etiquette_themes where stable_key='11'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Féliciter les autres','Un partenaire réussit un coup difficile alors que tu viens de perdre un trou. Tu ressens d’abord ta propre déception.','Reconnaître un beau geste ou un effort ne retire rien à ton envie de bien jouer. Un mot juste peut rendre la partie plus agréable, surtout quand le résultat est serré. Il n’est pas nécessaire d’en faire trop ni de prétendre que tu n’es pas déçu. La sincérité compte davantage qu’une formule automatique.','Attends que le coup soit terminé et que le joueur soit disponible. Félicite un élément précis si tu l’as remarqué : le choix prudent, la récupération ou le putt réussi. Après une victoire, laisse aussi à l’autre le temps de digérer son résultat.','Rester muet uniquement parce que l’autre a gagné, ou multiplier les compliments ironiques qui ressemblent à des reproches.','Félicite sincèrement un autre joueur pour un effort, un beau coup ou une victoire que tu as observés.','Invite les juniors à distinguer un compliment précis d’une formule de politesse forcée, puis respecte leur manière naturelle de s’exprimer.','R&A, Règles de golf, règle 1.2a ; conseil pédagogique ActiviTee','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='11.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'11.2',2 from public.etiquette_themes where stable_key='11'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Maîtriser ses émotions','La partie se termine et ton score est bien moins bon que prévu. Tu as envie de dire que tout a été raté.','Un résultat final mélange beaucoup de coups, de décisions et de circonstances. Il peut être décevant sans résumer toute ta journée. Prendre du recul aide à apprendre et à parler aux autres avec respect. Cette étape concerne l’après-partie ; elle est différente du réflexe de sécurité immédiatement après un mauvais coup.','Éloigne-toi un instant du score si nécessaire, puis nomme honnêtement ce que tu ressens. Choisis un point qui a fonctionné et un objectif concret pour la prochaine séance. Si la frustration reste forte, demande à ton coach un échange au calme avant de juger ton jeu.','Décharger sa déception sur un partenaire, un arbitre ou un bénévole, ou conclure qu’une seule carte définit ton niveau.','Après la partie, note un point positif précis et un objectif simple que tu aimerais travailler.','Fais un débrief bref qui sépare résultat, émotions et comportement ; laisse au junior le choix de partager ou non son ressenti au groupe.','R&A, Règles de golf, règle 1.2a ; conseil pédagogique ActiviTee','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='11.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'11.3',3 from public.etiquette_themes where stable_key='11'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Respecter arbitres, coaches et bénévoles','Une décision d’arbitrage ne te plaît pas. Un bénévole te demande en même temps de libérer une zone pour le groupe suivant.','Ces personnes contribuent à la sécurité et au bon déroulement de l’activité. Tu peux demander une explication sur une décision sans hausser le ton ni couper la parole. Écouter d’abord permet de comprendre la situation ; remercier reconnaît le travail souvent invisible derrière une partie ou un tournoi.','Laisse la personne terminer, reformule ce que tu as compris et pose une question factuelle si un point reste obscur. Suis les indications de sécurité sans attendre. À la fin, remercie au moins une personne pour une aide concrète, même si ton résultat t’a déçu.','Confondre désaccord et manque de respect, ou ignorer une consigne parce qu’elle vient d’un bénévole plutôt que d’un arbitre.','Remercie une personne qui a contribué au déroulement de ta prochaine activité et précise ce que son aide a permis.','Joue une demande d’explication calme après une décision difficile ; laisse les juniors pratiquer une question précise et une réponse respectueuse.','R&A, Règles de golf, règle 1.2a ; code de conduite applicable le cas échéant','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='11.3'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'12.1',1 from public.etiquette_themes where stable_key='12'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','La checklist avant la partie','Demain, tu joues sur un parcours que tu connais peu. Tu as l’horaire du départ, mais tu n’as pas encore vérifié la météo ni les consignes du jour.','L’autonomie commence avant le premier coup. Préparer séparément le matériel, l’heure, la formule et les consignes réduit les oublis. Une checklist personnelle fonctionne mieux qu’une liste interminable copiée : elle doit te permettre de trouver en quelques secondes ce qui manque encore.','La veille, note ton heure d’arrivée et le lieu du départ. Vérifie la formule de jeu, l’équipement nécessaire et les consignes locales. Prépare ton sac, puis garde une petite marge pour un changement de météo ou de trajet. Demande au coach ce qui reste flou avant le départ.','Cocher « matériel prêt » alors que tu n’as pas vérifié les objets essentiels, ou penser que connaître le parcours dispense de lire les consignes actualisées.','Prépare ta prochaine partie avec une checklist personnelle de quelques points et révise-la après usage.','Laisse le junior choisir ses rubriques ; vérifie seulement que sécurité, horaire, matériel, formule et consignes sont couverts.','R&A, Règles de golf, règles 5.3a et 1.3a ; bonne pratique ActiviTee','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='12.1'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'12.2',2 from public.etiquette_themes where stable_key='12'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Les bons réflexes pendant le tour','Au milieu de la partie, tu dois à la fois jouer ton prochain coup, laisser passer un partenaire et prendre soin d’une trace sur le terrain.','Les bons réflexes ne sont pas une suite de tâches à faire toutes en même temps. Sécurité d’abord, puis respect des autres, rythme du groupe et soin du parcours au moment adapté. Selon la situation, tu attends avant de réparer une trace pour ne pas modifier les conditions d’un coup encore à jouer. Savoir choisir l’ordre des gestes montre une vraie autonomie.','Avant chaque coup, vérifie la zone. Pendant l’attente, prépare ta décision sans gêner. Après ton coup et lorsque c’est permis, prends soin de la surface utilisée. Entre les coups, avance avec ton groupe. Si deux exigences semblent se contredire, arrête-toi et demande au coach.','Vouloir aller vite au point de jouer sans vérifier la sécurité, ou réparer immédiatement une zone proche d’une balle encore en jeu.','Sur trois trous, choisis un réflexe de sécurité, un de respect, un de rythme et un de soin du parcours, puis essaie de les appliquer.','Observe des situations réelles et invite le junior à expliquer l’ordre de ses décisions sans transformer la mission en contrôle obligatoire.','R&A, Règles de golf, règles 1.2a, 5.6b et 8 ; bonne pratique ActiviTee','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','good_practice'
from public.etiquette_cards where stable_key='12.2'
on conflict (card_id,version,locale) do nothing;
insert into public.etiquette_cards(theme_id,stable_key,position)
select id,'12.3',3 from public.etiquette_themes where stable_key='12'
on conflict (stable_key) do nothing;
insert into public.etiquette_card_versions(card_id,version,locale,title,situation,simple_explanation,action_text,common_mistake,mission_text,coach_tip,official_reference,reference_version,reference_kind)
select id,1,'fr','Après la partie','Tu as terminé le dernier trou. Le groupe se dirige vers le club-house, mais ta carte n’est pas encore vérifiée et ton matériel reste dispersé.','La fin du jeu comporte encore des gestes utiles. En stroke play, les obligations de la carte de score et de sa remise dépendent du cadre de compétition ; il faut suivre les instructions du comité. Remercier les autres et ranger son matériel font partie d’une fin de partie respectueuse. Un bref bilan aide à retenir une chose apprise sans réduire la journée au résultat.','Avant de te disperser, vérifie les scores et les formalités demandées pour ta formule. Remercie le groupe, récupère tous tes objets et laisse l’espace propre. Une fois au calme, note un moment réussi et une question à poser lors de la prochaine séance.','Partir sans vérifier la carte en compétition, oublier ses affaires près du green ou transformer le débrief en liste de reproches.','Réalise ta routine de fin de partie, avec l’aide adaptée à ton autonomie : score, remerciements, matériel et bref bilan.','Montre la procédure de remise de carte propre à l’épreuve et laisse le junior faire seul les étapes qu’il maîtrise déjà.','R&A, Règles de golf, règle 3.3b ; conditions de compétition du comité','R&A, Règles de golf en vigueur depuis 2023 ; vérification éditoriale requise','rule'
from public.etiquette_cards where stable_key='12.3'
on conflict (card_id,version,locale) do nothing;
