-- Complete editorial draft for series 2: the teeing area. Content remains
-- non-publishable until reviewed by a qualified golf rules official.

with content(stable_key,situation,simple_explanation,action_text,common_mistake,coach_tip,official_reference,illustration_prompt,image_alt) as (values
('junior-rule-07',$t$Au départ, Emma hésite : sa balle est près du bord extérieur d’un repère et ses pieds sont devant les marques.$t$,$t$La zone de départ est un rectangle profond de deux longueurs de club. Son bord avant relie les points les plus avancés des deux marques et ses côtés partent vers l’arrière. La balle est dans la zone si une partie la touche ou la surplombe ; le joueur peut se tenir en dehors.$t$,$t$Je repère le bord avant entre les marques, j’imagine les côtés et je mesure deux longueurs de club vers l’arrière. Je vérifie la balle, pas la position de mes pieds.$t$,$t$Tracer la limite au centre des marques, croire que les pieds doivent être dans la zone ou confondre la zone avec toute l’aire tondue du départ.$t$,$t$Matérialisez le rectangle avec quatre ficelles et déplacez une balle sur ses bords. Faites juger plusieurs positions en regardant la balle depuis le dessus.$t$,'Définition « Zone de départ » ; Règle 6.2b(1)',$t$Vue aérienne de deux marques de départ et d’un rectangle discret de deux longueurs de club vers l’arrière, plusieurs positions de balle près des limites, style ActiviTee, sans texte.$t$,$t$Vue aérienne de la zone rectangulaire située entre deux marques de départ et s’étendant vers l’arrière.$t$),
('junior-rule-08',$t$En stroke play, Lucas place toute sa balle quelques centimètres devant la ligne reliant les bords avant des marques puis joue.$t$,$t$Pour commencer un trou, la balle doit être jouée depuis l’intérieur de la zone de départ. En stroke play, jouer entièrement devant les marques entraîne la pénalité générale et le joueur doit corriger en rejouant depuis la zone. En match play, il n’y a pas de pénalité, mais l’adversaire peut annuler le coup.$t$,$t$Avant de jouer, je regarde la balle depuis le côté ou le dessus. En stroke play, si j’ai joué hors de la zone, j’annonce l’erreur et je la corrige avant de commencer le trou suivant.$t$,$t$Croire que les pieds devant les marques rendent le coup irrégulier, ou continuer avec la première balle en stroke play sans corriger.$t$,$t$Placez une balle dedans, sur la ligne et entièrement devant. Faites distinguer la position de la balle de celle du joueur, puis comparez stroke play et match play.$t$,'Règle 6.1b',$t$Vue latérale et aérienne d’une balle entièrement devant la ligne des bords avant de deux marques de départ, jeune joueur encore en position de départ, sans texte.$t$,$t$Une balle est placée entièrement devant la ligne reliant les bords avant des marques de départ.$t$),
('junior-rule-09',$t$Pour garder la balle basse face au vent, Chloé veut la poser directement sur l’herbe de la zone de départ, sans tee.$t$,$t$Dans la zone de départ, la balle peut être jouée depuis un tee conforme placé dans ou sur le sol, ou directement depuis le sol. Le sol comprend aussi du sable ou d’autres matières naturelles mises en place pour poser la balle.$t$,$t$Je choisis un tee conforme ou je pose ma balle sur le sol dans la zone. Je vérifie qu’une partie de la balle reste dans la zone.$t$,$t$Penser qu’un tee est obligatoire, utiliser un objet non conforme comme support ou poser la balle sur le sol en dehors de la zone.$t$,$t$Faites essayer un départ sur tee, sur herbe et sur un petit monticule de sable. Reliez le choix à la stratégie, sans présenter une option comme obligatoire.$t$,'Règle 6.2b(2)',$t$Trois préparations côte à côte dans une zone de départ : balle sur tee, balle sur herbe et balle sur petit monticule de sable, style ActiviTee, sans texte.$t$,$t$Dans une zone de départ, trois balles sont préparées sur un tee, sur l’herbe et sur un petit monticule de sable.$t$),
('junior-rule-10',$t$Juste avant le coup de Max, sa balle tombe toute seule du tee. Il n’a pas encore essayé de la frapper.$t$,$t$Au début d’un trou, une balle posée dans la zone de départ n’est pas en jeu avant qu’un coup soit joué. Si elle tombe ou est déplacée avant le coup, elle peut être replacée sur un tee, n’importe où dans la zone, sans pénalité.$t$,$t$Je replace ou retee la balle dans la zone sans ajouter de pénalité. Si j’ai réellement tenté de la frapper, je compte le coup et j’applique la situation qui en résulte.$t$,$t$Compter automatiquement un coup lorsque la balle tombe, ou confondre un mouvement d’essai avec une véritable intention de frapper.$t$,$t$Montrez trois scènes : balle tombée seule, balle touchée pendant un mouvement d’essai et air-shot intentionnel. Faites expliquer pourquoi seuls les coups intentionnels comptent.$t$,'Règle 6.2b(5)-(6)',$t$Balle venant de tomber d’un tee dans la zone de départ, jeune golfeur arrêté avant son coup, tee encore visible, style ActiviTee, sans texte.$t$,$t$Une balle est tombée de son tee avant que le jeune golfeur ne tente de la frapper.$t$),
('junior-rule-11',$t$En stroke play, Jade est prête tandis que le joueur qui devrait jouer cherche encore un gant. Elle peut jouer sans danger ni gêne.$t$,$t$L’ordre normal au départ dépend de l’honneur, puis la balle la plus éloignée du trou se joue d’abord. En stroke play, il n’y a normalement pas de pénalité pour jouer hors tour et le Ready Golf est encouragé lorsqu’il est sûr, responsable et ne donne pas volontairement un avantage.$t$,$t$Je vérifie que personne ne risque d’être touché ou gêné, puis j’annonce calmement que je suis prêt à jouer. Si le joueur dont c’est le tour veut jouer, j’attends.$t$,$t$Utiliser le Ready Golf pour se précipiter, jouer devant quelqu’un qui se prépare ou croire que la même souplesse s’applique automatiquement en match play.$t$,$t$Simulez un groupe de trois joueurs avec des rythmes différents. Faites choisir quand le Ready Golf fait gagner du temps sans compromettre sécurité, concentration ni équité.$t$,'Règle 6.4b',$t$Trois juniors au départ, une joueuse prête et en sécurité tandis qu’un autre ajuste son gant loin de la ligne de jeu, style ActiviTee, sans texte.$t$,$t$Une joueuse prête attend de vérifier la sécurité pendant qu’un autre joueur ajuste son gant au départ.$t$),
('junior-rule-12',$t$Le premier coup d’Arthur part vers des buissons proches des limites. Sa balle pourrait être perdue hors d’une zone à pénalité.$t$,$t$Pour gagner du temps, une balle provisoire peut être jouée si l’originale risque d’être perdue hors d’une zone à pénalité ou hors limites. Avant le coup, le joueur doit dire « provisoire » ou annoncer clairement qu’il applique la Règle 18.3.$t$,$t$Avant de rejouer, j’annonce clairement « Je joue une balle provisoire ». Depuis la zone de départ, je peux la jouer d’un tee ou du sol, n’importe où dans cette zone.$t$,$t$Dire seulement « j’en remets une », jouer avant l’annonce, ou jouer une provisoire lorsque la balle est certainement perdue uniquement dans une zone à pénalité.$t$,$t$Faites pratiquer une annonce courte à voix haute puis demandez aux juniors de décider, selon trois trajectoires, si une provisoire est autorisée.$t$,'Règle 18.3 ; Règle 6.2b',$t$Jeune joueur au départ montrant une seconde balle à son groupe après un premier coup vers des buissons et des piquets blancs, style ActiviTee, sans texte.$t$,$t$Un jeune joueur annonce une seconde balle au groupe après un coup parti vers des buissons proches de piquets blancs.$t$)
)
update public.rules_card_versions cv set situation=content.situation,simple_explanation=content.simple_explanation,
 action_text=content.action_text,common_mistake=content.common_mistake,coach_tip=content.coach_tip,
 official_reference=content.official_reference,reference_version='R&A Rules of Golf 2023 + Additional Clarifications 2026-07-01',
 illustration_prompt=content.illustration_prompt,image_alt=content.image_alt,image_status='pending',
 human_review_required=true,approved_by=null,approved_at=null
from content join public.rules_cards c on c.stable_key=content.stable_key
where cv.card_id=c.id and cv.version=1 and cv.locale='fr';

do $migration$
declare v_card_key text;v_kind text;v_variant integer;v_prompt text;v_explanation text;v_visual text;v_alt text;
 v_options jsonb;v_version_id uuid;v_question_id uuid;v_option jsonb;v_position integer;
begin
for v_card_key,v_kind,v_variant,v_prompt,v_explanation,v_visual,v_alt,v_options in select * from (values
('junior-rule-07','practice',1,$q$Une petite partie de ta balle surplombe le bord de la zone de départ. Est-elle dans la zone ?$q$,$q$Oui. Il suffit qu’une partie de la balle touche ou surplombe une partie de la zone.$q$,$q$Vue du dessus d’une balle chevauchant légèrement une ligne imaginaire entre une zone claire et une zone ombrée.$q$,$q$Une balle chevauche légèrement le bord imaginaire de la zone de départ.$q$,$json$[{"label":"Oui","is_correct":true,"explanation":"Correct. Une partie de la balle se trouve au-dessus de la zone."},{"label":"Non, son centre doit être dedans","is_correct":false,"explanation":"Incorrect. La position du centre n’est pas le critère."},{"label":"Non, toute la balle doit être dedans","is_correct":false,"explanation":"Incorrect. Une partie dans ou au-dessus de la zone suffit."}]$json$::jsonb),
('junior-rule-07','official',1,$q$Jusqu’où la zone de départ s’étend-elle derrière la ligne des marques ?$q$,$q$Elle s’étend sur deux longueurs de club vers l’arrière à partir de son bord avant.$q$,$q$Deux marques de départ et deux clubs alignés vers l’arrière pour matérialiser la profondeur.$q$,$q$Deux longueurs de club matérialisent la profondeur derrière les marques de départ.$q$,$json$[{"label":"Deux longueurs de club","is_correct":true,"explanation":"Correct. C’est la profondeur définie de la zone."},{"label":"Une longueur de club","is_correct":false,"explanation":"Incorrect. La zone est plus profonde."},{"label":"Jusqu’au bord de l’aire tondue","is_correct":false,"explanation":"Incorrect. La tonte ne définit pas la limite réglementaire."}]$json$::jsonb),
('junior-rule-07','official',2,$q$La balle de Léo est dans la zone, mais ses deux pieds sont devant les marques. Son départ est-il permis ?$q$,$q$Oui. La balle doit être dans la zone, mais le joueur peut se tenir en dehors pour effectuer le coup.$q$,$q$Balle entre les marques et joueur debout devant leur ligne, vue aérienne claire.$q$,$q$La balle est dans la zone de départ tandis que les pieds du joueur sont devant les marques.$q$,$json$[{"label":"Oui, car la balle est dans la zone","is_correct":true,"explanation":"Correct. La position des pieds peut être extérieure."},{"label":"Non, les deux pieds doivent être dedans","is_correct":false,"explanation":"Incorrect. Cette condition n’existe pas."},{"label":"Seulement si un pied reste dedans","is_correct":false,"explanation":"Incorrect. Aucun pied n’est obligé de se trouver dans la zone."}]$json$::jsonb),

('junior-rule-08','practice',1,$q$En stroke play, tu joues une balle entièrement devant les marques pour commencer le trou. Que dois-tu faire ?$q$,$q$Tu reçois la pénalité générale et dois corriger en jouant depuis l’intérieur de la zone.$q$,$q$Balle entièrement devant les marques puis flèche de retour vers la zone, sans texte.$q$,$q$Une balle jouée devant les marques doit être rejouée depuis la zone de départ en stroke play.$q$,$json$[{"label":"Corriger depuis la zone avec la pénalité générale","is_correct":true,"explanation":"Correct. Le premier coup extérieur ne met pas la balle en jeu en stroke play."},{"label":"Continuer avec cette balle sans pénalité","is_correct":false,"explanation":"Incorrect. L’erreur doit être corrigée."},{"label":"Dropper derrière les marques avec un coup","is_correct":false,"explanation":"Incorrect. Il faut jouer depuis la zone de départ selon ses règles."}]$json$::jsonb),
('junior-rule-08','official',1,$q$Une balle dépasse devant les marques, mais son bord arrière surplombe encore la zone. Est-elle correctement placée ?$q$,$q$Oui. Une partie de la balle au-dessus de la zone suffit.$q$,$q$Gros plan aérien d’une balle majoritairement devant la ligne mais la chevauchant encore.$q$,$q$Une balle dépasse la ligne avant tout en la chevauchant légèrement.$q$,$json$[{"label":"Oui","is_correct":true,"explanation":"Correct. Elle n’est pas entièrement en dehors."},{"label":"Non, le centre est devant","is_correct":false,"explanation":"Incorrect. Le centre de la balle ne détermine pas seul sa position."},{"label":"Non, plus de la moitié doit être dedans","is_correct":false,"explanation":"Incorrect. Aucune règle de moitié ne s’applique."}]$json$::jsonb),
('junior-rule-08','official',2,$q$En match play, Eva commence le trou entièrement devant les marques. Quelle possibilité a son adversaire ?$q$,$q$Il peut annuler rapidement le coup et lui demander de rejouer depuis la zone ; sinon le coup compte sans pénalité.$q$,$q$Deux adversaires au départ, l’un montrant calmement la zone après un coup joué devant les marques.$q$,$q$En match play, un adversaire indique la zone après un départ joué devant les marques.$q$,$json$[{"label":"Annuler rapidement le coup","is_correct":true,"explanation":"Correct. C’est l’option particulière du match play."},{"label":"Ajouter automatiquement deux coups","is_correct":false,"explanation":"Incorrect. La procédure du stroke play ne s’applique pas ici."},{"label":"Déclarer automatiquement le trou perdu","is_correct":false,"explanation":"Incorrect. Ce n’est pas la conséquence prévue."}]$json$::jsonb),

('junior-rule-09','practice',1,$q$Peux-tu jouer ton premier coup avec la balle directement sur l’herbe dans la zone ?$q$,$q$Oui. Le tee n’est pas obligatoire.$q$,$q$Balle posée directement sur une herbe courte entre deux marques de départ.$q$,$q$Une balle repose directement sur l’herbe dans la zone de départ.$q$,$json$[{"label":"Oui","is_correct":true,"explanation":"Correct. La balle peut être jouée depuis le sol."},{"label":"Non, un tee est obligatoire","is_correct":false,"explanation":"Incorrect. Le joueur choisit tee conforme ou sol."},{"label":"Seulement avec un putter","is_correct":false,"explanation":"Incorrect. Le choix du club ne conditionne pas cette possibilité."}]$json$::jsonb),
('junior-rule-09','official',1,$q$Nora forme un petit monticule de sable dans la zone et y pose sa balle. Est-ce permis ?$q$,$q$Oui. Pour cette règle, le sol comprend le sable ou d’autres matières naturelles mises en place pour poser la balle.$q$,$q$Main formant un petit monticule de sable naturel dans la zone de départ.$q$,$q$Une balle est posée sur un petit monticule de sable dans la zone de départ.$q$,$json$[{"label":"Oui","is_correct":true,"explanation":"Correct. Le sable naturel peut servir à poser la balle."},{"label":"Non, seul un tee en bois est permis","is_correct":false,"explanation":"Incorrect. La balle peut être jouée du sol ou d’un support naturel autorisé."},{"label":"Seulement si le sable vient d’un bunker","is_correct":false,"explanation":"Incorrect. Cette origine n’est pas exigée."}]$json$::jsonb),
('junior-rule-09','official',2,$q$Quel support est autorisé pour jouer depuis la zone de départ ?$q$,$q$Un tee conforme placé dans ou sur le sol, ou le sol lui-même, est autorisé.$q$,$q$Tee de golf conforme et balle posée sur l’herbe présentés côte à côte.$q$,$q$Un tee conforme et une balle posée sur l’herbe illustrent les deux options autorisées.$q$,$json$[{"label":"Un tee conforme ou le sol","is_correct":true,"explanation":"Correct. Ce sont les deux possibilités prévues."},{"label":"N’importe quel objet assez haut","is_correct":false,"explanation":"Incorrect. Un support utilisé comme tee doit être conforme."},{"label":"Uniquement un tee fourni par le club","is_correct":false,"explanation":"Incorrect. La règle n’impose pas cette provenance."}]$json$::jsonb),

('junior-rule-10','practice',1,$q$Ta balle tombe du tee avant que tu essaies de la frapper. Y a-t-il une pénalité ?$q$,$q$Non. Elle peut être remise sur un tee n’importe où dans la zone.$q$,$q$Balle au sol près d’un tee vide, joueur encore en préparation.$q$,$q$Une balle tombée repose près de son tee avant le coup.$q$,$json$[{"label":"Non, je peux la retee","is_correct":true,"explanation":"Correct. Aucun coup n’a encore été joué."},{"label":"Oui, un coup","is_correct":false,"explanation":"Incorrect. Une chute avant le coup n’est pas un coup."},{"label":"Non, mais je dois la jouer au sol","is_correct":false,"explanation":"Incorrect. Elle peut être replacée sur un tee dans la zone."}]$json$::jsonb),
('junior-rule-10','official',1,$q$Lors d’un mouvement d’essai, Sami heurte accidentellement la balle sur son tee. Que peut-il faire ?$q$,$q$Comme il n’avait pas l’intention de frapper la balle, ce n’est pas un coup. Il peut la retee sans pénalité.$q$,$q$Club d’entraînement passant près d’un tee, balle tombée juste à côté.$q$,$q$Une balle a été renversée de son tee par un mouvement d’essai.$q$,$json$[{"label":"La retee sans pénalité","is_correct":true,"explanation":"Correct. Le mouvement d’essai n’était pas un coup."},{"label":"Compter un coup et jouer du sol","is_correct":false,"explanation":"Incorrect. Il n’y avait pas d’intention de frapper."},{"label":"Ajouter un coup de pénalité","is_correct":false,"explanation":"Incorrect. Aucun coup de pénalité n’est prévu ici."}]$json$::jsonb),
('junior-rule-10','official',2,$q$La balle commence à tomber du tee au moment où Ana effectue volontairement son coup et elle la frappe. Que se passe-t-il ?$q$,$q$Il n’y a pas de pénalité supplémentaire : le coup compte et la balle est en jeu.$q$,$q$Balle quittant légèrement le tee pendant qu’un club la frappe intentionnellement.$q$,$q$Un club frappe une balle au moment où elle commence à tomber du tee.$q$,$json$[{"label":"Le coup compte sans pénalité supplémentaire","is_correct":true,"explanation":"Correct. Un coup intentionnel sur la balle qui tombe compte."},{"label":"Le coup est annulé automatiquement","is_correct":false,"explanation":"Incorrect. La règle précise que le coup compte."},{"label":"Ana doit ajouter deux coups","is_correct":false,"explanation":"Incorrect. Aucune pénalité supplémentaire n’est appliquée."}]$json$::jsonb),

('junior-rule-11','practice',1,$q$En stroke play, peux-tu jouer avant ton tour pour gagner du temps ?$q$,$q$Oui, si cela est fait de manière sûre et responsable, sans gêner ni donner volontairement un avantage.$q$,$q$Joueuse prête à frapper pendant que ses partenaires se tiennent en sécurité à distance.$q$,$q$Une joueuse prête vérifie que ses partenaires sont en sécurité avant de jouer.$q$,$json$[{"label":"Oui, en Ready Golf sûr et responsable","is_correct":true,"explanation":"Correct. Cette pratique est encouragée en stroke play."},{"label":"Jamais","is_correct":false,"explanation":"Incorrect. Le stroke play permet normalement de jouer hors tour."},{"label":"Oui, même si quelqu’un est devant","is_correct":false,"explanation":"Incorrect. La sécurité reste prioritaire."}]$json$::jsonb),
('junior-rule-11','official',1,$q$Après que tous ont joué leur départ en stroke play, quelle balle devrait normalement être jouée d’abord ?$q$,$q$La balle la plus éloignée du trou se joue normalement en premier.$q$,$q$Trois balles à différentes distances du green, la plus éloignée clairement repérable.$q$,$q$Trois balles sont placées à différentes distances du trou sur un fairway.$q$,$json$[{"label":"La plus éloignée du trou","is_correct":true,"explanation":"Correct. C’est l’ordre normal après le départ."},{"label":"La plus proche du trou","is_correct":false,"explanation":"Incorrect. L’ordre normal commence par la plus éloignée."},{"label":"Toujours celle du meilleur score total","is_correct":false,"explanation":"Incorrect. Le score total ne fixe pas cet ordre."}]$json$::jsonb),
('junior-rule-11','official',2,$q$Le joueur dont c’est normalement le tour est prêt et indique vouloir jouer. Que devrait faire un partenaire qui envisageait le Ready Golf ?$q$,$q$Il devrait généralement attendre que ce joueur joue.$q$,$q$Deux joueurs prêts, celui qui a le tour levant calmement la main pour jouer en premier.$q$,$q$Le joueur dont c’est le tour indique à son partenaire qu’il est prêt à jouer.$q$,$json$[{"label":"Attendre généralement son coup","is_correct":true,"explanation":"Correct. Le Ready Golf ne doit pas créer de gêne ou de conflit."},{"label":"Jouer immédiatement sans regarder","is_correct":false,"explanation":"Incorrect. Ce ne serait ni sûr ni responsable."},{"label":"L’obliger à céder son tour","is_correct":false,"explanation":"Incorrect. Le Ready Golf n’accorde pas ce droit."}]$json$::jsonb),

('junior-rule-12','practice',1,$q$Quelle annonce claire fais-tu avant de jouer une balle provisoire ?$q$,$q$Tu dis que tu joues une balle provisoire, ou tu indiques clairement que tu appliques la Règle 18.3.$q$,$q$Joueur montrant une seconde balle à ses partenaires avant de la poser sur un tee.$q$,$q$Un joueur montre une seconde balle à son groupe avant de jouer.$q$,$json$[{"label":"Je joue une balle provisoire","is_correct":true,"explanation":"Correct. Le caractère provisoire est annoncé sans ambiguïté."},{"label":"J’en joue une autre","is_correct":false,"explanation":"Incorrect. Cette phrase n’indique pas clairement une provisoire."},{"label":"Je recommence","is_correct":false,"explanation":"Incorrect. L’intention sous la Règle 18.3 reste ambiguë."}]$json$::jsonb),
('junior-rule-12','official',1,$q$La balle de Mia est certainement perdue uniquement dans une zone à pénalité. Peut-elle jouer une provisoire selon la Règle 18.3 ?$q$,$q$Non. Une provisoire n’est pas autorisée lorsque la balle ne peut être perdue que dans une zone à pénalité.$q$,$q$Balle ayant franchi clairement la limite rouge d’un étang, joueuse tenant une seconde balle.$q$,$q$Une balle a franchi clairement une limite rouge vers une zone à pénalité.$q$,$json$[{"label":"Non","is_correct":true,"explanation":"Correct. Il faut appliquer les options de la zone à pénalité."},{"label":"Oui, dans tous les cas de balle introuvable","is_correct":false,"explanation":"Incorrect. La provisoire est limitée aux risques prévus par la règle."},{"label":"Oui, mais seulement avec deux coups","is_correct":false,"explanation":"Incorrect. Cette option n’existe pas."}]$json$::jsonb),
('junior-rule-12','official',2,$q$Après un départ possiblement hors limites, où peut-on jouer la provisoire depuis la zone de départ ?$q$,$q$En rejouant depuis la zone de départ, le joueur peut utiliser un tee ou le sol n’importe où dans cette zone.$q$,$q$Première zone de départ avec plusieurs emplacements possibles pour poser une balle provisoire.$q$,$q$Plusieurs positions possibles sont montrées à l’intérieur de la même zone de départ.$q$,$json$[{"label":"N’importe où dans la zone de départ","is_correct":true,"explanation":"Correct. Les règles de la zone s’appliquent à ce nouveau coup."},{"label":"Exactement sur l’emplacement du premier tee","is_correct":false,"explanation":"Incorrect. Le joueur n’est pas limité à ce point précis."},{"label":"En droppant derrière les marques","is_correct":false,"explanation":"Incorrect. Depuis la zone, la balle peut être teed ou jouée du sol."}]$json$::jsonb)
) as question_seed(card_key,kind,variant,prompt,explanation,visual,alt,options)
loop
 select cv.id into v_version_id from public.rules_card_versions cv join public.rules_cards c on c.id=cv.card_id
 where c.stable_key=v_card_key and cv.version=1 and cv.locale='fr';
 insert into public.rules_questions(card_version_id,kind,variant,prompt,explanation,illustration_prompt,image_alt,allows_multiple,editorial_status)
 values(v_version_id,v_kind,v_variant,v_prompt,v_explanation,v_visual,v_alt,false,'needs_review')
 on conflict(card_version_id,kind,variant) do update set prompt=excluded.prompt,explanation=excluded.explanation,
 illustration_prompt=excluded.illustration_prompt,image_alt=excluded.image_alt,allows_multiple=false,editorial_status='needs_review'
 returning id into v_question_id;
 v_position:=0;
 for v_option in select value from jsonb_array_elements(v_options) loop
  v_position:=v_position+1;
  insert into public.rules_question_options(question_id,position,label,is_correct,explanation)
  values(v_question_id,v_position,trim(v_option->>'label'),(v_option->>'is_correct')::boolean,trim(v_option->>'explanation'))
  on conflict(question_id,position) do update set label=excluded.label,is_correct=excluded.is_correct,explanation=excluded.explanation;
 end loop;
end loop;
end;
$migration$;

update public.rules_cards set editorial_status='needs_review'
where stable_key in ('junior-rule-07','junior-rule-08','junior-rule-09','junior-rule-10','junior-rule-11','junior-rule-12');
